class_name OptionCatalog
extends RefCounted

## Runtime for the master option catalog (ADR 0025/0028). Reads the derived
## projection for pool membership and the master JSONL for option records,
## resolves the realm/rarity magnitude policy, and realizes rolled options.
## The projection is generated by `uv run python -m tools data options derive`;
## the master JSONL stays the authored source of truth.

const PROJECTION_PATH := "res://data/item_options/derived/option_pools.json"
const CATALOG_PATH := "res://data/item_options/master_option_pool.jsonl"
const SCALE_PATH := "res://data/item_options/item_magnitude_scale.json"
const PROJECTION_VERSION := 2
const SCALE_VERSION := 1

const RARITY_TIERS := {"common": 0, "magic": 1, "rare": 2, "legendary": 3}

# Magnitude policy per unit: [base_min, base_max, realm_scale, rarity_scale].
# min/max = base * realm_factor * (1 + rarity_index * rarity_scale).
# `realm_scale` (slot 2) is the linear per-realm weight of a RATE read and is
# unused by "magnitude", whose realm axis is the authored scale table.
const MAGNITUDE_POLICY := {
	"magnitude": [1.0, 10.0, 0.10, 0.25],
	"rate": [0.01, 0.05, 0.005, 0.01],
	"fraction": [0.01, 0.06, 0.01, 0.02],
}

## Authored per-realm magnitude multipliers, keyed by realm id: realm id -> float.
## This module owns the magnitude of its own items. The realm axis is DATA - one
## number per realm, seeded once by `uv run python -m tools data options scale
## --write` and hand-editable per realm after that - and there is no formula here
## to restate it, so a designer retunes one realm without touching code.
static var _scales: Dictionary = {}
static var _scales_loaded: bool = false

## Shared instance: thousands of ItemDef resources share one parsed catalog.
static var shared: OptionCatalog = null

## Overlay stack for the item_options family (ADR 0184 §5). Empty means "not
## wired yet": `_ensure_records` reads only the authored CATALOG_PATH. When
## set, the overlay roots are scanned for `.jsonl` files whose records merge
## AFTER the base records, with the declared-override collision policy
## CatalogOverlay enforces.
static var _overlay_stack: Array = []

var _records: Dictionary = {}
var _records_loaded: bool = false
var _projection: Dictionary = {}
var _projection_loaded: bool = false


static func rarity_tier(rarity: StringName) -> int:
	return int(RARITY_TIERS.get(rarity, 0))


static func instance() -> OptionCatalog:
	if shared == null:
		shared = OptionCatalog.new()
	return shared


## Set the family's overlay stack: ordered rows of `{dir, owner,
## declared_overrides, id_field}`. Later rows overlay earlier ones; an id
## collision needs a declared override on the LATER root or the merge fails
## loudly (ADR 0240).
static func set_overlay_roots(stack: Array) -> void:
	_overlay_stack = stack


## The merge stack: the base root as a base-owned row, then the overlay rows
## in order. The base row carries the family's default id_field so the merge
## reads the correct property even when an overlay row omits it.
func _merge_stack() -> Array:
	var stack: Array = [
		{
			"dir": CATALOG_PATH,
			"owner": "base",
			"declared_overrides": [],
			"id_field": "id",
		}
	]
	for row in _overlay_stack:
		stack.append(row)
	return stack


## Merge the family's overlay stack through CatalogOverlay (ADR 0184 §5).
## OptionCatalog reads JSONL, not `.tres`, so the merge scans overlay
## directories for `.jsonl` files and merges the records. Returns a
## dictionary with `ok`, `reason`, `detail`, `merged`, `paths`, `owners`.
func _overlay_merge() -> Dictionary:
	var stack := _merge_stack()
	var merged: Array[Dictionary] = []
	var paths := {}
	var owners := {}
	for root in stack:
		var dir := String(root.get("dir", ""))
		var owner := String(root.get("owner", ""))
		var declared := {}
		for entry in root.get("declared_overrides", []):
			declared[String(entry)] = true
		var files := ContentScan.files_under(dir)
		for path in files:
			if not path.ends_with(".jsonl"):
				continue
			var json := JSON.new()
			for line in FileAccess.get_file_as_string(path).split("\n"):
				line = line.strip_edges()
				if line.is_empty():
					continue
				if json.parse(line) != OK:
					continue
				var record: Dictionary = json.data
				var id := String(record.get("id", ""))
				if id.is_empty():
					continue
				if paths.has(id):
					if declared.has(id):
						var index := int(paths[id])
						merged[index] = {"id": id, "path": path, "owner": owner}
						paths[id] = path
						owners[id] = owner
					else:
						return {
							"ok": false,
							"reason": "undeclared_override",
							"detail":
							"undeclared_override id=%s dir=%s owner=%s" % [id, dir, owner],
							"merged": [],
							"paths": {},
							"owners": {},
						}
				else:
					paths[id] = merged.size()
					merged.append({"id": id, "path": path, "owner": owner})
					owners[id] = owner
	return {
		"ok": true, "reason": "", "detail": "", "merged": merged, "paths": paths, "owners": owners
	}


## Annotate resolved effects with the value window they could legally have taken
## under the item's realm and rarity. Bounds travel with the effect so a reader
## (inspection UI, audit, tooltip) never has to restate the magnitude policy
## and cannot drift from it (ADR 0025).
func with_bounds(
	effects: Array[Dictionary], realm_id: StringName, rarity: StringName
) -> Array[Dictionary]:
	var rarity_index := rarity_tier(rarity)
	var out: Array[Dictionary] = []
	for source in effects:
		var effect: Dictionary = source.duplicate()
		var window := magnitude_bounds(
			String(effect.get("unit", "magnitude")), realm_id, rarity_index
		)
		effect["value_min"] = window["min"]
		effect["value_max"] = window["max"]
		out.append(effect)
	return out


## Resolved pool membership for an activation/context pair, from the generated
## projection. Exposed for debugging, UI provenance and the distribution audit.
func pool_ids(activation: StringName, context: StringName) -> Array[StringName]:
	_ensure_projection()
	var pools: Dictionary = _projection.get("pools", {})
	var ids: Array = pools.get("%s:%s" % [activation, context], [])
	var out: Array[StringName] = []
	for id in ids:
		out.append(StringName(id))
	return out


## Full option record by id from the master JSONL (ADR 0025).
func option_record(option_id: StringName) -> Dictionary:
	_ensure_records()
	return _records.get(String(option_id), {})


func has_option(option_id: StringName) -> bool:
	return not option_record(option_id).is_empty()


## Canonically sorted ids of every active option.
func active_option_ids() -> Array[StringName]:
	_ensure_records()
	var out: Array[StringName] = []
	for key in _records.keys():
		if String(_records[key].get("status", "")) == "active":
			out.append(StringName(key))
	out.sort()
	return out


## A JSON `null` is a real value in the catalog, so string-ish fields are read
## through this helper instead of being coerced straight to StringName.
static func text_field(record: Dictionary, field: String, fallback: String = "") -> String:
	var value = record.get(field, fallback)
	return "" if value == null else String(value)


## Activation channels an option may be authored on, derived from the record's
## declared categories. An option therefore can never claim a consumer that its
## categories do not have (ADR 0028).
func activations_for(record: Dictionary) -> Array[StringName]:
	var declared: Array = record.get("activations", [])
	var out: Array[StringName] = []
	for category in record.get("categories", []):
		var activation := ItemActivation.for_category(StringName(category))
		if activation != &"" and not out.has(activation):
			out.append(activation)
	if declared.is_empty():
		return out
	var narrowed: Array[StringName] = []
	for activation in out:
		if declared.has(String(activation)):
			narrowed.append(activation)
	return narrowed


## Whether an option may be authored on an item that activates through
## `activation`. Keeps every registered option backed by a real consumer.
func allows_activation(option_id: StringName, activation: StringName) -> bool:
	var record := option_record(option_id)
	if record.is_empty():
		return false
	return activations_for(record).has(activation)


## Realize one rolled option for an activation/context pair, excluding ids in
## `used` and any option that shares an exclusive family with an already-used
## one. Returns an empty dictionary when nothing legal remains, so callers stop
## instead of rerolling for a lucky legal roll (ADR 0025).
func roll_next(
	activation: StringName,
	context: StringName,
	used: Array[StringName],
	realm_id: StringName,
	rarity_index: int,
	rng: RandomNumberGenerator
) -> Dictionary:
	var taken := {}
	for id in used:
		taken[String(id)] = true
	var families := {}
	for id in used:
		var record := option_record(id)
		var family := StringName(OptionCatalog.text_field(record, "exclusive_family"))
		if family != &"":
			families[String(family)] = true
	var candidates: Array[Dictionary] = []
	var total := 0.0
	for id in pool_ids(activation, context):
		if taken.has(String(id)):
			continue
		var record := option_record(id)
		if record.is_empty() or not _eligible(record, activation, context):
			continue
		var family := StringName(OptionCatalog.text_field(record, "exclusive_family"))
		if family != &"" and families.has(String(family)):
			continue
		var weight := float(record.get("weight", 0.0))
		if weight <= 0.0:
			continue
		candidates.append({"record": record, "weight": weight})
		total += weight
	if candidates.is_empty() or total <= 0.0:
		return {}
	var pick := rng.randf() * total
	var chosen: Dictionary = candidates[candidates.size() - 1]["record"]
	for candidate in candidates:
		pick -= float(candidate["weight"])
		if pick <= 0.0:
			chosen = candidate["record"]
			break
	return realize(chosen, realm_id, rarity_index, rng)


## Min/max for an option's unit under a realm id and rarity index.
##
## Two reads, and they are deliberately different in KIND, not just in number:
##
## - A **magnitude** looks its realm up in the authored scale table. A magnitude is
##   a value the player sees, and what it is worth at a realm is a balance fact
##   about that realm - so it is one authored number per realm, not a function.
## - A **rate** is a contest input and stays a linear read of the realm ordinal, so
##   a one-realm gap is worth the same at R30 as at R5. That per-unit slope is a
##   legitimate tuning weight, not a magnitude curve.
##
## Keeping the two apart is the point: a magnitude has no reason to be computable,
## and a rate has no reason to be more than linear.
func magnitude_bounds(unit: String, realm_id: StringName, rarity_index: int) -> Dictionary:
	var policy: Array = MAGNITUDE_POLICY.get(unit, MAGNITUDE_POLICY["magnitude"])
	var realm_factor := _realm_factor(unit, realm_id, float(policy[2]))
	var rarity_factor := 1.0 + rarity_index * float(policy[3])
	return {
		"min": float(policy[0]) * realm_factor * rarity_factor,
		"max": float(policy[1]) * realm_factor * rarity_factor,
	}


## Realm factor for one unit. `slope` is the unit's authored per-realm weight and
## is used only by rates.
##
## A magnitude is keyed by realm ID; a rate is a linear read of the ordinal. That
## asymmetry is deliberate and is the whole point (ADR 0050): a magnitude is an
## authored balance fact that must follow its realm if realms are renumbered,
## while a rate's slope is per ordinal step and must not.
func _realm_factor(unit: String, realm_id: StringName, slope: float) -> float:
	if unit == "magnitude":
		return realm_magnitude_scale(realm_id)
	return 1.0 + realm_ordinal(realm_id) * slope  # power: rate-read


## The realm's position on the shared ladder, or -1 when it is not on it. Used
## only by rates; magnitudes never go through this.
static func realm_ordinal(realm_id: StringName) -> int:
	return maxi(0, RealmDefaults.ladder().index_of(realm_id))


## The authored magnitude multiplier for one realm. Resolved by realm ID, never by
## array position, so renumbering a realm moves its authored number with it
## instead of handing it a neighbour's.
##
## An EMPTY realm is not an error: content authors items that are not realm-scaled
## (a currency, for one), and an item with no realm has no per-realm magnitude to
## look up, so the multiplier is the unscaled 1.0. Reporting that would fire
## `push_error` once per roll of every such item, which is a per-roll error storm
## rather than a diagnostic.
##
## A realm that IS named but absent from the table is a genuine content defect and
## still fails loudly: that realm rolls items, so it needs an authored number.
static func realm_magnitude_scale(realm_id: StringName) -> float:
	if realm_id == &"":
		return 1.0
	_ensure_scales()
	if not _scales.has(String(realm_id)):
		push_error("OptionCatalog: no authored magnitude scale for realm '%s'" % realm_id)
		return 1.0
	return float(_scales[String(realm_id)])


static func _ensure_scales() -> void:
	if _scales_loaded:
		return
	_scales_loaded = true
	if not FileAccess.file_exists(SCALE_PATH):
		push_error(
			(
				"OptionCatalog: magnitude scale missing at %s; run `tools data options scale --write`"
				% SCALE_PATH
			)
		)
		return
	var json := JSON.new()
	if json.parse(FileAccess.get_file_as_string(SCALE_PATH)) != OK:
		push_error("OptionCatalog: magnitude scale is malformed")
		return
	var data: Dictionary = json.data
	if int(data.get("version", 0)) != SCALE_VERSION:
		push_error("OptionCatalog: magnitude scale is stale; run `tools data options scale`")
		return
	var realms: Dictionary = data.get("realms", {})
	if realms.is_empty():
		push_error("OptionCatalog: magnitude scale declares no realms")
		return
	for realm_id in realms:
		_scales[String(realm_id)] = float(realms[realm_id])


## option's declared precision and clamped to its declared final bounds.
func roll_value(
	record: Dictionary, realm_id: StringName, rarity_index: int, rng: RandomNumberGenerator
) -> float:
	var unit := String(record.get("unit", "magnitude"))
	var bounds := magnitude_bounds(unit, realm_id, rarity_index)
	var low := float(bounds["min"])
	var high := float(bounds["max"])
	if rng != null and high > low:
		low = lerpf(low, high, rng.randf())
	var value := snappedf(low, pow(10.0, -float(int(record.get("precision", 2)))))
	return clamp_to_bounds(record, value)


## Fixed (item-authored) effect for `{option_id, value}`. Fixed values are
## authored values validated against the option's final bounds, never rerolled.
func fixed_effect(option_id: StringName, value: float) -> Dictionary:
	var record := option_record(option_id)
	if record.is_empty():
		return {}
	return make_effect(record, clamp_to_bounds(record, value), &"fixed")


## Normalized effect entry: the one shape every consumer reads.
static func make_effect(record: Dictionary, value: float, channel: StringName) -> Dictionary:
	var target: Dictionary = record.get("target", {})
	return {
		"option_id": StringName(record.get("id", "")),
		"target_type": StringName(target.get("type", "stat")),
		"target_id": StringName(target.get("id", "")),
		"scope": StringName(target.get("scope", "")),
		"op": StringName(record.get("op", "FLAT")),
		"unit": StringName(record.get("unit", "magnitude")),
		"value": value,
		"channel": channel,
		"family": StringName(record.get("family", "")),
		"label": String(record.get("label", "")),
	}


func realize(
	record: Dictionary, realm_id: StringName, rarity_index: int, rng: RandomNumberGenerator
) -> Dictionary:
	var effect := make_effect(record, roll_value(record, realm_id, rarity_index, rng), &"rolled")
	var window := magnitude_bounds(String(effect.get("unit", "magnitude")), realm_id, rarity_index)
	effect["value_min"] = window["min"]
	effect["value_max"] = window["max"]
	return effect


## Canonically ordered active records; registration order never matters.
func _active_records() -> Array:
	_ensure_records()
	var out: Array = []
	for key in _records.keys():
		var record: Dictionary = _records[key]
		if String(record.get("status", "")) == "active":
			out.append(record)
	out.sort_custom(
		func(a: Dictionary, b: Dictionary) -> bool:
			return String(a.get("id", "")) < String(b.get("id", ""))
	)
	return out


func _eligible(record: Dictionary, activation: StringName, context: StringName) -> bool:
	if not activations_for(record).has(activation):
		return false
	var contexts: Array = record.get("contexts", [])
	return contexts.has(String(context))


static func clamp_to_bounds(record: Dictionary, value: float) -> float:
	var limits: Dictionary = record.get("bounds", {})
	var out := value
	if limits.has("min"):
		out = maxf(out, float(limits["min"]))
	if limits.has("max"):
		out = minf(out, float(limits["max"]))
	return out


func _ensure_records() -> void:
	if _records_loaded:
		return
	_records_loaded = true
	if not FileAccess.file_exists(CATALOG_PATH):
		push_error("OptionCatalog: master catalog missing at %s" % CATALOG_PATH)
		return
	var json := JSON.new()
	for line in FileAccess.get_file_as_string(CATALOG_PATH).split("\n"):
		line = line.strip_edges()
		if line.is_empty():
			continue
		if json.parse(line) == OK and json.data is Dictionary:
			var record: Dictionary = json.data
			_records[String(record.get("id", ""))] = record
	# Overlay records merge AFTER base records, so a mod option with the same
	# id replaces the base one (ADR 0184 §5). The merge is keyed by id, never
	# by array position.
	var merged := _overlay_merge()
	if not bool(merged.get("ok", false)):
		push_error("OptionCatalog: %s" % String(merged.get("detail", "")))
		return
	for entry in merged["merged"]:
		var path := String(entry["path"])
		if path == CATALOG_PATH:
			continue
		for line in FileAccess.get_file_as_string(path).split("\n"):
			line = line.strip_edges()
			if line.is_empty():
				continue
			if json.parse(line) == OK and json.data is Dictionary:
				var record: Dictionary = json.data
				_records[String(record.get("id", ""))] = record


func _ensure_projection() -> void:
	if _projection_loaded:
		return
	_projection_loaded = true
	if not FileAccess.file_exists(PROJECTION_PATH):
		push_error("OptionCatalog: derived pool projection missing at %s" % PROJECTION_PATH)
		return
	var json := JSON.new()
	if json.parse(FileAccess.get_file_as_string(PROJECTION_PATH)) != OK:
		push_error("OptionCatalog: derived pool projection is malformed")
		return
	var data: Dictionary = json.data
	if int(data.get("version", 0)) != PROJECTION_VERSION:
		push_error("OptionCatalog: derived pool projection is stale; run tools data options derive")
		return
	_projection = data
