class_name OptionCatalog
extends RefCounted

## Runtime for the master option catalog (ADR 0025). Loads the derived projection,
## resolves rarity/realm magnitude policy, and generates rolled affixes. The
## projection is generated by `tools data options derive` and is the export-safe
## runtime source; the master JSONL remains the authored SSOT.

const PROJECTION_PATH := "res://data/item_options/derived/option_pools.json"

const RARITY_TIERS := {"common": 0, "magic": 1, "rare": 2, "legendary": 3}

# Magnitude policy per unit: [base_min, base_max, realm_scale, rarity_scale].
# min/max = base * (1 + realm_index * realm_scale) * (1 + rarity_index * rarity_scale).
const MAGNITUDE_POLICY := {
	"magnitude": [1.0, 10.0, 0.10, 0.25],
	"rate": [0.01, 0.05, 0.005, 0.01],
	"fraction": [0.01, 0.05, 0.005, 0.01],
}

var _projection: Dictionary = {}
var _loaded: bool = false


static func rarity_tier(rarity: StringName) -> int:
	return int(RARITY_TIERS.get(rarity, 0))


func _ensure_loaded() -> void:
	if _loaded:
		return
	if ResourceLoader.exists(PROJECTION_PATH):
		var json := JSON.new()
		var text := FileAccess.get_file_as_string(PROJECTION_PATH)
		if json.parse(text) == OK:
			_projection = json.data
	_loaded = true


func option_ids_for(family: StringName, op: String, unit: String) -> Array[StringName]:
	_ensure_loaded()
	var key := "%s:%s:%s" % [family, op, unit]
	var ids: Array = _projection.get(key, [])
	var out: Array[StringName] = []
	for id in ids:
		out.append(StringName(id))
	return out


## Compute the min/max value for an option under a realm and rarity.
func magnitude_bounds(unit: String, realm_index: int, rarity_index: int) -> Dictionary:
	var policy: Array = MAGNITUDE_POLICY.get(unit, MAGNITUDE_POLICY["magnitude"])
	var base_min: float = float(policy[0])
	var base_max: float = float(policy[1])
	var realm_scale: float = float(policy[2])
	var rarity_scale: float = float(policy[3])
	var realm_factor := 1.0 + realm_index * realm_scale
	var rarity_factor := 1.0 + rarity_index * rarity_scale
	return {
		"min": base_min * realm_factor * rarity_factor,
		"max": base_max * realm_factor * rarity_factor,
	}


## Roll `count` affixes for an item from its roll_spec. Selection is weighted,
## without replacement, restricted to the spec's contexts. Returns realized
## StatModifiers tagged with the item's roll source.
func roll_affixes(
	def: ItemDef, realm_index: int, rarity_index: int, count: int, rng: RandomNumberGenerator
) -> Array[StatModifier]:
	var modifiers: Array[StatModifier] = []
	if def.roll_spec.is_empty() or count <= 0:
		return modifiers
	var contexts: Array = def.roll_spec.get("contexts", ["prefix", "postfix"])
	var seen: Dictionary = {}
	for _i in count:
		var candidate := _select_affix(contexts, realm_index, rarity_index, rng, seen)
		if candidate.is_empty():
			break
		seen[candidate["id"]] = true
		modifiers.append(candidate)
	return modifiers


func _select_affix(
	contexts: Array,
	realm_index: int,
	rarity_index: int,
	rng: RandomNumberGenerator,
	seen: Dictionary
) -> StatModifier:
	_ensure_loaded()
	var total_weight := 0.0
	var candidates: Array[Dictionary] = []
	for family in _projection.keys():
		var parts := String(family).split(":")
		if parts.size() != 3:
			continue
		var ids: Array = _projection[family]
		for id in ids:
			if seen.has(id):
				continue
			var weight := _option_weight(StringName(id), contexts)
			if weight <= 0.0:
				continue
			candidates.append(
				{"id": id, "family": parts[0], "op": parts[1], "unit": parts[2], "weight": weight}
			)
			total_weight += weight
	if candidates.is_empty() or total_weight <= 0.0:
		return null
	var pick := rng.randf() * total_weight
	for candidate in candidates:
		pick -= float(candidate["weight"])
		if pick <= 0.0:
			return _realize(candidate, realm_index, rarity_index)
	return null


func _option_weight(option_id: StringName, contexts: Array) -> float:
	# Base weight from the catalog family; restricted to the spec's contexts.
	# Equipment families roll on equipment; base attributes roll on base.
	var family := _family_of(option_id)
	if family == "base":
		return 10.0 if contexts.has("base") else 0.0
	if family == "element":
		return 6.0 if contexts.has("prefix") or contexts.has("postfix") else 0.0
	return 8.0 if contexts.has("prefix") or contexts.has("postfix") else 0.0


func _family_of(option_id: StringName) -> String:
	var id := String(option_id)
	if id.begins_with("base_"):
		return "base"
	if id.begins_with("element_"):
		return "element"
	if id.begins_with("core_"):
		return "core"
	return "other"


func _realize(candidate: Dictionary, realm_index: int, rarity_index: int) -> StatModifier:
	var unit := String(candidate["unit"])
	var bounds := magnitude_bounds(unit, realm_index, rarity_index)
	var value: float = float(bounds["min"]) + (float(bounds["max"]) - float(bounds["min"])) * 0.5
	value = round(value * 100.0) / 100.0
	var op: Stat.Op
	match String(candidate["op"]):
		"FLAT":
			op = Stat.Op.FLAT
		"PERCENT":
			op = Stat.Op.PERCENT
		_:
			op = Stat.Op.MULT
	return StatModifier.new(StringName(candidate["id"]), op, value, &"roll")
