extends TestCase

## The option magnitude window is applied once.
##
## `OptionCatalog.magnitude_bounds` is what the game actually rolls; the Python
## mirror in `tools/options.py` is what the gate validates authored content
## against. If the two drift, the gate blesses item values the runtime would
## never produce. `tools data options parity --write` pins the Python side to
## `tests/fixtures/option_magnitude_windows.json`; this suite asserts the Godot
## side matches it, and `tools check` fails if the fixture itself is stale.
##
## ## Why this suite does not just compare against the fixture's `windows`
##
## The `windows` column is GENERATED by the same Python function the runtime
## mirrors. Comparing the runtime against it is a mirror comparison: the two
## agreed for months while both made an identical wrong read, so 261 green
## assertions were confirming an error. A generated expectation cannot catch a
## shared mistake, because the mistake is in the generator.
##
## So the fixture also carries `scales`: the authored per-realm multipliers keyed
## by REALM ID, taken straight from `data/item_options/item_magnitude_scale.json`
## and never composed by the generator. The expectations below are recomposed from
## that column by a deliberately separate route — resolve the id through the
## ladder, look the scale up BY NAME, multiply with constants typed in this file —
## and then compared against the runtime. A wrong argument, a wrong unit or a
## wrong realm in either implementation moves these numbers and fails here, which
## is disagreement the `windows` column structurally cannot produce.

const FIXTURE := "res://tests/fixtures/option_magnitude_windows.json"
const SCALE_PATH := "res://data/item_options/item_magnitude_scale.json"
const PARITY_VERSION := 2
const UNIT_COUNT := 3
const RARITY_COUNT := 4
const REALM_COUNT := 30
## Absolute, and tight. The authored scale spans 1.0x..3.9x, so the largest window
## is ~68 and 1e-6 is a relative demand of ~1e-8: this suite compares real numbers
## with a real tolerance, which is only possible because the magnitude is data of
## sane size rather than the product of an exponential.
const TOLERANCE := 0.000001

## The policy as this test understands it, written out independently of
## `OptionCatalog.MAGNITUDE_POLICY`: base_min, base_max, rarity_scale. A change to
## the shipped policy has to be made here too, deliberately — that is the point of
## a second copy.
const INDEPENDENT_POLICY := {
	"magnitude": [1.0, 10.0, 0.25],
	"rate": [0.01, 0.05, 0.01],
	"fraction": [0.01, 0.06, 0.02],
}
## Rate and fraction ramp linearly off the realm ordinal. Stated here, not read from
## the implementation, so the test states the intent it is checking.
const INDEPENDENT_RATE_SLOPE := {"rate": 0.005, "fraction": 0.01}


func _fixture() -> Dictionary:
	if not FileAccess.file_exists(FIXTURE):
		return {}
	var parsed = JSON.parse_string(FileAccess.get_file_as_string(FIXTURE))
	return parsed if parsed is Dictionary else {}


func _windows() -> Dictionary:
	var fixture := _fixture()
	assert_ne(fixture, {}, "parity fixture is loadable")
	return fixture.get("windows", {})


## The authored scales, keyed by realm id, as the fixture recorded them.
func _scales() -> Dictionary:
	return _fixture().get("scales", {})


## The scale table the RUNTIME reads, straight off disk. Compared against the
## fixture's copy so a regenerated fixture cannot quietly disagree with the file
## the game actually rolls from.
func _scale_file() -> Dictionary:
	if not FileAccess.file_exists(SCALE_PATH):
		return {}
	var parsed = JSON.parse_string(FileAccess.get_file_as_string(SCALE_PATH))
	return parsed if parsed is Dictionary else {}


func _realm_id(realm_index: int) -> String:
	var realms := RealmDefaults.ladder().realms()
	return String(realms[realm_index].id)


## Realm ORDINAL for a named realm, resolved through the ladder's own id lookup.
## The historic bug was an index passed where an id was expected; going through
## `realm(id)` means a unit confusion in the runtime shows up here as a wrong
## number rather than agreeing with a fixture generated the same wrong way.
func _ordinal_of(realm_id: String) -> int:
	return RealmDefaults.ladder().index_of(StringName(realm_id))


## Expected window recomposed from the authored scale column, not from the
## fixture's generated `windows`. Scale is looked up BY REALM ID; the rarity and
## base terms come from constants typed in this file.
func _independent_window(unit: String, realm_index: int, rarity_index: int) -> Array:
	var policy: Array = INDEPENDENT_POLICY[unit]
	var base_min := float(policy[0])
	var base_max := float(policy[1])
	var rarity_scale := float(policy[2])
	var rarity := 1.0 + rarity_index * rarity_scale
	if unit == "magnitude":
		var scale := float(_scales()[_realm_id(realm_index)])
		return [base_min * scale * rarity, base_max * scale * rarity]
	var slope := float(INDEPENDENT_RATE_SLOPE[unit])
	var realm := 1.0 + realm_index * slope
	return [base_min * realm * rarity, base_max * realm * rarity]


func test_the_fixture_covers_every_unit_realm_and_rarity() -> void:
	var windows := _windows()
	assert_eq(windows.size(), UNIT_COUNT * REALM_COUNT * RARITY_COUNT, "full coverage")
	for unit in ["magnitude", "rate", "fraction"]:
		assert_ne(windows.get("%s:0:0" % unit, []), [], "%s windows present" % unit)


func test_the_fixture_shape_is_the_one_this_suite_understands() -> void:
	# The generated `windows` column cannot catch a shared mistake, so the suite
	# also reads `scales`. If that column ever disappears the independent
	# assertions below would silently degrade into the mirror they exist to
	# replace, so its presence is asserted rather than assumed.
	var fixture := _fixture()
	assert_eq(int(fixture.get("version", 0)), PARITY_VERSION, "parity version is explicit")
	assert_eq((fixture.get("scales", {}) as Dictionary).size(), REALM_COUNT, "scales present")


## The scale column is the authored data the runtime reads, so the two must be the
## same file's contents and not two independent copies that can drift.
func test_the_scale_column_is_the_file_the_runtime_reads() -> void:
	var on_disk := _scale_file()
	assert_ne(on_disk, {}, "scale file is loadable")
	assert_eq(int(on_disk.get("version", 0)), 1, "scale version is explicit")
	assert_eq(_scales(), on_disk.get("realms", {}), "fixture records the runtime's own table")


## Every realm on the ladder has exactly one authored scale, and the scale is
## resolved through the ladder rather than through a position in the file.
func test_every_realm_on_the_ladder_has_one_authored_scale() -> void:
	var scales := _scales()
	assert_eq(scales.size(), REALM_COUNT, "one scale per realm, and no others")
	for realm_index in REALM_COUNT:
		var realm_id := _realm_id(realm_index)
		assert_ne(scales.get(realm_id, null), null, "scale authored for %s" % realm_id)
		assert_almost_eq(
			OptionCatalog.realm_magnitude_scale(realm_index),
			float(scales[realm_id]),
			"the runtime resolves %s at ordinal %d" % [realm_id, realm_index],
			TOLERANCE
		)


## THE INDEPENDENT ASSERTION. Every magnitude window is recomposed from the
## id-keyed scale column through a separate route and compared against the
## runtime, so a wrong unit, a wrong index or a wrong realm in either
## implementation fails here even though the generated `windows` column agrees
## with both by construction.
func test_every_magnitude_window_survives_an_independent_recomposition() -> void:
	var windows := _windows()
	var catalog := OptionCatalog.new()
	for realm_index in REALM_COUNT:
		for rarity_index in RARITY_COUNT:
			var expected := _independent_window("magnitude", realm_index, rarity_index)
			var window := catalog.magnitude_bounds("magnitude", realm_index, rarity_index)
			var key := "magnitude:%d:%d" % [realm_index, rarity_index]
			assert_almost_eq(
				float(window["min"]), float(expected[0]), "%s min, recomposed" % key, TOLERANCE
			)
			assert_almost_eq(
				float(window["max"]), float(expected[1]), "%s max, recomposed" % key, TOLERANCE
			)
			# And it still agrees with the generated column, which is the original
			# parity check retained.
			var generated: Array = windows[key]
			assert_almost_eq(
				float(window["min"]), float(generated[0]), "%s min vs generated" % key, TOLERANCE
			)
			assert_almost_eq(
				float(window["max"]), float(generated[1]), "%s max vs generated" % key, TOLERANCE
			)


func test_the_runtime_matches_every_golden_window() -> void:
	var windows := _windows()
	var catalog := OptionCatalog.new()
	for key in windows:
		var parts := String(key).split(":")
		var window: Dictionary = catalog.magnitude_bounds(parts[0], int(parts[1]), int(parts[2]))
		var expected: Array = windows[key]
		assert_almost_eq(float(window["min"]), float(expected[0]), "%s min" % key, TOLERANCE)
		assert_almost_eq(float(window["max"]), float(expected[1]), "%s max" % key, TOLERANCE)


## Anchored on NAMED realms, at the two ends of the ladder, with the numbers stated
## here rather than read from the table: a realm/ordinal confusion anywhere in the
## chain moves these.
func test_the_named_ends_of_the_ladder_have_the_stated_magnitudes() -> void:
	var catalog := OptionCatalog.new()
	var first := catalog.magnitude_bounds("magnitude", _ordinal_of("qi_refining"), 0)
	assert_almost_eq(float(first["min"]), 1.0, "Qi Refining rolls 1..10", TOLERANCE)
	assert_almost_eq(float(first["max"]), 10.0, "Qi Refining rolls 1..10", TOLERANCE)

	var last := catalog.magnitude_bounds("magnitude", _ordinal_of("primordial_origin"), 0)
	# The authored table's top entry is 3.9, i.e. 1.0 + 0.10 * 29.
	assert_almost_eq(float(last["min"]), 3.9, "Primordial Origin's authored scale", TOLERANCE)
	assert_almost_eq(float(last["max"]), 39.0, "so its window is 3.9..39", TOLERANCE)


## The authored scale is a lookup, not a ramp the runtime recomputes, so it is
## allowed to be whatever the balance owner wrote — including a shape this file
## cannot predict. Asserted by only requiring what the unit actually promises:
## every entry finite and positive, and the ends the table names.
func test_the_scale_is_data_the_runtime_never_recomputes() -> void:
	var scales := _scales()
	for realm_id in scales:
		var scale := float(scales[realm_id])
		assert_eq(scale > 0.0, true, "%s has a positive scale" % realm_id)
		assert_eq(scale < INF, true, "%s has a finite scale" % realm_id)
	# The ordinal the runtime resolves must equal the table's own end values, so a
	# regenerated table cannot quietly renumber which realm is which.
	assert_almost_eq(
		float(scales["qi_refining"]), 1.0, "the first realm is the 1.0x baseline", TOLERANCE
	)
	assert_almost_eq(
		float(scales["primordial_origin"]), 3.9, "the last realm is the 3.9x top", TOLERANCE
	)


func test_the_authored_scale_never_falls_below_the_baseline() -> void:
	# A realm weaker than the one before it is a content error, not a curve
	# property: it is exactly the sort of thing a designer must be able to author,
	# so it is checked rather than assumed.
	var scales := _scales()
	for realm_index in range(1, REALM_COUNT):
		var previous := float(scales[_realm_id(realm_index - 1)])
		var current := float(scales[_realm_id(realm_index)])
		assert_eq(current >= previous, true, "realm %d is not weaker than the last" % realm_index)


func test_rarity_widens_the_window_without_becoming_a_second_scale() -> void:
	var windows := _windows()
	for realm_index in [0, 18, 29]:
		var common: Array = windows["magnitude:%d:0" % realm_index]
		var legendary: Array = windows["magnitude:%d:3" % realm_index]
		assert_eq(float(legendary[1]) > float(common[1]), true, "legendary rolls higher")
		# Rarity is a quality axis: the ratio is the same at every realm, so it
		# scales the window without becoming a second power curve.
		var common_ratio := float(common[1]) / float(common[0])
		var legendary_ratio := float(legendary[1]) / float(legendary[0])
		assert_almost_eq(
			common_ratio, legendary_ratio, "rarity scales, does not re-scale", TOLERANCE
		)


## A rate is a contest input and stays linear in the ordinal. Its realm axis is
## therefore NOT the authored magnitude table, and the two must be distinguishable
## at every realm or "linear" would be unfalsifiable.
func test_a_rate_reads_the_ordinal_linearly_not_the_authored_scale() -> void:
	var windows := _windows()
	var first: Array = windows["rate:0:0"]
	var mid: Array = windows["rate:9:0"]
	var top: Array = windows["rate:29:0"]
	# The rate step is 0.005, so nine realms is 1.045x — not the authored scale.
	assert_almost_eq(
		float(mid[0]) / float(first[0]), 1.045, "a rate is linear in the ordinal", TOLERANCE
	)
	assert_almost_eq(
		float(top[0]) / float(first[0]), 1.145, "and still linear at the top", TOLERANCE
	)
	# And it is demonstrably NOT the authored magnitude scale at that ordinal: if the
	# rate branch started reading the table, "linear" would become unfalsifiable.
	assert_ne(
		float(mid[0]) / float(first[0]),
		float(_scales()[_realm_id(9)]),
		"a rate does not read the authored magnitude scale"
	)


func test_rates_are_recomposed_independently_too() -> void:
	# The independent route covers the rate branch as well, so the distinction
	# between "data" and "linear contest read" is asserted on both sides.
	var windows := _windows()
	var catalog := OptionCatalog.new()
	for realm_index in REALM_COUNT:
		var expected := _independent_window("rate", realm_index, 0)
		var window := catalog.magnitude_bounds("rate", realm_index, 0)
		var key := "rate:%d:0" % realm_index
		assert_almost_eq(float(window["min"]), float(expected[0]), "%s min" % key, TOLERANCE)
		assert_almost_eq(float(window["max"]), float(expected[1]), "%s max" % key, TOLERANCE)
		var generated: Array = windows[key]
		assert_almost_eq(
			float(window["min"]), float(generated[0]), "%s vs generated" % key, TOLERANCE
		)
