# -*- coding: utf-8 -*-
"""Check subcategory names alignment between categories.json and sphere generators."""

import json
from pathlib import Path

import sys
REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
CATEGORIES_PATH = REPO_ROOT / "game/assets/packs/medieval_western/categories.json"

from tools.medieval_scaffold_common import make_asset
from tools.medieval_sphere1_crossroads import generate_sphere1
from tools.medieval_sphere2_architecture import generate_sphere2
from tools.medieval_sphere3_faith import generate_sphere3
from tools.medieval_sphere4_supply_chains import generate_sphere4
from tools.medieval_sphere5_commerce import generate_sphere5
from tools.medieval_sphere6_warfare import generate_sphere6
from tools.medieval_sphere7_ecology import generate_sphere7

def main():
    with open(CATEGORIES_PATH, "r", encoding="utf-8") as f:
        categories = json.load(f)

    all_assets = []
    all_assets.extend(generate_sphere1(make_asset))
    all_assets.extend(generate_sphere2(make_asset))
    all_assets.extend(generate_sphere3(make_asset))
    all_assets.extend(generate_sphere4(make_asset))
    all_assets.extend(generate_sphere5(make_asset))
    all_assets.extend(generate_sphere6(make_asset))
    all_assets.extend(generate_sphere7(make_asset))

    gen_subs_by_cat = {}
    for a in all_assets:
        gen_subs_by_cat.setdefault(a["category"], set()).add(a["sub_category"])

    mismatches = []
    for c in categories:
        cid = c["id"]
        defined_subs = set(c["sub_categories"])
        gen_subs = gen_subs_by_cat.get(cid, set())

        missing_in_gen = defined_subs - gen_subs
        extra_in_gen = gen_subs - defined_subs

        if missing_in_gen or extra_in_gen:
            mismatches.append((cid, defined_subs, gen_subs, missing_in_gen, extra_in_gen))

    if not mismatches:
        print("[PERFECT] All 250 subcategories match 100% between categories.json and generators!")
    else:
        print(f"Found {len(mismatches)} categories with subcategory naming mismatches:")
        for cid, def_s, gen_s, miss, extra in mismatches:
            print(f"\nCategory: {cid}")
            print(f"  Defined in categories.json: {list(def_s)}")
            print(f"  Generated by code:          {list(gen_s)}")
            print(f"  Missing in code:            {list(miss)}")
            print(f"  Extra in code:              {list(extra)}")

if __name__ == "__main__":
    main()
