# -*- coding: utf-8 -*-
"""Sphere II: Built Architecture & Fortifications (6 Categories, 800 Assets).

Categories:
1. modular_timber_frame_fachwerk (160: 4 subs * 27 + 2 subs * 26)
2. village_cottages_and_serf_hovels (120: 5 subs * 24)
3. castles_curtain_walls_and_bastions (180: 6 subs * 30)
4. palace_keeps_and_royal_chambers (120: 6 subs * 20)
5. garrisons_barracks_and_watchtowers (100: 5 subs * 20)
6. city_gates_bridges_and_portals (120: 5 subs * 24)
"""

from __future__ import annotations
from typing import Callable


def generate_sphere2(make_asset: Callable) -> list[dict]:
    items: list[dict] = []

    # =========================================================================
    # 1. modular_timber_frame_fachwerk (160 assets: 4*27 + 2*26)
    # =========================================================================
    cid = "modular_timber_frame_fachwerk"
    var9 = [
        ("raw_oak", "Hewn Oak", "Gỗ Sồi Đẽo", "germanic_holy_roman", "freshly squared oak timbers"),
        (
            "dark_tarred",
            "Pine-Tarred",
            "Quét Hắc Ín",
            "germanic_holy_roman",
            "blackened weather-tar coating",
        ),
        (
            "weathered_silver",
            "Silver-Grey",
            "Xám Phong Hóa",
            "germanic_holy_roman",
            "aged silver-grey timber grain",
        ),
        (
            "mossy_eaves",
            "Moss-Bordered",
            "Viền Rêu Ẩm",
            "germanic_holy_roman",
            "soft green moss along rain drip edges",
        ),
        (
            "red_ochre",
            "Red Ochre Stained",
            "Sơn Nâu Đỏ Ochre",
            "flemish_hanseatic",
            "traditional red ochre earth paint",
        ),
        (
            "whitewashed",
            "Lime-Washed",
            "Quét Vôi Trắng",
            "anglo_norman",
            "calcified white lime-wash coating",
        ),
        (
            "soot_stained",
            "Soot-Darkened",
            "Ám Khói Bếp",
            "germanic_holy_roman",
            "hearth chimney soot patina",
        ),
        (
            "ivy_twined",
            "Ivy-Climbed",
            "Dây Leo Quấn",
            "anglo_norman",
            "delicate climbing ivy tendrils",
        ),
        (
            "reinforced_iron",
            "Iron-Strapped",
            "Gia Cố Nẹp Sắt",
            "germanic_holy_roman",
            "forged iron bracket reinforcing braces",
        ),
    ]

    subs_fachwerk = [
        # Sub 1: 3 archetypes * 9 variants = 27
        (
            "cruck_blade_and_tie_beam",
            [
                (
                    "curved_cruck_blade_arch",
                    "Curved Oak Cruck Blade Arch",
                    "Khung Gỗ Cong Cruck Blade Chịu Lực",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "wood",
                ),
                (
                    "horizontal_tie_beam_collar",
                    "Cross Tie-Beam Collar Assembly",
                    "Xà Ngang Giằng Khung Tie-Beam",
                    [2, 1],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "wood",
                ),
                (
                    "plinth_padstone_footing",
                    "Dwarf Masonry Plinth Padstone",
                    "Tảng Đá Kê Chân Cột Khung Gỗ",
                    [1, 1],
                    "solid",
                    True,
                    "low",
                    None,
                    "structure",
                    "stone",
                ),
            ],
            27,
        ),
        # Sub 2: 3 archetypes * 9 variants = 27
        (
            "jetty_cantilever_bracket_bay",
            [
                (
                    "cantilever_jetty_overhang_bay",
                    "Cantilever Jetty Wall Overhang Bay",
                    "Khối Tầng Nhô Công Xôn Jetty",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "wood",
                ),
                (
                    "carved_dragon_beam_bracket",
                    "Carved Dragon Beam Angle Bracket",
                    "Con Bọ Đỡ Gỗ Góc Chạm Rồng",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "admire",
                    "prop",
                    "wood",
                ),
                (
                    "bressumer_molded_beam",
                    "Molded Jetty Bressumer Sill Beam",
                    "Dầm Ngang Đỡ Sàn Nhô Bressumer",
                    [2, 1],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "wood",
                ),
            ],
            27,
        ),
        # Sub 3: 3 archetypes * 9 variants = 27
        (
            "wattle_daub_and_brick_infill",
            [
                (
                    "herringbone_brick_nogging_panel",
                    "Herringbone Brick Nogging Panel",
                    "Vách Xây Gạch Đỏ Kiểu Xương Cá",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "lime_daubed_hazel_wattle_bay",
                    "Lime-Plastered Wattle & Daub Wall",
                    "Vách Đan Nan Cây Phỉ Trát Vôi Rơm",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "wood",
                ),
                (
                    "st_andrew_cross_timber_brace",
                    "St. Andrew Cross Timber Wall Infill",
                    "Mảng Tường Gỗ Chữ Thập St. Andrew",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "wood",
                ),
            ],
            27,
        ),
        # Sub 4: 3 archetypes * 9 variants = 27
        (
            "leaded_diamond_casement_window",
            [
                (
                    "diamond_lattice_glass_casement",
                    "Diamond Leaded Quarrel Window",
                    "Cửa Sổ Kính Quả Trám Khung Chì",
                    [1, 1],
                    "cover",
                    True,
                    "transparent",
                    "open",
                    "prop",
                    "glass",
                ),
                (
                    "carved_timber_window_lintel",
                    "Floral Carved Oak Window Sill Frame",
                    "Bậu Cửa Sổ Gỗ Sồi Chạm Hoa Văn",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    None,
                    "prop",
                    "wood",
                ),
                (
                    "paneled_interior_oak_shutter",
                    "Hinged Oak Window Folding Shutters",
                    "Cửa Chớp Gỗ Sồi Gấp Mở Trong Nhà",
                    [1, 1],
                    "cover",
                    True,
                    "opaque",
                    "shut",
                    "prop",
                    "wood",
                ),
            ],
            27,
        ),
        # Sub 5: 2 archetypes * 13 variants (or 2*9 + 8) -> 26
        (
            "roof_gable_thatch_and_tile",
            [
                (
                    "steep_pitched_clay_tile_gable",
                    "Steep Plain Clay Tile Roof Gable",
                    "Đầu Hồi Mái Ngói Đất Nung Dốc Đứng",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "cross_spar_thatch_ridge_crest",
                    "Cross-Spar Hazel Thatched Ridge",
                    "Đỉnh Mái Tranh Khóa Cọc Cây Phỉ",
                    [2, 1],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "organic",
                ),
            ],
            26,
        ),
        # Sub 6: 2 archetypes * 13 variants -> 26
        (
            "veranda_porch_and_dormer",
            [
                (
                    "timber_roof_dormer_window",
                    "Gabled Timber Roof Dormer Window",
                    "Cửa Sổ Mái Gác Gỗ Nhô Lên",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "peer_out",
                    "structure",
                    "wood",
                ),
                (
                    "covered_street_porch_entrance",
                    "Timber Street Post Porch Canopy",
                    "Mái Hiên Gỗ Che Cửa Ra Vào Đường Phố",
                    [2, 1],
                    "walk_surface",
                    False,
                    "low",
                    "enter",
                    "structure",
                    "wood",
                ),
            ],
            26,
        ),
    ]

    for sub_id, archetypes, target_count in subs_fachwerk:
        sub_items = []
        if target_count == 27:
            for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
                for v_slug, v_name, v_vn, cult, desc in var9:
                    slug = f"{a_slug}_{v_slug}"
                    name = f"{v_name} {a_name}"
                    vn = f"{a_vn} ({v_vn})"
                    prompt = (
                        f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                        f"Fachwerk half-timbering architecture style, gouache hand-painted, ink contours, isolated on white background."
                    )
                    sub_items.append(
                        make_asset(
                            cid,
                            slug,
                            name,
                            vn,
                            sub_id,
                            fp,
                            col,
                            blk,
                            vis,
                            vrb,
                            f"Fachwerk timber-frame modular element ({a_name}).",
                            False,
                            mat,
                            cult,
                            prompt,
                            asset_type=atype,
                        )
                    )
        elif target_count == 26:
            var13 = var9 + [
                (
                    "lichen_mottled",
                    "Lichen-Mottled",
                    "Lốm Đốm Địa Y",
                    "germanic_holy_roman",
                    "yellow and grey crustose lichen colonies",
                ),
                (
                    "fire_charred",
                    "Fire-Scorched",
                    "Sém Lửa Cháy",
                    "germanic_holy_roman",
                    "surface charred by close proximity to chimney sparks",
                ),
                (
                    "carved_floral",
                    "Floral-Carved",
                    "Chạm Trổ Hoa Lá",
                    "flemish_hanseatic",
                    "deeply gouged folk floral carvings",
                ),
                (
                    "weather_bleached",
                    "Sun-Bleached",
                    "Nắng Tẩy Trắng Bạc",
                    "germanic_holy_roman",
                    "pale bleached timber surface",
                ),
            ]
            for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
                for v_slug, v_name, v_vn, cult, desc in var13:
                    slug = f"{a_slug}_{v_slug}"
                    name = f"{v_name} {a_name}"
                    vn = f"{a_vn} ({v_vn})"
                    prompt = (
                        f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                        f"Fachwerk half-timbering roof and porch element, gouache hand-painted, ink contours, isolated on white background."
                    )
                    sub_items.append(
                        make_asset(
                            cid,
                            slug,
                            name,
                            vn,
                            sub_id,
                            fp,
                            col,
                            blk,
                            vis,
                            vrb,
                            f"Fachwerk modular component ({a_name}).",
                            False,
                            mat,
                            cult,
                            prompt,
                            asset_type=atype,
                        )
                    )
        items.extend(sub_items)

    # =========================================================================
    # 2. village_cottages_and_serf_hovels (120 assets: 5 subs * 24)
    # =========================================================================
    cid = "village_cottages_and_serf_hovels"
    var6_hovel = [
        (
            "muddy_rough",
            "Mud-Splattered",
            "Bám Bùn Đất Thô",
            "universal_feudal",
            "coarse dried clay mud and soil splashes",
        ),
        (
            "weathered_thatch",
            "Weathered Thatch",
            "Tranh Phong Hóa Xám",
            "universal_feudal",
            "silvered decaying wheat straw thatch",
        ),
        (
            "moss_crept",
            "Moss-Covered",
            "Phủ Rêu Dày",
            "universal_feudal",
            "thick green damp moss mounds",
        ),
        (
            "whitewashed_clay",
            "Lime-Whitewashed",
            "Quét Vôi Sáng",
            "universal_feudal",
            "fresh white slaked lime coating",
        ),
        (
            "soot_chimney",
            "Woodsmoke-Darkened",
            "Ám Khói Bếp Củi",
            "universal_feudal",
            "dark fragrant woodsmoke chimney patina",
        ),
        (
            "ramshackle_repaired",
            "Rough-Mended",
            "Chắp Vá Vội",
            "universal_feudal",
            "hastily lashed wattle hurdles and driftwood mends",
        ),
    ]

    subs_hovel = [
        (
            "peasant_turf_roofed_hovel",
            [
                (
                    "turf_eaves_peasant_dwelling",
                    "Single-Room Serf Turf Hovel",
                    "Túp Lều Nông Nô Mái Cỏ Một Gian",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "enter",
                    "structure",
                    "earth",
                ),
                (
                    "smoke_hole_wicker_chimney",
                    "Wicker Chimney Flue Smoke Hole",
                    "Ống Khói Đan Nan Cây Phỉ Thoát Khói",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    None,
                    "prop",
                    "wood",
                ),
                (
                    "earth_fast_timber_post",
                    "Earth-Fast Split Oak Wall Post",
                    "Cột Gỗ Sồi Chôn Thẳng Xuống Đất",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "wood",
                ),
                (
                    "wattle_hurdle_windbreak_fence",
                    "Woven Hazel Hurdle Windbreak",
                    "Vách Đan Cành Phỉ Chắn Gió Bấc",
                    [2, 1],
                    "solid",
                    True,
                    "low",
                    None,
                    "structure",
                    "wood",
                ),
            ],
        ),
        (
            "wattle_thatched_cottage_dwelling",
            [
                (
                    "half_cruck_peasant_cottage",
                    "Thatched Yeoman Cottage Bay",
                    "Gian Nhà Tranh Nông Dân Tự Do",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "enter",
                    "structure",
                    "wood",
                ),
                (
                    "split_oak_plank_door",
                    "Hinged Oak Latch Door with Peg",
                    "Cửa Gỗ Sồi Then Cài Chốt Gỗ",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "open",
                    "structure",
                    "wood",
                ),
                (
                    "shuttered_window_linen_cloth",
                    "Oiled Linen Peasant Window Nook",
                    "Ô Cửa Sổ Bịt Vải Lanh Thấm Dầu",
                    [1, 1],
                    "cover",
                    True,
                    "transparent",
                    "open",
                    "prop",
                    "cloth",
                ),
                (
                    "mud_daub_chimney_breast",
                    "Exterior Mud-Daub Chimney Stack",
                    "Ống Khói Trát Đất Sét Ngoài Nhà",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "earth",
                ),
            ],
        ),
        (
            "outdoor_clay_bread_oven",
            [
                (
                    "domed_clay_communal_oven",
                    "Domed Earth & Stone Bread Oven",
                    "Lò Nướng Bánh Mì Đất Vòm Cộng Đồng",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "bake_bread",
                    "structure",
                    "stone",
                ),
                (
                    "wooden_bakers_peel_shovel",
                    "Long Ashwood Baker's Peel Shovel",
                    "Xẻng Gỗ Dài Đưa Bánh Mì Vào Lò",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "take",
                    "prop",
                    "wood",
                ),
                (
                    "faggot_kindling_wood_stack",
                    "Bundle of Willow Baking Kindling",
                    "Bó Củi Cành Liễu Khô Dành Nướng Bánh",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "harvest_fuel",
                    "prop",
                    "wood",
                ),
                (
                    "bread_cooling_slat_rack",
                    "Slatted Bread Loaf Cooling Bench",
                    "Ghế Dài Nan Gỗ Để Nguội Bánh Mì",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "take_bread",
                    "prop",
                    "wood",
                ),
            ],
        ),
        (
            "drystone_boundary_wall_and_stile",
            [
                (
                    "drystone_coping_field_wall",
                    "Rough Field Boundary Drystone Wall",
                    "Tường Đá Xếp Không Vữa Ngăn Bờ Thửa",
                    [2, 1],
                    "solid",
                    True,
                    "low",
                    "climb_over",
                    "structure",
                    "stone",
                ),
                (
                    "wooden_step_stile_crossing",
                    "Pasture Boundary Timber Stile Steps",
                    "Bậc Thang Gỗ Vượt Tường Bờ Ruộng (Stile)",
                    [1, 1],
                    "walk_surface",
                    False,
                    "low",
                    "step_over",
                    "structure",
                    "wood",
                ),
                (
                    "rustic_swinging_field_gate",
                    "Five-Bar Oak Field Gate with Latch",
                    "Cổng Đồng Gỗ Năm Thanh Kèm Then Cài",
                    [2, 1],
                    "solid",
                    True,
                    "low",
                    "open_gate",
                    "structure",
                    "wood",
                ),
                (
                    "thorny_hawthorn_hedge_line",
                    "Dense Hawthorn Field Boundary Hedge",
                    "Hàng Rào Bụi Cây Táo Gai Rậm Ngăn Gia Súc",
                    [2, 1],
                    "cover",
                    True,
                    "low",
                    None,
                    "flora",
                    "plant",
                ),
            ],
        ),
        (
            "homestead_woodpile_and_shed",
            [
                (
                    "stacked_cordwood_pile",
                    "Neat Stacked Split Firewood Cord",
                    "Đống Củi Gỗ Chẻ Xếp Ngăn Nắp",
                    [2, 1],
                    "cover",
                    True,
                    "low",
                    "harvest_wood",
                    "prop",
                    "wood",
                ),
                (
                    "thatched_lean_to_tool_hovel",
                    "Lean-To Thatched Implement Shed",
                    "Lán Tranh Mái Tựa Để Nông Cụ",
                    [2, 1],
                    "solid",
                    True,
                    "opaque",
                    "inspect",
                    "structure",
                    "wood",
                ),
                (
                    "wooden_chopping_stump_and_wedge",
                    "Oak Chopping Block with Iron Wedge",
                    "Khúc Gỗ Chẻ Củi Kèm Nêm Sắt",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "chop_wood",
                    "prop",
                    "wood",
                ),
                (
                    "wicker_manure_carrying_creel",
                    "Woven Pannier Manure Basket",
                    "Sọt Đan Nan Đựng Phân Bón Ruộng",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "loot",
                    "prop",
                    "wood",
                ),
            ],
        ),
    ]

    for sub_id, archetypes in subs_hovel:
        for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
            for v_slug, v_name, v_vn, cult, desc in var6_hovel:
                slug = f"{a_slug}_{v_slug}"
                name = f"{v_name} {a_name}"
                vn = f"{a_vn} ({v_vn})"
                prompt = (
                    f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                    f"Medieval peasant village and serf hovel vernacular style, gouache hand-painted, ink contours, isolated on white background."
                )
                items.append(
                    make_asset(
                        cid,
                        slug,
                        name,
                        vn,
                        sub_id,
                        fp,
                        col,
                        blk,
                        vis,
                        vrb,
                        f"Peasant homestead vernacular element ({a_name}).",
                        False,
                        mat,
                        cult,
                        prompt,
                        asset_type=atype,
                    )
                )

    # =========================================================================
    # 3. castles_curtain_walls_and_bastions (180 assets: 6 subs * 30)
    # =========================================================================
    cid = "castles_curtain_walls_and_bastions"
    var6_castle = [
        (
            "ashlar_pristine",
            "Dressed Ashlar",
            "Đá Đẽo Phẳng",
            "anglo_norman",
            "fine tight-jointed ashlar limestone blocks",
        ),
        (
            "weathered_mossy",
            "Moss-Veined",
            "Gân Rêu Xanh",
            "anglo_norman",
            "centuries of rain weathering and moss in joints",
        ),
        (
            "siege_scarred",
            "Siege-Battered",
            "Vết Đá Bắn Phá",
            "universal_feudal",
            "cracked masonry from catapult impacts and repaired breaches",
        ),
        (
            "lichen_golden",
            "Golden Lichen",
            "Địa Y Vàng",
            "universal_feudal",
            "crust of golden yellow and orange sun lichen",
        ),
        (
            "banner_flown",
            "Heraldic-Hung",
            "Treo Cờ Hiệu",
            "anglo_norman",
            "fluttering heraldic banners and painted shields",
        ),
        (
            "reinforced_iron",
            "Iron-Portcullis Braced",
            "Gia Cố Sắt Thép",
            "anglo_norman",
            "heavy iron studs, iron grilles and forged braces",
        ),
    ]

    # 5 archetypes * 6 variants = 30 per subcat
    subs_castle = [
        (
            "ashlar_curtain_wall_and_talus",
            [
                (
                    "straight_curtain_wall_bay",
                    "Concentric Stone Curtain Wall Bay",
                    "Đoạn Tường Thành Đá Đồng Tâm",
                    [2, 1],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "sloped_talus_wall_base",
                    "Battered Talus Foundation Wall",
                    "Chân Thành Vát Nghiêng Talus Chống Đào Hầm",
                    [2, 1],
                    "solid",
                    True,
                    "low",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "angle_bastion_curtain_salient",
                    "Salient Corner Angle Wall",
                    "Góc Tường Thành Nhô Ra Pháo Đài",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "covered_intramural_postern_corridor",
                    "Vaulted Intramural Wall Corridor",
                    "Hành Lang Đá Hầm Trong Lòng Tường Thành",
                    [2, 1],
                    "walk_surface",
                    False,
                    "opaque",
                    "patrol",
                    "structure",
                    "stone",
                ),
                (
                    "chemise_low_outer_apron_wall",
                    "Outer Low Chemise Stone Wall",
                    "Tường Thành Đá Thấp Vòng Ngoài Chemise",
                    [2, 1],
                    "solid",
                    True,
                    "low",
                    None,
                    "structure",
                    "stone",
                ),
            ],
        ),
        (
            "crenellation_and_hoarding_crest",
            [
                (
                    "crenellated_merlon_walk",
                    "Stone Merlon Battlements Wall Walk",
                    "Lỗ Châu Mai & Bờ Tường Đứng Bắn Tên",
                    [2, 1],
                    "cover",
                    True,
                    "low",
                    "defend",
                    "structure",
                    "stone",
                ),
                (
                    "timber_hoarding_overhang_gallery",
                    "Projecting Timber Hoarding Gallery",
                    "Hành Lang Gỗ Đua Ra Đỉnh Thành (Hoarding)",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "drop_stones",
                    "structure",
                    "wood",
                ),
                (
                    "slotted_arrow_embrasure_pier",
                    "Deep Pierced Arrow Slit Embrasure",
                    "Lỗ Bắn Tên Xẻ Rãnh Chống Bắn Trả",
                    [1, 1],
                    "cover",
                    True,
                    "low",
                    "shoot",
                    "structure",
                    "stone",
                ),
                (
                    "murder_hole_corbelled_lintel",
                    "Corbelled Floor Murder-Hole Section",
                    "Lỗ Đổ Dầu Nhô Ra Đỡ Bằng Giá Đá",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "pour_pitch",
                    "prop",
                    "stone",
                ),
                (
                    "crenellation_pennon_flagpole",
                    "Battlement Iron Crest Flagpole",
                    "Cột Cờ Sắt Cắm Đỉnh Tường Thành",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "raise_banner",
                    "prop",
                    "iron",
                ),
            ],
        ),
        (
            "round_drum_and_square_tower",
            [
                (
                    "circular_drum_flanking_tower",
                    "Round Stone Flanking Drum Tower",
                    "Tháp Trống Tròn Bọc Sườn Tường Thành",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "enter",
                    "structure",
                    "stone",
                ),
                (
                    "square_norman_mural_tower",
                    "Square Corner Mural Keep Tower",
                    "Tháp Canh Vuông Góc Tường Kiểu Norman",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "enter",
                    "structure",
                    "stone",
                ),
                (
                    "d_shaped_open_gorge_bastion",
                    "D-Shaped Open-Gorge Flanker Bastion",
                    "Pháo Đài Bán Nguyệt Hình Chữ D",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "patrol",
                    "structure",
                    "stone",
                ),
                (
                    "corbelled_corner_bartizan_turret",
                    "Hanging Corner Bartizan Turret",
                    "Chòi Gác Nhô Treo Góc Tháp Bartizan",
                    [1, 1],
                    "solid",
                    True,
                    "opaque",
                    "watch",
                    "structure",
                    "stone",
                ),
                (
                    "conical_slate_spire_roof",
                    "Conical Slate Tower Roof Cap",
                    "Mái Chóp Nhọn Đá Phiến Đỉnh Tháp",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "stone",
                ),
            ],
        ),
        (
            "gatehouse_barbican_and_portcullis",
            [
                (
                    "twin_drum_gatehouse_portal",
                    "Twin-Drum Vaulted Castle Gatehouse",
                    "Cổng Thành Vòm Hai Tháp Tròn Kẹp Hông",
                    [3, 2],
                    "solid",
                    True,
                    "opaque",
                    "open",
                    "structure",
                    "stone",
                ),
                (
                    "iron_shod_oak_portcullis",
                    "Iron-Spiked Oak Grate Portcullis",
                    "Cửa Sập Gỗ Bọc Sắt Portcullis Chặn Cổng",
                    [2, 2],
                    "solid",
                    True,
                    "low",
                    "lower_portcullis",
                    "structure",
                    "iron",
                ),
                (
                    "counterweight_drawbridge_pivot",
                    "Timber Drawbridge with Iron Chains",
                    "Cầu Bập Bênh Gỗ Xích Sắt Vượt Hào",
                    [2, 2],
                    "walk_surface",
                    False,
                    "low",
                    "raise_drawbridge",
                    "structure",
                    "wood",
                ),
                (
                    "outer_barbican_walled_passage",
                    "Outer Defensive Barbican Chokepoint",
                    "Tiền Đồn Barbican Kẹp Hông Dẫn Vào Cổng",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "defend",
                    "structure",
                    "stone",
                ),
                (
                    "winch_chamber_windlass_drum",
                    "Drawbridge Windlass Winding Drum",
                    "Trục Tời Gỗ Xích Sắt Nâng Cầu",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "operate_winch",
                    "prop",
                    "wood",
                ),
            ],
        ),
        (
            "moat_ditch_and_sloping_bank",
            [
                (
                    "water_filled_castle_moat",
                    "Deep Castle Defensive Water Moat",
                    "Hào Nước Sâu Phòng Thủ Lâu Đài",
                    [2, 2],
                    "water",
                    False,
                    "transparent",
                    "swim",
                    "structure",
                    "water",
                ),
                (
                    "dry_ditch_scarp_embankment",
                    "Deep Dry Moat Earth Scarp Slope",
                    "Hào Khô Đào Sâu Vách Dốc Chống Đột Kích",
                    [2, 2],
                    "walk_surface",
                    False,
                    "low",
                    None,
                    "structure",
                    "earth",
                ),
                (
                    "sharpened_stake_fraises_bank",
                    "Inclined Sharpened Fraise Stakes",
                    "Bãi Cọc Nhọn Nghiêng Cắm Bờ Hào",
                    [2, 1],
                    "solid",
                    True,
                    "low",
                    None,
                    "structure",
                    "wood",
                ),
                (
                    "stone_counterscarp_retaining_wall",
                    "Masonry Counterscarp Retaining Wall",
                    "Tường Kè Đá Giữ Bờ Ngoài Hào Thành",
                    [2, 1],
                    "solid",
                    True,
                    "low",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "sluice_gate_water_regulator",
                    "Timber Moat Sluice Control Gate",
                    "Cửa Cống Gỗ Điều Tiết Nước Hào",
                    [1, 1],
                    "cover",
                    True,
                    "low",
                    "turn_sluice",
                    "prop",
                    "wood",
                ),
            ],
        ),
        (
            "arrow_slit_and_intramural_stairs",
            [
                (
                    "spiral_clockwise_newel_stair",
                    "Tight Spiral Clockwise Stone Stair",
                    "Cầu Thang Đá Xoắn Ốc Thuận Chiều Kiếm",
                    [1, 2],
                    "walk_surface",
                    False,
                    "low",
                    "climb",
                    "structure",
                    "stone",
                ),
                (
                    "cross_slit_oilette_loop",
                    "Cross Arrow Loop with Round Oilettes",
                    "Khe Bắn Tên Chữ Thập Có Lỗ Ngắm Tròn",
                    [1, 1],
                    "cover",
                    True,
                    "low",
                    "aim",
                    "prop",
                    "stone",
                ),
                (
                    "stone_corbel_torch_sconce",
                    "Cast Iron Wall Torch Sconce",
                    "Chân Cắm Đuốc Sắt Gắn Tường Đá",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "light_torch",
                    "prop",
                    "iron",
                ),
                (
                    "archers_sitting_bench_recess",
                    "Arched Stone Wall Archer Bench",
                    "Ghế Đá Ngồi Nghỉ Của Xạ Thủ Bắn Cung",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "sit",
                    "prop",
                    "stone",
                ),
                (
                    "potern_sally_iron_studded_door",
                    "Sally Port Iron-Bolted Oak Door",
                    "Cửa Xuất Kích Bí Mật Nạm Đinh Sắt",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "sneak_out",
                    "structure",
                    "wood",
                ),
            ],
        ),
    ]

    for sub_id, archetypes in subs_castle:
        for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
            for v_slug, v_name, v_vn, cult, desc in var6_castle:
                slug = f"{a_slug}_{v_slug}"
                name = f"{v_name} {a_name}"
                vn = f"{a_vn} ({v_vn})"
                prompt = (
                    f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                    f"Concentric stone castle fortification style, gouache hand-painted, ink contours, isolated on white background."
                )
                items.append(
                    make_asset(
                        cid,
                        slug,
                        name,
                        vn,
                        sub_id,
                        fp,
                        col,
                        blk,
                        vis,
                        vrb,
                        f"Concentric stone castle defensive element ({a_name}).",
                        False,
                        mat,
                        cult,
                        prompt,
                        asset_type=atype,
                    )
                )

    # =========================================================================
    # 4. palace_keeps_and_royal_chambers (120 assets: 6 subs * 20)
    # =========================================================================
    cid = "palace_keeps_and_royal_chambers"
    var4_palace = [
        (
            "royal_gilded",
            "Royal Gilded",
            "Dát Vàng Hoàng Gia",
            "french_capetian",
            "regal gold leaf gilding and lapis lazuli accents",
        ),
        (
            "chivalric_crimson",
            "Chivalric Crimson",
            "Nhung Đỏ Thêu Hoa",
            "anglo_norman",
            "deep crimson velvet with heraldic lion embroidery",
        ),
        (
            "somber_feudal_oak",
            "Dark Polished Oak",
            "Gỗ Sồi Đen Đánh Bóng",
            "universal_feudal",
            "centuries-old hand-rubbed beeswax finish",
        ),
        (
            "candlelit_ceremonial",
            "Candlelit Ceremonial",
            "Nến Sáp Nghi Lễ",
            "universal_feudal",
            "gleaming beeswax candle wax drippings and brass glow",
        ),
    ]
    # 5 archetypes * 4 variants = 20 per subcat
    subs_palace = [
        (
            "throne_dais_and_royal_canopy",
            [
                (
                    "canopied_gilded_high_throne",
                    "Carved Lion Royal Oak Throne",
                    "Ngai Vàng Khắc Sư Tử Hoàng Gia",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "sit_throne",
                    "prop",
                    "wood",
                ),
                (
                    "carpeted_stone_throne_dais",
                    "Three-Tiered Carpeted Throne Platform",
                    "Bệ Ngai Vàng Ba Bậc Trải Thảm Nhung",
                    [2, 2],
                    "walk_surface",
                    False,
                    "low",
                    "ascend",
                    "structure",
                    "stone",
                ),
                (
                    "cloth_of_estate_velvet_drape",
                    "Embroidered Velvet Cloth of Estate",
                    "Bức Màn Nhung Thêu Gia Huy Đằng Sau Ngai",
                    [2, 1],
                    "cover",
                    False,
                    "transparent",
                    None,
                    "prop",
                    "cloth",
                ),
                (
                    "royal_sword_of_state_cushion",
                    "Gold-Fringed State Sword Velvet Cushion",
                    "Gối Nhung Đặt Thanh Kiếm Trấn Quốc",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "admire",
                    "prop",
                    "cloth",
                ),
                (
                    "chancellor_standing_rostrum",
                    "Carved Oak Chancellor Reading Rostrum",
                    "Bục Gỗ Sồi Tể Tướng Đứng Đọc Tấu Sớ",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "read",
                    "prop",
                    "wood",
                ),
            ],
        ),
        (
            "great_hall_feasting_trestles",
            [
                (
                    "long_lordly_trestle_banquet_table",
                    "High Table Lordly Feasting Trestle",
                    "Bàn Tiệc Gỗ Dài Cho Lãnh Chúa & Quý Tộc",
                    [3, 1],
                    "cover",
                    False,
                    "low",
                    "dine",
                    "prop",
                    "wood",
                ),
                (
                    "carved_back_lordly_armchair",
                    "High-Backed Baronial Oak Chair",
                    "Ghế Bành Tựa Cao Khắc Phù Hiệu",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "sit",
                    "prop",
                    "wood",
                ),
                (
                    "pewter_flagon_and_platter_buffet",
                    "Standing Sideboard Buffet of Flagons",
                    "Tủ Kệ Trưng Bày Đĩa Bạc & Bình Rượu",
                    [2, 1],
                    "solid",
                    True,
                    "opaque",
                    "loot",
                    "prop",
                    "wood",
                ),
                (
                    "minstrels_gallery_balcony_rail",
                    "Carved Minstrels' Music Gallery Balcony",
                    "Ban Công Gỗ Cho Ban Nhạc Biểu Diễn",
                    [2, 1],
                    "walk_surface",
                    False,
                    "low",
                    "play_music",
                    "structure",
                    "wood",
                ),
                (
                    "roast_boar_pewter_serving_tray",
                    "Silver Serving Platter Roasted Boar",
                    "Mâm Bạc Lớn Đựng Thịt Heo Rừng Quay",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "feast",
                    "prop",
                    "iron",
                ),
            ],
        ),
        (
            "monumental_carved_stone_hearth",
            [
                (
                    "hooded_heraldic_palace_chimneypiece",
                    "Monumental Hooded Stone Fireplace",
                    "Lò Sưởi Đá Lớn Có Mái Chóp Phù Hiệu",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "warm_hands",
                    "structure",
                    "stone",
                ),
                (
                    "wrought_iron_andirons_firedogs",
                    "Cast Iron Beast-Headed Firedogs",
                    "Cặp Chân Sắt Đỡ Củi Hình Đầu Quái Thú",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "stoke_fire",
                    "prop",
                    "iron",
                ),
                (
                    "rotating_spit_clockwork_roaster",
                    "Weight-Driven Iron Meat Roasting Spit",
                    "Trục Quay Thịt Bằng Sắt Chạy Quả Lắc",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "roast",
                    "prop",
                    "iron",
                ),
                (
                    "ash_pan_and_bronze_fire_tongs",
                    "Brass Hearth Shovel & Fire Tongs Set",
                    "Bộ Kẹp Than & Xẻng Tro Bằng Đồng Thau",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "take",
                    "prop",
                    "iron",
                ),
                (
                    "stack_of_scented_applewood_logs",
                    "Stack of Split Scented Orchard Logs",
                    "Đống Gỗ Cây Táo Khô Thơm Để Sưởi",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "add_fuel",
                    "prop",
                    "wood",
                ),
            ],
        ),
        (
            "four_poster_oak_bedchamber",
            [
                (
                    "brocade_canopied_four_poster_bed",
                    "Four-Poster Carved Oak State Bed",
                    "Giường Gỗ Bốn Cột Có Mái Trướng Gấm",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "sleep",
                    "prop",
                    "wood",
                ),
                (
                    "iron_banded_dower_chest",
                    "Heavy Oak Clothes Dower Chest",
                    "Rương Gỗ Sồi Nẹp Sắt Đựng Vải Vóc",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "open",
                    "prop",
                    "wood",
                ),
                (
                    "copper_warming_pan_with_long_handle",
                    "Long-Handled Copper Bed Warming Pan",
                    "Chảo Đồng Dài Đựng Than Sưởi Ấm Giường",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "warm_bed",
                    "prop",
                    "iron",
                ),
                (
                    "velvet_curtained_privy_wardrobe",
                    "Garderobe Chamber Screen Wall",
                    "Bình Phong Che Góc Vệ Sinh Garderobe",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "use_privy",
                    "prop",
                    "wood",
                ),
                (
                    "curved_x_frame_lady_folding_chair",
                    "Silk-Cushioned X-Frame Folding Chair",
                    "Ghế Xếp Khung Chữ X Nệm Lụa Quý Bà",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "sit",
                    "prop",
                    "wood",
                ),
            ],
        ),
        (
            "chivalric_heraldic_tapestry",
            [
                (
                    "arтивное_thousand_flower_tapestry",
                    "Millefleurs Unicorn Wall Tapestry",
                    "Thảm Treo Tường Ngàn Hoa Millefleurs",
                    [2, 2],
                    "cover",
                    False,
                    "transparent",
                    "admire",
                    "prop",
                    "cloth",
                ),
                (
                    "knightly_quest_woven_hanging",
                    "Chivalric Grail Quest Woven Hanging",
                    "Tấm Thảm Thêu Tích Hiệp Sĩ Tìm Chén Thánh",
                    [2, 2],
                    "cover",
                    False,
                    "transparent",
                    "read_story",
                    "prop",
                    "cloth",
                ),
                (
                    "heraldic_quartered_lineage_banner",
                    "Quartered Lineage Silk Armorial Drapery",
                    "Cờ Thêu Gia Phả Kết Hợp Bốn Dòng Họ",
                    [1, 2],
                    "cover",
                    False,
                    "transparent",
                    "inspect",
                    "prop",
                    "cloth",
                ),
                (
                    "iron_tapestry_hanging_rod_finial",
                    "Forged Fleur-de-lis Tapestry Rod",
                    "Thanh Sắt Treo Thảm Đầu Hình Hoa Huệ",
                    [2, 1],
                    "cover",
                    False,
                    "transparent",
                    None,
                    "prop",
                    "iron",
                ),
                (
                    "heraldic_painted_wooden_shield_mount",
                    "Wall Mounted Tournament Heater Shield",
                    "Khiên Hiệp Sĩ Gắn Tường Trang Trí",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "examine_crest",
                    "prop",
                    "wood",
                ),
            ],
        ),
        (
            "chancery_and_treasury_chests",
            [
                (
                    "iron_bound_armada_bullion_chest",
                    "Multi-Lock Iron Bullion Vault Chest",
                    "Rương Sắt Đúc Bảy Ổ Khóa Đựng Tiền Vàng",
                    [1, 1],
                    "solid",
                    True,
                    "low",
                    "unlock_vault",
                    "prop",
                    "iron",
                ),
                (
                    "chancery_seal_parchment_press",
                    "Royal Great Seal Lead & Wax Press",
                    "Máy Ép Con Dấu Sáp & Chì Hoàng Gia",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "affix_seal",
                    "prop",
                    "iron",
                ),
                (
                    "cubbyhole_charter_scroll_cabinet",
                    "Oak Chancery Scroll Pigeonhole Desk",
                    "Tủ Gỗ Sồi Chia Ngăn Chứa Cuộn Hiến Chương",
                    [2, 1],
                    "solid",
                    True,
                    "opaque",
                    "search_archive",
                    "prop",
                    "wood",
                ),
                (
                    "standing_inkhorn_and_quill_stand",
                    "Gilded Bronze Inkstand & Quill Rack",
                    "Nghiên Mực Đồng Mạ Vàng & Ống Bút Lông",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "write",
                    "prop",
                    "iron",
                ),
                (
                    "linen_tally_stick_storage_basket",
                    "Notched Hazel Debt Tally Stick Basket",
                    "Giỏ Đựng Thẻ Gỗ Khía Ghi Nợ Ngân Khố",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "inspect_debts",
                    "prop",
                    "wood",
                ),
            ],
        ),
    ]

    for sub_id, archetypes in subs_palace:
        for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
            for v_slug, v_name, v_vn, cult, desc in var4_palace:
                slug = f"{a_slug}_{v_slug}"
                name = f"{v_name} {a_name}"
                vn = f"{a_vn} ({v_vn})"
                prompt = (
                    f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                    f"High medieval royal palace and keep court style, gouache hand-painted, ink contours, isolated on white background."
                )
                items.append(
                    make_asset(
                        cid,
                        slug,
                        name,
                        vn,
                        sub_id,
                        fp,
                        col,
                        blk,
                        vis,
                        vrb,
                        f"Palace keep and royal court element ({a_name}).",
                        False,
                        mat,
                        cult,
                        prompt,
                        asset_type=atype,
                    )
                )

    # =========================================================================
    # 5. garrisons_barracks_and_watchtowers (100 assets: 5 subs * 20)
    # =========================================================================
    cid = "garrisons_barracks_and_watchtowers"
    var4_garrison = [
        (
            "iron_disciplined",
            "Munitions-Grade",
            "Quân Trang Chuẩn",
            "universal_feudal",
            "plain functional iron studs and tough oiled timber",
        ),
        (
            "weather_hardened",
            "Frontier-Weathered",
            "Gió Bụi Biên Ải",
            "universal_feudal",
            "scoured by harsh border winds and rain",
        ),
        (
            "torch_smoked",
            "Pine-Smoked",
            "Ám Khói Đuốc",
            "universal_feudal",
            "soot-caked corners from midnight watch torches",
        ),
        (
            "alert_ready",
            "Combat-Ready",
            "Sẵn Sàng Chiến Đấu",
            "universal_feudal",
            "strung bows, racked weapons, and primed torches",
        ),
    ]
    # 5 archetypes * 4 variants = 20 per subcat
    subs_garrison = [
        (
            "border_stone_watchtower",
            [
                (
                    "square_border_watchtower_keep",
                    "Isolated Square Border Stone Sentry Tower",
                    "Tháp Canh Đá Đơn Độc Biên Giới",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "enter",
                    "structure",
                    "stone",
                ),
                (
                    "timber_roofed_sentry_lookout",
                    "Covered Timber Observation Platform",
                    "Bục Quan Sát Gỗ Có Mái Che Đỉnh Tháp",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "scout",
                    "structure",
                    "wood",
                ),
                (
                    "sentry_alarm_bronze_bell",
                    "Tripod Frame Garrison Alarm Bell",
                    "Chuông Đồng Báo Động Khung Chân Ba",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "ring_alarm",
                    "prop",
                    "iron",
                ),
                (
                    "stone_sentry_fire_brazier",
                    "Iron Cage Beacon Fire Basket",
                    "Lồng Sắt Đốt Lửa Hiệu Đêm",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "light_beacon",
                    "prop",
                    "iron",
                ),
                (
                    "retractable_timber_entry_ladder",
                    "Counterbalanced Heavy Entry Ladder",
                    "Thang Gỗ Rút Lên Tránh Đột Kích",
                    [1, 2],
                    "walk_surface",
                    False,
                    "low",
                    "retract",
                    "structure",
                    "wood",
                ),
            ],
        ),
        (
            "soldiers_timber_bunkhouse",
            [
                (
                    "two_tier_soldier_bunk_bed",
                    "Double-Tier Rough Pine Soldiers' Bunk",
                    "Giường Tầng Gỗ Thông Đơn Sơ Của Lính",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "rest",
                    "prop",
                    "wood",
                ),
                (
                    "straw_stuffed_tick_mattress",
                    "Coarse Burlap Straw Bedding Sack",
                    "Đệm Rơm Bao Tải Thô Của Lính Gác",
                    [1, 1],
                    "walk_surface",
                    False,
                    "low",
                    "sleep",
                    "prop",
                    "organic",
                ),
                (
                    "soldiers_iron_kit_chest",
                    "Footlocker Munitions Storage Box",
                    "Hòm Gỗ Để Đồ Cá Nhân Của Quân Sĩ",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "loot",
                    "prop",
                    "wood",
                ),
                (
                    "central_dice_and_ale_table",
                    "Heavy Oak Mess Hall Drinking Table",
                    "Bàn Ăn & Lắc Xúc Xắc Gỗ Sồi",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "gamble",
                    "prop",
                    "wood",
                ),
                (
                    "pewter_tankard_and_mess_kit",
                    "Iron Mess Tin & Wooden Spoon Set",
                    "Khay Ăn Bằng Sắt & Thìa Gỗ Của Lính",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "eat_rations",
                    "prop",
                    "iron",
                ),
            ],
        ),
        (
            "armory_rack_spears_and_halberds",
            [
                (
                    "vertical_polearm_spear_rack",
                    "Upright Oak Halberd & Billhook Rack",
                    "Giá Gỗ Dựng Kích & Giáo Halberd",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "take_weapon",
                    "prop",
                    "wood",
                ),
                (
                    "munition_crossbow_hanging_peg",
                    "Wall Rack of Loaded Crossbows",
                    "Giá Gỗ Treo Nỏ Bắn Đá & Bắn Tiêu",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "take_crossbow",
                    "prop",
                    "wood",
                ),
                (
                    "crossbow_bolt_quiver_barrel",
                    "Oak Tub Filled with Iron Quarrels",
                    "Thùng Gỗ Chứa Tên Nỏ Bọc Sắt",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "restock_bolts",
                    "prop",
                    "wood",
                ),
                (
                    "armorers_padded_gambeson_stand",
                    "Munition Jack & Kettle Hat Display",
                    "Giá Treo Áo Giáp Độn Vải & Nón Sắt",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "equip_armor",
                    "prop",
                    "wood",
                ),
                (
                    "iron_sword_oil_and_whetstone_bench",
                    "Grease Tub & Weapon Polishing Bench",
                    "Bàn Mài Gươm Kèm Chậu Mỡ Chống Gỉ",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "sharpen_sword",
                    "prop",
                    "stone",
                ),
            ],
        ),
        (
            "archery_practice_butt_range",
            [
                (
                    "straw_archery_boss_target",
                    "Coarse Straw Archery Target Butt",
                    "Bia Rơm Bện Dành Cho Cung Thủ Luyện Tập",
                    [1, 2],
                    "cover",
                    True,
                    "low",
                    "shoot_target",
                    "prop",
                    "organic",
                ),
                (
                    "shooting_stake_distance_mark",
                    "Painted Distance Archer Shooting Post",
                    "Cọc Gỗ Sơn Đánh Dấu Cự Ly Bắn",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "aim_from_here",
                    "prop",
                    "wood",
                ),
                (
                    "quiver_spike_ground_stand",
                    "Ground-Spiked Arrow Floor Quiver",
                    "Bao Tên Cắm Thẳng Xuống Đất Dễ Rút",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "grab_arrows",
                    "prop",
                    "organic",
                ),
                (
                    "archer_bow_stringing_brace",
                    "Wooden Bow Stave Clamping Bench",
                    "Bàn Gỗ Giữ Cánh Cung Để Lên Dây",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "string_bow",
                    "prop",
                    "wood",
                ),
                (
                    "missed_arrow_in_turf_cluster",
                    "Cluster of Arrows Stuck in Grass",
                    "Chùm Mũi Tên Bắn Trượt Cắm Vào Cỏ",
                    [1, 1],
                    "walk_surface",
                    False,
                    "transparent",
                    "collect_arrows",
                    "prop",
                    "iron",
                ),
            ],
        ),
        (
            "signal_fire_beacon_turret",
            [
                (
                    "elevated_signal_wood_pyre",
                    "Timber-Framed High Signal Wood Pyre",
                    "Giàn Gỗ Chất Đầy Củi Khô Đốt Lửa Hiệu",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "light_pyre",
                    "structure",
                    "wood",
                ),
                (
                    "tar_barrel_quick_igniter",
                    "Pitch Barrel & Brimstone Fuse Box",
                    "Thùng Nhựa Hắc Ín Dẫn Cháy Cực Nhanh",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "ignite_fuse",
                    "prop",
                    "wood",
                ),
                (
                    "watchmans_shelter_lean_to",
                    "Sentry Windproof Canvas Lean-To",
                    "Chòi Bạt Che Gió Cho Lính Canh Đốt Lửa",
                    [1, 1],
                    "cover",
                    True,
                    "low",
                    "rest",
                    "structure",
                    "cloth",
                ),
                (
                    "horn_sounding_stand_perch",
                    "Great War Horn on Wrought Iron Perch",
                    "Tù Và Chiến Trận Lớn Trên Giá Sắt",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "sound_horn",
                    "prop",
                    "iron",
                ),
                (
                    "stacked_dry_pine_faggots",
                    "Dry Pine Beacon Kindling Stack",
                    "Chồng Cành Thông Khô Chờ Đốt Lửa Báo",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "add_kindling",
                    "prop",
                    "wood",
                ),
            ],
        ),
    ]

    for sub_id, archetypes in subs_garrison:
        for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
            for v_slug, v_name, v_vn, cult, desc in var4_garrison:
                slug = f"{a_slug}_{v_slug}"
                name = f"{v_name} {a_name}"
                vn = f"{a_vn} ({v_vn})"
                prompt = (
                    f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                    f"Medieval garrison barracks and watchtower style, gouache hand-painted, ink contours, isolated on white background."
                )
                items.append(
                    make_asset(
                        cid,
                        slug,
                        name,
                        vn,
                        sub_id,
                        fp,
                        col,
                        blk,
                        vis,
                        vrb,
                        f"Garrison defense element ({a_name}).",
                        False,
                        mat,
                        cult,
                        prompt,
                        asset_type=atype,
                    )
                )

    # =========================================================================
    # 6. city_gates_bridges_and_portals (120 assets: 5 subs * 24)
    # =========================================================================
    cid = "city_gates_bridges_and_portals"
    var6_portal = [
        (
            "ashlar_civic",
            "Civic Limestone",
            "Đá Vôi Đô Thị",
            "universal_feudal",
            "neat civic limestone ashlar masonry",
        ),
        (
            "wagon_scarred",
            "Cart-Rut Scratched",
            "Xước Vết Trục Xe",
            "universal_feudal",
            "worn corner guard stones and iron wheel scrape grooves",
        ),
        (
            "rain_damp_moss",
            "River-Misted",
            "Sương Sông Ẩm Ướt",
            "universal_feudal",
            "slick green water-spray moss on lower piers",
        ),
        (
            "heraldic_painted",
            "Town-Arms Painted",
            "Vẽ Huy Hiệu Thành Thị",
            "flemish_hanseatic",
            "bright civic heraldry shields and banners",
        ),
        (
            "iron_spiked",
            "Iron-Spiked Defense",
            "Cọc Sắt Chống Xâm Nhập",
            "universal_feudal",
            "sharp iron caltrops and spiked gate collars",
        ),
        (
            "lantern_lit",
            "Torch-Illuminated",
            "Soi Sáng Ánh Đuốc",
            "universal_feudal",
            "iron-framed grease lanterns casting warm glow",
        ),
    ]

    subs_portal = [
        (
            "twin_towered_city_gatehouse",
            [
                (
                    "twin_drum_city_gate_portal",
                    "Twin-Drum Vaulted City Entrance Gate",
                    "Cổng Thành Vòm Đôi Hai Tháp Tròn Đô Thị",
                    [3, 2],
                    "solid",
                    True,
                    "opaque",
                    "pass_gate",
                    "structure",
                    "stone",
                ),
                (
                    "overhead_curfew_portcullis_slot",
                    "Iron-Banded Oak Night Curfew Grate",
                    "Cổng Sắt Hạ Ban Đêm Giới Nghiêm",
                    [2, 2],
                    "solid",
                    True,
                    "low",
                    "lower_gate",
                    "structure",
                    "iron",
                ),
                (
                    "tax_collector_nook_window",
                    "Gate Toll Collector Stone Office Bay",
                    "Buồng Thu Thuế Cửa Ô Bằng Đá",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "pay_toll",
                    "structure",
                    "stone",
                ),
                (
                    "parade_heraldic_city_arms",
                    "Carved Polychrome City Coat of Arms",
                    "Huy Hiệu Thành Phố Bằng Đá Sơn Màu",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "inspect",
                    "prop",
                    "stone",
                ),
            ],
        ),
        (
            "norman_barrel_arch_stone_bridge",
            [
                (
                    "ribbed_arch_bridge_span",
                    "Masonry Barrel Arch River Span",
                    "Nhịp Cầu Đá Vòm Vượt Sông Kiểu Norman",
                    [3, 2],
                    "walk_surface",
                    False,
                    "low",
                    "cross_bridge",
                    "structure",
                    "stone",
                ),
                (
                    "pointed_cutwater_pier_starlings",
                    "Pointed Triangular River Cutwater",
                    "Mũi Rẽ Nước Bằng Đá Bảo Vệ Trụ Cầu",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "stone_parapet_refuge_alcove",
                    "Bridge Parapet Pedestrian Refuge Niche",
                    "Hốc Tránh Xe Cho Người Đi Bộ Trên Cầu",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "take_refuge",
                    "structure",
                    "stone",
                ),
                (
                    "bridge_chapel_wayside_portal",
                    "Small Arched Bridge Sentry Chapel",
                    "Nhà Nguyện Nhỏ Xây Trên Trụ Cầu Đá",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "pray",
                    "structure",
                    "stone",
                ),
            ],
        ),
        (
            "timber_oxcart_trestle_bridge",
            [
                (
                    "heavy_timber_trestle_pier",
                    "Cross-Braced Oak Trestle River Pier",
                    "Trụ Cầu Gỗ Sồi Khung Giằng Chữ X",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "wood",
                ),
                (
                    "log_plank_wagon_deck",
                    "Heavy Hewn Log Plank Bridge Deck",
                    "Mặt Cầu Lát Ván Gỗ Cho Xe Bò Đi",
                    [2, 2],
                    "walk_surface",
                    False,
                    "low",
                    "drive_cart",
                    "structure",
                    "wood",
                ),
                (
                    "split_rail_bridge_guardrail",
                    "Rustic Split-Rail Bridge Parapet",
                    "Lan Can Cầu Bằng Cây Gỗ Tự Nhiên",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    None,
                    "structure",
                    "wood",
                ),
                (
                    "river_drift_catcher_ice_breaker",
                    "Angled Timber Ice-Breaker Boom",
                    "Thanh Gỗ Nghiêng Cản Băng Trôi Đầu Cầu",
                    [1, 2],
                    "solid",
                    True,
                    "low",
                    None,
                    "structure",
                    "wood",
                ),
            ],
        ),
        (
            "curfew_bell_and_toll_station",
            [
                (
                    "curfew_bell_timber_belfry",
                    "Roadside Curfew Bell Timber Spire",
                    "Tháp Chuông Gỗ Báo Giờ Giới Nghiêm",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "sound_curfew",
                    "structure",
                    "wood",
                ),
                (
                    "toll_barrier_pivoting_boom",
                    "Iron-Counterweighted Timber Toll Bar",
                    "Thanh Chắn Cần Cẩu Thu Phí Đường",
                    [2, 1],
                    "cover",
                    True,
                    "low",
                    "lift_barrier",
                    "prop",
                    "wood",
                ),
                (
                    "toll_collectors_money_dish",
                    "Iron Coin Weighing Bowl & Receipt Box",
                    "Bát Đồng Cân Tiền Thu Phí & Hộp Biên Lai",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "drop_coin",
                    "prop",
                    "iron",
                ),
                (
                    "town_charter_law_display_pillar",
                    "Pillar of Civic Decrees & Penalties",
                    "Trụ Đá Treo Bảng Luật Lệ Thành Phố",
                    [1, 1],
                    "solid",
                    True,
                    "opaque",
                    "read_laws",
                    "prop",
                    "stone",
                ),
            ],
        ),
        (
            "river_ford_and_stepping_stones",
            [
                (
                    "granite_river_stepping_stones",
                    "Line of Flat Granite Stepping Stones",
                    "Dãy Phiến Đá Hoa Cương Băng Qua Suối",
                    [2, 1],
                    "walk_surface",
                    False,
                    "transparent",
                    "step_across",
                    "structure",
                    "stone",
                ),
                (
                    "gravel_shallows_wagon_ford",
                    "Pebble Shallows Ox-Cart Ford Track",
                    "Đoạn Lội Nước Nông Cho Xe Ngựa Bò Lội",
                    [2, 2],
                    "walk_surface",
                    False,
                    "transparent",
                    "ford_river",
                    "structure",
                    "stone",
                ),
                (
                    "depth_gauge_notched_timber_post",
                    "Water Height Notched Gauge Post",
                    "Cọc Gỗ Khía Vạch Đo Mực Nước Lũ",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "check_depth",
                    "prop",
                    "wood",
                ),
                (
                    "safety_guide_rope_river_ferry",
                    "Hemp Guide Line Across Shallow River",
                    "Dây Thừng Dẫn Đường Băng Qua Sông",
                    [2, 1],
                    "walk_surface",
                    False,
                    "transparent",
                    "hold_line",
                    "prop",
                    "organic",
                ),
            ],
        ),
    ]

    for sub_id, archetypes in subs_portal:
        for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
            for v_slug, v_name, v_vn, cult, desc in var6_portal:
                slug = f"{a_slug}_{v_slug}"
                name = f"{v_name} {a_name}"
                vn = f"{a_vn} ({v_vn})"
                prompt = (
                    f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                    f"Medieval city gates and river bridges style, gouache hand-painted, ink contours, isolated on white background."
                )
                items.append(
                    make_asset(
                        cid,
                        slug,
                        name,
                        vn,
                        sub_id,
                        fp,
                        col,
                        blk,
                        vis,
                        vrb,
                        f"City gate and river crossing element ({a_name}).",
                        False,
                        mat,
                        cult,
                        prompt,
                        asset_type=atype,
                    )
                )

    return items
