"""Sphere III: Faith, Monasticism, Mortality & Occult (7 Categories, 760 Assets).

Categories:
1. gothic_cathedrals_and_monumental_abbeys (140: 2*24 + 4*23)
2. monasteries_cloisters_and_scriptoria (120: 5 subs * 24)
3. parish_chapels_and_wayside_shrines (100: 5 subs * 20)
4. graveyards_crypts_and_charnel_houses (110: 5 subs * 22)
5. medieval_alchemy_and_natural_philosophy (100: 5 subs * 20)
6. witchcraft_folklore_and_bog_magic (100: 5 subs * 20)
7. plague_lazarettos_and_quarantine (90: 5 subs * 18)
"""

from __future__ import annotations

from collections.abc import Callable


def generate_sphere3(make_asset: Callable) -> list[dict]:
    items: list[dict] = []

    # =========================================================================
    # 1. gothic_cathedrals_and_monumental_abbeys (140 assets: 2*24 + 4*23)
    # =========================================================================
    cid = "gothic_cathedrals_and_monumental_abbeys"
    var6_gothic = [
        (
            "caen_limestone",
            "Caen Limestone",
            "Đá Vôi Caen Sáng",
            "french_capetian",
            "creamy pale fine-grained French ashlar",
        ),
        (
            "weathered_gargoyle",
            "Gargoyle-Rainwashed",
            "Xói Mòn Mưa Nước",
            "french_capetian",
            "dark runnels from rainwater spouts",
        ),
        (
            "gilded_liturgical",
            "Gold-Leaf Traced",
            "Dát Vàng Phụng Vụ",
            "french_capetian",
            "gleaming church gold-leaf highlights",
        ),
        (
            "candle_soot",
            "Incense-Darkened",
            "Ám Khói Hương Trầm",
            "french_capetian",
            "deep grey incense and wax patina",
        ),
        (
            "mossy_buttress",
            "Lichen-Encrusted",
            "Phủ Địa Y Rêu",
            "french_capetian",
            "centuries of lichen on exterior piers",
        ),
        (
            "polychrome_painted",
            "Polychrome Painted",
            "Sơn Màu Thánh Tượng",
            "french_capetian",
            "rich medieval tempera pigment traces",
        ),
    ]

    subs_cathedral = [
        # Sub 1: 4 archetypes * 6 variants = 24
        (
            "flying_buttress_and_pinacle",
            [
                (
                    "arch_flying_buttress_pier",
                    "Double-Tiered Flying Buttress Arch",
                    "Vòm Bay Đỡ Tường Đôi (Flying Buttress)",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "crocketed_gothic_pinnacle",
                    "Crocketed Gothic Stone Pinnacle",
                    "Tháp Chóp Nhọn Đá Chạm Họa Tiết Lá",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "grotesque_gargoyle_drain_spout",
                    "Carved Beast Gargoyle Waterspout",
                    "Máng Thoát Nước Đá Hình Quái Thú Gargoyle",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "inspect",
                    "prop",
                    "stone",
                ),
                (
                    "pierced_quatrefoil_parapet",
                    "Quatrefoil Pierced Gallery Balustrade",
                    "Lan Can Đá Chạm Trổ Bốn Cánh Hoa",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    None,
                    "structure",
                    "stone",
                ),
            ],
            24,
        ),
        # Sub 2: 4 archetypes * 6 variants = 24
        (
            "rose_window_and_lancet_glass",
            [
                (
                    "great_rose_stained_glass_window",
                    "Radiant Rose Stained Glass Window",
                    "Cửa Sổ Hoa Hồng Kính Màu Lộng Lẫy",
                    [2, 2],
                    "cover",
                    True,
                    "transparent",
                    "admire",
                    "prop",
                    "glass",
                ),
                (
                    "pointed_lancet_stained_arch",
                    "Tall Pointed Lancet Saint Glass Window",
                    "Cửa Sổ Vòm Nhọn Kính Màu Hình Thánh",
                    [1, 2],
                    "cover",
                    True,
                    "transparent",
                    "pray",
                    "prop",
                    "glass",
                ),
                (
                    "geometric_stone_tracery_mullion",
                    "Bar Tracery Geometric Mullion Screen",
                    "Khung Hoa Sắt Đá Cửa Sổ Tracery",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "iron_glazing_bar_armature",
                    "Saddle-Bar Iron Window Armature",
                    "Khung Sắt Gia Cố Kính Màu Nhà Thờ",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    None,
                    "prop",
                    "iron",
                ),
            ],
            24,
        ),
        # Sub 3: 4 archetypes * 5 + 3 hero = 23
        (
            "high_altar_and_reredos_screen",
            [
                (
                    "marble_high_altar_mensa",
                    "Consecrated White Marble Altar Table",
                    "Bàn Thờ Lễ Đá Cẩm Thạch Trắng",
                    [2, 1],
                    "solid",
                    True,
                    "low",
                    "commune",
                    "prop",
                    "stone",
                ),
                (
                    "gilded_carved_triptych_reredos",
                    "Gilded Wooden Passion Triptych Reredos",
                    "Bức Bình Phong Ba Tấm Gỗ Dát Vàng Khắc Tích",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "venerate",
                    "prop",
                    "wood",
                ),
                (
                    "golden_altar_tabernacle_shrine",
                    "Enamelled Gold Eucharist Tabernacle",
                    "Hòm Thánh Tích Bằng Vàng Khảm Men",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "open",
                    "prop",
                    "iron",
                ),
                (
                    "standing_seven_branched_candelabrum",
                    "Cast Bronze Seven-Branched Menorah Lamp",
                    "Đèn Nến Đồng Bảy Nhánh Đại Thánh Đường",
                    [1, 2],
                    "cover",
                    False,
                    "low",
                    "light_candles",
                    "prop",
                    "iron",
                ),
            ],
            23,
        ),
        # Sub 4: 23
        (
            "carved_choir_stalls_and_misericord",
            [
                (
                    "canopied_oak_choir_stall_tier",
                    "Two-Tiered Canopied Oak Choir Stalls",
                    "Hàng Ghế Gỗ Sồi Có Mái Dành Cho Ca Đoàn",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "sit",
                    "structure",
                    "wood",
                ),
                (
                    "satirical_carved_misericord_seat",
                    "Tipped Misericord Carved Wooden Ledge",
                    "Bệ Ghế Gỗ Chạm Khắc Châm Biếm Misericord",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "inspect_carving",
                    "prop",
                    "wood",
                ),
                (
                    "great_brass_eagle_lectern",
                    "Massive Cast Brass Eagle Gospel Lectern",
                    "Bục Giảng Hình Đại Bàng Bằng Đồng Đúc",
                    [1, 2],
                    "solid",
                    True,
                    "low",
                    "read_scripture",
                    "prop",
                    "iron",
                ),
                (
                    "illuminated_choir_antiphoner_book",
                    "Giant Vellum Choral Antiphoner Hymnal",
                    "Cuốn Sách Thánh Ca Da Cừu Khổng Lồ",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "turn_page",
                    "prop",
                    "organic",
                ),
            ],
            23,
        ),
        # Sub 5: 23
        (
            "cathedral_bell_chamber_and_carillon",
            [
                (
                    "great_bourdon_bronze_bell",
                    "Ten-Ton Bronze Bourdon Cathedral Bell",
                    "Đại Hồng Chung Đồng Mười Tấn Bourdon",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "ring_bourdon",
                    "structure",
                    "iron",
                ),
                (
                    "timber_bell_hanging_cage_belfry",
                    "Massive Oak Timber Bellframe Yoke",
                    "Khung Gỗ Sồi Khổng Lồ Treo Đại Hồng Chung",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "wood",
                ),
                (
                    "carillon_chiming_iron_action",
                    "Chiming Wire Carillon Lever Rig",
                    "Hệ Thống Dây Sắt Kéo Chuông Gõ Nhịp",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "play_carillon",
                    "prop",
                    "iron",
                ),
                (
                    "bellringer_coiled_hemp_sallies",
                    "Wool-Padded Hemp Bell Ropes & Sally",
                    "Dây Thừng Kéo Chuông Bọc Len Êm Tay",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "pull_rope",
                    "prop",
                    "organic",
                ),
            ],
            23,
        ),
        # Sub 6: 23
        (
            "processional_crosses_and_reliquaries",
            [
                (
                    "jeweled_processional_cross_crucifix",
                    "Gold Jeweled Crux Gemmata Cross",
                    "Thánh Giá Rước Lễ Nạm Ngọc Vàng",
                    [1, 2],
                    "cover",
                    False,
                    "low",
                    "lift",
                    "prop",
                    "iron",
                ),
                (
                    "silver_arm_reliquary_of_saint",
                    "Repoussé Silver Arm Reliquary Casket",
                    "Hòm Thánh Cốt Hình Cánh Tay Bằng Bạc",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "revere_relic",
                    "prop",
                    "iron",
                ),
                (
                    "thurible_censer_and_incense_boat",
                    "Gothic Silver Swinging Incense Thurible",
                    "Bình Xông Trầm Bạc Lắc Dây Xích Nhà Thờ",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "swing_censer",
                    "prop",
                    "iron",
                ),
                (
                    "holy_water_aspersorium_bucket",
                    "Cast Bronze Holy Water Bucket & Sprinkler",
                    "Thùng Đựng Nước Thánh Đồng & Chổi Vẩy",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "bless",
                    "prop",
                    "iron",
                ),
            ],
            23,
        ),
    ]

    for sub_id, archetypes, target_count in subs_cathedral:
        sub_items = []
        if target_count == 24:
            for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
                for v_slug, v_name, v_vn, cult, desc in var6_gothic:
                    slug = f"{a_slug}_{v_slug}"
                    name = f"{v_name} {a_name}"
                    vn = f"{a_vn} ({v_vn})"
                    prompt = (
                        f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                        f"High Gothic cathedral and monumental abbey style, gouache hand-painted, ink contours, isolated on white background."
                    )
                    sub_items.append(
                        make_asset(
                            cid,
                            slug,
                            name,
                            vn,
                            sub_id,
                            fp,
                            col,
                            blk,
                            vis,
                            vrb,
                            f"Cathedral architecture component ({a_name}).",
                            False,
                            mat,
                            cult,
                            prompt,
                            asset_type=atype,
                        )
                    )
        elif target_count == 23:
            # 4 archetypes * 5 variants = 20 + 3 hero variants = 23
            var5 = var6_gothic[:5]
            for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
                for v_slug, v_name, v_vn, cult, desc in var5:
                    slug = f"{a_slug}_{v_slug}"
                    name = f"{v_name} {a_name}"
                    vn = f"{a_vn} ({v_vn})"
                    prompt = (
                        f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                        f"Gothic monumental cathedral ecclesiastical feature, gouache hand-painted, ink contours, isolated on white background."
                    )
                    sub_items.append(
                        make_asset(
                            cid,
                            slug,
                            name,
                            vn,
                            sub_id,
                            fp,
                            col,
                            blk,
                            vis,
                            vrb,
                            f"Cathedral religious component ({a_name}).",
                            False,
                            mat,
                            cult,
                            prompt,
                            asset_type=atype,
                        )
                    )
            # 3 hero assets
            h1 = make_asset(
                cid,
                f"{sub_id}_miraculous_hallowed",
                f"Miraculous Hallowed {sub_id.replace('_', ' ').title()}",
                f"Thánh Tích Phép Màu {sub_id.replace('_', ' ').title()}",
                sub_id,
                [2, 2],
                "solid",
                True,
                "opaque",
                "venerate",
                "Miraculous hallowed cathedral treasure.",
                False,
                "stone",
                "french_capetian",
                f"Miraculous hallowed cathedral treasure of {sub_id}, holy divine aura, Gothic abbey, gouache anime style.",
            )
            h2 = make_asset(
                cid,
                f"{sub_id}_ancient_archbishop",
                f"Archbishop's Consecrated {sub_id.replace('_', ' ').title()}",
                f"Đức Tổng Giám Mục Tận Hiến {sub_id.replace('_', ' ').title()}",
                sub_id,
                [1, 2],
                "cover",
                False,
                "low",
                "inspect",
                "Archbishop's consecrated sacred ecclesiastical item.",
                False,
                "wood",
                "french_capetian",
                f"Archbishop's consecrated sacred item of {sub_id}, gold embroidery, Gothic cathedral, gouache style.",
            )
            h3 = make_asset(
                cid,
                f"{sub_id}_relic_sanctuary",
                f"Sanctuary Vault {sub_id.replace('_', ' ').title()}",
                f"Hầm Cất Thánh Điện {sub_id.replace('_', ' ').title()}",
                sub_id,
                [1, 1],
                "cover",
                False,
                "low",
                "commune",
                "Sanctuary relic from abbey vaults.",
                False,
                "iron",
                "french_capetian",
                f"Sacred relic vault piece of {sub_id}, gold and silver filigree, Gothic abbey, gouache style.",
            )
            sub_items.extend([h1, h2, h3])
        items.extend(sub_items)

    # =========================================================================
    # 2. monasteries_cloisters_and_scriptoria (120 assets: 5 subs * 24)
    # =========================================================================
    cid = "monasteries_cloisters_and_scriptoria"
    var6_monk = [
        (
            "cistercian_plain",
            "Cistercian Austere",
            "Khổ Hạnh Cistercian",
            "universal_feudal",
            "unornamented clean pale limestone and strict geometric purity",
        ),
        (
            "benedictine_aged",
            "Benedictine Aged",
            "Benedictine Cổ Kính",
            "universal_feudal",
            "aged brown oak timbers and wax polished surfaces",
        ),
        (
            "herb_scented",
            "Herbal-Scented",
            "Thơm Hương Dược Liệu",
            "universal_feudal",
            "drying sage and lavender sprigs strewn nearby",
        ),
        (
            "ink_stained",
            "Scribe-Inked",
            "Vết Mực Chép Kinh",
            "universal_feudal",
            "black oak-gall ink droplets and pumice powder traces",
        ),
        (
            "candlelit_quiet",
            "Vespers-Shadowed",
            "Tịch Mịch Giờ Kinh Chiều",
            "universal_feudal",
            "warm quiet candlelight and quiet shadows",
        ),
        (
            "rain_washed_garth",
            "Garth Rain-Cooled",
            "Mưa Mát Vườn Tu Viện",
            "universal_feudal",
            "fresh green moss on flagstones around the inner lawn",
        ),
    ]

    subs_monk = [
        (
            "cloister_quadrangle_arcaded_walk",
            [
                (
                    "pointed_cloister_arcade_bay",
                    "Monastic Cloister Vaulted Walk Bay",
                    "Dãy Hành Lang Vòm Cuốn Quanh Vườn Tu Viện",
                    [2, 2],
                    "walk_surface",
                    False,
                    "low",
                    "walk_contemplate",
                    "structure",
                    "stone",
                ),
                (
                    "central_garth_lawn_herb_bed",
                    "Cloister Garth Quadrangle Lawn Herb Bed",
                    "Thảm Cỏ Trồng Thảo Dược Giữa Vườn Tu Viện",
                    [2, 2],
                    "walk_surface",
                    False,
                    "transparent",
                    "inspect_herbs",
                    "flora",
                    "plant",
                ),
                (
                    "central_octagonal_lavatorium",
                    "Monastic Stone Water Basin Lavatorium",
                    "Bể Rửa Tay Bằng Đá Hình Bát Giác Của Tu Sĩ",
                    [2, 2],
                    "water",
                    False,
                    "low",
                    "wash_hands",
                    "structure",
                    "stone",
                ),
                (
                    "twin_column_monastic_capital",
                    "Carved Folio Twin Monastic Column",
                    "Cặp Cột Đá Nhỏ Chạm Lá Cây Cổ Điển",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "stone",
                ),
            ],
        ),
        (
            "monastic_scriptorium_desk",
            [
                (
                    "slanted_scribe_carrel_desk",
                    "Monk's Sloping Oak Writing Carrel",
                    "Bàn Nghiêng Chép Sách Gỗ Sồi Có Hộc Tủ",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "transcribe",
                    "prop",
                    "wood",
                ),
                (
                    "vellum_sheet_parchment_press",
                    "Wooden Screw Parchment Flattening Press",
                    "Máy Ép Phẳng Giấy Da Cừu Bằng Gỗ",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "press_parchment",
                    "prop",
                    "wood",
                ),
                (
                    "iron_gall_ink_and_quill_stand",
                    "Horn Inkwell & Goose Feather Quill Set",
                    "Nghiên Mực Sừng Bò & Bút Lông Ngỗng",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "take_ink",
                    "prop",
                    "organic",
                ),
                (
                    "gold_leaf_illumination_palette",
                    "Shell Dish of Minium & Lapis Lazuli",
                    "Vỏ Sò Đựng Bột Màu Vẽ Tranh Lapis Lazuli",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "illuminate",
                    "prop",
                    "stone",
                ),
            ],
        ),
        (
            "refectory_dining_and_pulpit",
            [
                (
                    "long_monastic_refectory_trestle",
                    "Refectory Long Trestle Dining Bench",
                    "Bàn Dài Ăn Cơm Tập Thể Của Tu Viện",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "eat_silent",
                    "prop",
                    "wood",
                ),
                (
                    "wall_mounted_readers_pulpit",
                    "Stone Intramural Reading Pulpit Stair",
                    "Bục Giảng Kinh Gắn Trên Tường Phòng Ăn",
                    [1, 2],
                    "walk_surface",
                    False,
                    "low",
                    "read_aloud",
                    "structure",
                    "stone",
                ),
                (
                    "monks_turned_wooden_bowl_set",
                    "Turned Alder Trencher & Wooden Spoon",
                    "Bát Gỗ Cây Tiêu Đẽo & Thìa Gỗ Tu Sĩ",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "loot",
                    "prop",
                    "wood",
                ),
                (
                    "earthenware_cider_serving_pitcher",
                    "Glazed Brown Stoneware Water Pitcher",
                    "Bình Gốm Men Nâu Đựng Nước Uống",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "drink",
                    "prop",
                    "stone",
                ),
            ],
        ),
        (
            "physic_garden_monastic_herbs",
            [
                (
                    "raised_plank_physic_herb_bed",
                    "Wattle-Edged Medicinal Physic Bed",
                    "Luống Trồng Cây Thuốc Quây Nan Gỗ",
                    [2, 1],
                    "walk_surface",
                    False,
                    "transparent",
                    "harvest_herb",
                    "flora",
                    "plant",
                ),
                (
                    "carved_stone_apothecary_mortar",
                    "Massive Granite Herb Pounding Mortar",
                    "Cối Đá Hoa Cương Giã Thuốc Lớn",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "grind_herbs",
                    "prop",
                    "stone",
                ),
                (
                    "drying_herb_bundle_timber_rack",
                    "Hanging Sage & Belladonna Drying Line",
                    "Dây Treo Phơi Cây Xô Thơm & Ngải Cứu",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "inspect",
                    "prop",
                    "organic",
                ),
                (
                    "monk_herbalist_distillation_retort",
                    "Earthenware Retort & Condenser Tube",
                    "Bình Gốm Chưng Cất Nước Hoa Hồng Dược Liệu",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "distill",
                    "prop",
                    "stone",
                ),
            ],
        ),
        (
            "monastic_cell_and_dormitory",
            [
                (
                    "monastic_oak_pallet_bed",
                    "Straw-Tick Monk's Narrow Pallet Bed",
                    "Giường Gỗ Hẹp Đệm Rơm Của Tu Sĩ",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "sleep",
                    "prop",
                    "wood",
                ),
                (
                    "wooden_kneeling_prie_dieu",
                    "Carved Oak Kneeling Prayer Desk",
                    "Bệ Quỳ Cầu Nguyện Bằng Gỗ Sồi Prie-Dieu",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "kneel_pray",
                    "prop",
                    "wood",
                ),
                (
                    "discipline_knotted_scourge_peg",
                    "Knotted Hemp Cord Discipline Whip",
                    "Dây Thừng Thắt Nút Sám Hối Treo Tường",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "examine",
                    "prop",
                    "organic",
                ),
                (
                    "dormitory_night_lantern_niche",
                    "Stone Pierced Night Candle Alcove",
                    "Hốc Tường Đá Thắp Nến Ban Đêm Ký Túc Xá",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "light",
                    "prop",
                    "stone",
                ),
            ],
        ),
    ]

    for sub_id, archetypes in subs_monk:
        for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
            for v_slug, v_name, v_vn, cult, desc in var6_monk:
                slug = f"{a_slug}_{v_slug}"
                name = f"{v_name} {a_name}"
                vn = f"{a_vn} ({v_vn})"
                prompt = (
                    f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                    f"Monastic abbey cloister and scriptorium style, gouache hand-painted, ink contours, isolated on white background."
                )
                items.append(
                    make_asset(
                        cid,
                        slug,
                        name,
                        vn,
                        sub_id,
                        fp,
                        col,
                        blk,
                        vis,
                        vrb,
                        f"Monastic cloister life element ({a_name}).",
                        False,
                        mat,
                        cult,
                        prompt,
                        asset_type=atype,
                    )
                )

    # =========================================================================
    # 3. parish_chapels_and_wayside_shrines (100 assets: 5 subs * 20)
    # =========================================================================
    cid = "parish_chapels_and_wayside_shrines"
    var4_chapel = [
        (
            "country_limestone",
            "Fieldstone Plain",
            "Đá Đồng Quê Mộc",
            "universal_feudal",
            "rustic unhewn rubble fieldstone and rough mortar",
        ),
        (
            "mossy_roof",
            "Moss-Roofed",
            "Mái Phủ Rêu Xanh",
            "universal_feudal",
            "thick green moss blanket on stone slates",
        ),
        (
            "pilgrim_honored",
            "Votive-Adorned",
            "Đầy Lễ Vật Hành Hương",
            "universal_feudal",
            "scattered copper coins, wax ex-votos, and prayer ribbons",
        ),
        (
            "autumn_strewn",
            "Autumn Leaf-Strewn",
            "Rụng Đầy Lá Vàng",
            "universal_feudal",
            "blanket of dry fallen beech and oak leaves",
        ),
    ]

    subs_chapel = [
        (
            "wayside_stone_cross_crucifix",
            [
                (
                    "octagonal_base_standing_cross",
                    "Wayside Octagonal Shaft Stone Cross",
                    "Thánh Giá Đá Ven Đường Bệ Tám Cạnh",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "pray",
                    "prop",
                    "stone",
                ),
                (
                    "weeping_cross_pilgrim_steps",
                    "Calvary Weeping Cross Step Platform",
                    "Bậc Đá Quỳ Cầu Nguyện Thánh Giá Calvary",
                    [2, 1],
                    "walk_surface",
                    False,
                    "low",
                    "kneel",
                    "structure",
                    "stone",
                ),
                (
                    "niche_head_lantern_cross",
                    "Cross-Head Lantern Niche for Wayfarers",
                    "Hốc Đặt Đèn Dầu Đỉnh Thánh Giá Chỉ Đường",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "light_lantern",
                    "prop",
                    "stone",
                ),
                (
                    "weathered_crossroads_fingerpost",
                    "Carved Stone Crossroads Guide Stele",
                    "Trụ Đá Chỉ Lối Ngã Ba Đường Khắc Chữ",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "read_sign",
                    "prop",
                    "stone",
                ),
                (
                    "pilgrim_coin_offering_hollow",
                    "Alms Hollow Carved in Cross Plinth",
                    "Lỗ Khét Đựng Tiền Bố Thí Trên Chân Thánh Giá",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "give_alms",
                    "prop",
                    "stone",
                ),
            ],
        ),
        (
            "thatched_field_chapel_building",
            [
                (
                    "nave_and_chancel_field_chapel",
                    "Single-Room Stone & Thatch Field Chapel",
                    "Nhà Nguyện Nhỏ Lợp Tranh Giữa Cánh Đồng",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "enter",
                    "structure",
                    "stone",
                ),
                (
                    "timber_bell_cote_gable",
                    "Gable-Mounted Timber Bell-Cote",
                    "Mái Chuông Nhỏ Bằng Gỗ Gắn Đầu Hồi Nhà Nguyện",
                    [1, 1],
                    "solid",
                    True,
                    "opaque",
                    "ring",
                    "structure",
                    "wood",
                ),
                (
                    "peasant_hemp_door_curtain",
                    "Heavy Wool Parish Entry Draft Curtain",
                    "Rèm Vải Dạ Dày Chắn Gió Cửa Nhà Nguyện",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "part_curtain",
                    "prop",
                    "cloth",
                ),
                (
                    "stone_tithe_collection_urn",
                    "Carved Parish Tithe Grain Chest",
                    "Rương Gỗ Đựng Thóc Nộp Thuế Mười Phần Một",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "pay_tithe",
                    "prop",
                    "wood",
                ),
                (
                    "outdoor_communion_stone_bench",
                    "Low Stone Sentry Bench Under Eaves",
                    "Băng Ghế Đá Thấp Dưới Mái Hiên Nhà Nguyện",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "sit",
                    "prop",
                    "stone",
                ),
            ],
        ),
        (
            "pilgrims_sacred_spring_shrine",
            [
                (
                    "stonework_holy_well_basin",
                    "Arched Masonry Holy Well Enclosure",
                    "Miếu Vòm Đá Quây Giếng Nước Thánh Lành Tật",
                    [2, 2],
                    "water",
                    False,
                    "low",
                    "drink_holy_water",
                    "structure",
                    "stone",
                ),
                (
                    "votive_rag_cloutie_bush",
                    "Cloutie Thornbush Fluttering Rags",
                    "Bụi Cây Buộc Vải Điều Ước Của Khách Hành Hương",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "tie_rag",
                    "flora",
                    "plant",
                ),
                (
                    "pilgrim_lead_badge_vessel",
                    "Dish of Stamped Lead Pilgrim Badges",
                    "Khay Bán Huy Hiệu Chì Kỷ Niệm Hành Hương",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "buy_badge",
                    "prop",
                    "iron",
                ),
                (
                    "crutch_and_ex_voto_hanging_wall",
                    "Wall Hung with Crutches & Wax Limbs",
                    "Vách Treo Nạng Gỗ & Lễ Vật Tạ Ơn Bằng Sáp",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "admire_miracle",
                    "prop",
                    "organic",
                ),
                (
                    "carved_saint_healing_relief",
                    "Healing Saint Stone Relief Slab",
                    "Phiến Phù Điêu Đá Khắc Vị Thánh Ban Phép Lành",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "touch_relic",
                    "prop",
                    "stone",
                ),
            ],
        ),
        (
            "hollow_tree_saint_shrine",
            [
                (
                    "gnarled_oak_carved_statue_niche",
                    "Ancient Hollow Oak with Saint Statue",
                    "Cây Sồi Già Khoét Rỗng Đặt Tượng Thánh Nữ",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "pray",
                    "flora",
                    "plant",
                ),
                (
                    "standing_parish_stoup_stone",
                    "Stone Holy Water Stoup on Rubble Pier",
                    "Chậu Đá Đựng Nước Thánh Đặt Ven Lối Đi",
                    [1, 1],
                    "water",
                    False,
                    "low",
                    "cross_oneself",
                    "prop",
                    "stone",
                ),
                (
                    "wildflower_pilgrim_garland",
                    "Wreath of Woven Marigolds & Ivy",
                    "Vòng Hoa Cúc Vạn Thọ Dâng Kính Tượng Thánh",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "offer_flowers",
                    "prop",
                    "organic",
                ),
                (
                    "weathered_wood_carved_crucifix",
                    "Rustic Carved Pine Crucifix on Trunk",
                    "Thánh Giá Gỗ Thông Khắc Tay Gắn Thân Cây",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "venerate",
                    "prop",
                    "wood",
                ),
                (
                    "tallow_candle_stub_stump",
                    "Flat Tree Stump Melted Tallow Candles",
                    "Gốc Cây Đọng Sáp Nến Mỡ Động Vật Cháy Dở",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "light_candle",
                    "prop",
                    "wood",
                ),
            ],
        ),
        (
            "tithe_barn_parish_compound",
            [
                (
                    "massive_thatched_tithe_barn",
                    "Aisle-Timber Thatched Great Tithe Barn",
                    "Kho Thóc Mười Phần Một Khổng Lồ Khung Gỗ",
                    [3, 2],
                    "solid",
                    True,
                    "opaque",
                    "enter",
                    "structure",
                    "wood",
                ),
                (
                    "burlap_grain_tithe_stack",
                    "Pyramid of Tied Wheat & Rye Sacks",
                    "Chồng Bao Tải Thóc Lúa Mì & Lúa Mạch Nộp Thuế",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "inspect_tithe",
                    "prop",
                    "organic",
                ),
                (
                    "parish_priest_tithe_counter",
                    "Priest's Grain Measuring Bushel Tub",
                    "Thùng Gỗ Đong Thóc Của Cha Xứ (Bushel)",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "measure",
                    "prop",
                    "wood",
                ),
                (
                    "heavy_timber_threshing_floor_gate",
                    "Double-Leaf High Waggon Barn Doors",
                    "Cánh Cổng Kho Thóc Cho Xe Bò Đi Vào",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "open",
                    "structure",
                    "wood",
                ),
                (
                    "dovecote_parish_pigeon_tower",
                    "Circular Fieldstone Tithe Pigeon Tower",
                    "Tháp Nuôi Bồ Câu Bằng Đá Thuế Lãnh Chúa",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "gather_squabs",
                    "structure",
                    "stone",
                ),
            ],
        ),
    ]

    for sub_id, archetypes in subs_chapel:
        for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
            for v_slug, v_name, v_vn, cult, desc in var4_chapel:
                slug = f"{a_slug}_{v_slug}"
                name = f"{v_name} {a_name}"
                vn = f"{a_vn} ({v_vn})"
                prompt = (
                    f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                    f"Parish field chapel and wayside shrine style, gouache hand-painted, ink contours, isolated on white background."
                )
                items.append(
                    make_asset(
                        cid,
                        slug,
                        name,
                        vn,
                        sub_id,
                        fp,
                        col,
                        blk,
                        vis,
                        vrb,
                        f"Wayside chapel and shrine element ({a_name}).",
                        False,
                        mat,
                        cult,
                        prompt,
                        asset_type=atype,
                    )
                )

    # =========================================================================
    # 4. graveyards_crypts_and_charnel_houses (110 assets: 5 subs * 22)
    # =========================================================================
    cid = "graveyards_crypts_and_charnel_houses"
    var_grave = [
        (
            "ancient_mossy",
            "Mossy Weathered",
            "Rêu Phong Cổ",
            "universal_feudal",
            "centuries of damp green velvet moss and eroded stone",
        ),
        (
            "chilled_damp",
            "Subterranean Damp",
            "Ẩm Ướt Lòng Đất",
            "universal_feudal",
            "glistening damp subterranean moisture beads",
        ),
        (
            "ivy_choked",
            "Ivy-Strangled",
            "Dây Leo Xiết Chặt",
            "universal_feudal",
            "tangled dark ivy vines obscuring Latin inscriptions",
        ),
        (
            "charnel_dusted",
            "Bone-Dusted",
            "Bụi Xương Trắng",
            "universal_feudal",
            "dry pale calcium bone dust and cobwebs",
        ),
        (
            "weeping_yew",
            "Yew-Shaded",
            "Bóng Cây Thủy Tùng",
            "universal_feudal",
            "somber red berries and dark evergreen yew needles",
        ),
    ]

    subs_grave = [
        (
            "gothic_sarcophagus_and_tomb",
            [
                (
                    "knightly_effigy_stone_sarcophagus",
                    "Gothic Knight Effigy Carved Tomb",
                    "Mộ Đá Khắc Tượng Hiệp Sĩ Nằm Mặc Giáp",
                    [2, 1],
                    "solid",
                    True,
                    "low",
                    "inspect_tomb",
                    "prop",
                    "stone",
                ),
                (
                    "lady_effigy_canopied_tomb",
                    "Noble Lady Weeping Canopy Monument",
                    "Lăng Mộ Quý Tộc Có Tượng Điêu Khắc Khóc Thương",
                    [2, 1],
                    "solid",
                    True,
                    "low",
                    "venerate",
                    "prop",
                    "stone",
                ),
                (
                    "brass_inlaid_memorial_slab",
                    "Floor Brass Inlay Knight Memorial Plate",
                    "Tấm Đồng Khảm Sàn Khắc Chân Dung Hiệp Sĩ",
                    [2, 1],
                    "walk_surface",
                    False,
                    "transparent",
                    "read_epitaph",
                    "prop",
                    "iron",
                ),
                (
                    "cadaver_transi_tomb_shroud",
                    "Transi Cadaver Shrouded Corpse Tomb",
                    "Mộ Đá Transi Khắc Hình Xác Ướp Quấn Vải",
                    [2, 1],
                    "solid",
                    True,
                    "low",
                    "ponder_mortality",
                    "prop",
                    "stone",
                ),
            ],
        ),
        (
            "charnel_house_ossuary_skull_wall",
            [
                (
                    "geometric_skull_and_femur_wall",
                    "Stacked Human Skulls & Femurs Wall",
                    "Bức Tường Xương Người & Hộp Sọ Xếp Khéo",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "inspect_ossuary",
                    "structure",
                    "organic",
                ),
                (
                    "ossuary_arched_bone_niche",
                    "Arched Bone Reliquary Crypt Niche",
                    "Hốc Vòm Chứa Xương Người Trong Hầm Mộ",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "organic",
                ),
                (
                    "bone_pyramid_memento_mori",
                    "Pyramid of Arranged Human Bones",
                    "Tháp Xương Memento Mori Xếp Tầng",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "memento_mori",
                    "prop",
                    "organic",
                ),
                (
                    "charnel_chapel_altar_of_bones",
                    "Crypt Altar Constructed of Skulls",
                    "Bàn Thờ Hầm Mộ Xếp Bằng Hộp Sọ",
                    [2, 1],
                    "solid",
                    True,
                    "low",
                    "pray_for_souls",
                    "prop",
                    "organic",
                ),
            ],
        ),
        (
            "churchyard_standing_slate_headstones",
            [
                (
                    "weathered_slate_peasant_headstone",
                    "Pointed Slate Headstone with Skull Motif",
                    "Bia Mộ Đá Phiến Khắc Họa Tiết Đầu Lâu",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "read_grave",
                    "prop",
                    "stone",
                ),
                (
                    "celtic_cross_churchyard_marker",
                    "Low Churchyard Celtic Cross Marker",
                    "Cọc Bia Mộ Đá Chữ Thập Celtic Nhỏ",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "inspect",
                    "prop",
                    "stone",
                ),
                (
                    "mounded_turf_grave_with_cross",
                    "Freshly Mounded Earth Peasant Grave",
                    "Mộ Mới Đắp Đất Có Cắm Thánh Giá Gỗ",
                    [2, 1],
                    "walk_surface",
                    False,
                    "low",
                    "pray",
                    "structure",
                    "earth",
                ),
                (
                    "iron_corpse_cage_mortsafe",
                    "Wrought Iron Grave-Robber Mortsafe Cage",
                    "Lồng Sắt Chống Trộm Xác Mortsafe Khóa Mộ",
                    [2, 1],
                    "solid",
                    True,
                    "low",
                    "inspect_cage",
                    "prop",
                    "iron",
                ),
            ],
        ),
        (
            "ancient_churchyard_yew_tree",
            [
                (
                    "massive_hollow_churchyard_yew",
                    "Giant Gnarled Cemetery Yew Trunk",
                    "Gốc Cây Thủy Tùng Cổ Thụ Nghĩa Địa Nghìn Năm",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "shelter_under",
                    "flora",
                    "plant",
                ),
                (
                    "spreading_poisonous_yew_bough",
                    "Low Spreading Evergreen Yew Canopy",
                    "Cành Cây Thủy Tùng Xòe Thấp Đầy Quả Độc",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "flora",
                    "plant",
                ),
                (
                    "yew_shaded_stone_lichgate_bench",
                    "Timber Lychgate Corpse Shelter Roof",
                    "Cổng Nghĩa Địa Lychgate Có Mái Che Đặt Quan Tài",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "pass_gate",
                    "structure",
                    "wood",
                ),
                (
                    "grave_diggers_mattock_and_mound",
                    "Sexton's Shovel & Fresh Mound of Soil",
                    "Xẻng Của Người Đào Huyệt & Đống Đất Vừa Đào",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "loot_shovel",
                    "prop",
                    "iron",
                ),
            ],
        ),
        (
            "subterranean_catacomb_niches",
            [
                (
                    "loculus_coffin_wall_shelf",
                    "Tiered Catacomb Loculus Coffin Niche",
                    "Hàng Ngăn Đặt Quan Tài Khoét Vách Đá",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "search_loculus",
                    "structure",
                    "stone",
                ),
                (
                    "sealed_marble_burial_plaque",
                    "Inscribed Latin Epitaph Marble Tile",
                    "Tấm Đá Cẩm Thạch Bịt Kín Miệng Mộ Khắc Chữ",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "read_name",
                    "prop",
                    "stone",
                ),
                (
                    "subterranean_oil_lamp_bracket",
                    "Wrought Iron Wall Crypt Lamp Bracket",
                    "Giá Sắt Gắn Tường Đỡ Đèn Dầu Hầm Mộ",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "light_oil",
                    "prop",
                    "iron",
                ),
                (
                    "heavy_oak_iron_catacomb_grille",
                    "Padlocked Iron Crypt Gate Grille",
                    "Cửa Sắt Khóa Xích Ngăn Lối Xuống Hầm Mộ Sâu",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "unlock_gate",
                    "structure",
                    "iron",
                ),
            ],
        ),
    ]

    for sub_id, archetypes in subs_grave:
        for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
            for v_slug, v_name, v_vn, cult, desc in var_grave:
                slug = f"{a_slug}_{v_slug}"
                name = f"{v_name} {a_name}"
                vn = f"{a_vn} ({v_vn})"
                prompt = (
                    f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                    f"Medieval graveyard churchyard crypt and ossuary style, gouache hand-painted, ink contours, isolated on white background."
                )
                items.append(
                    make_asset(
                        cid,
                        slug,
                        name,
                        vn,
                        sub_id,
                        fp,
                        col,
                        blk,
                        vis,
                        vrb,
                        f"Graveyard and crypt mortality element ({a_name}).",
                        False,
                        mat,
                        cult,
                        prompt,
                        asset_type=atype,
                    )
                )
        h1 = make_asset(
            cid,
            f"{sub_id}_ancestral_crypt_relic",
            f"Ancestral Hallowed {sub_id.replace('_', ' ').title()}",
            f"Di Vật Tổ Tiên {sub_id.replace('_', ' ').title()}",
            sub_id,
            [2, 2],
            "solid",
            True,
            "opaque",
            "commune",
            "Ancestral relic from centuries past.",
            False,
            "stone",
            "universal_feudal",
            f"Ancient ancestral relic of {sub_id}, mossy stone and mortality symbols, Gothic style.",
        )
        h2 = make_asset(
            cid,
            f"{sub_id}_undisturbed_crypt",
            f"Undisturbed Sealed {sub_id.replace('_', ' ').title()}",
            f"Niêm Phong Bất Khả Xâm Phạm {sub_id.replace('_', ' ').title()}",
            sub_id,
            [1, 1],
            "cover",
            False,
            "low",
            "inspect",
            "Undisturbed sealed crypt relic.",
            False,
            "organic",
            "universal_feudal",
            f"Undisturbed sealed crypt artifact of {sub_id}, ancient cobwebs and heavy seals, Gothic style.",
        )
        items.extend([h1, h2])

    # =========================================================================
    # 5. medieval_alchemy_and_natural_philosophy (100 assets: 5 subs * 20)
    # =========================================================================
    cid = "medieval_alchemy_and_natural_philosophy"
    var4_alch = [
        (
            "soot_stained_glass",
            "Fire-Stained",
            "Ám Khói Lò Nung",
            "universal_feudal",
            "flame-blackened glass and charcoal smudge",
        ),
        (
            "mercury_sheen",
            "Quicksilver-Gleaming",
            "Ánh Thủy Ngân",
            "universal_feudal",
            "metallic silvery sheen and alembic residue",
        ),
        (
            "parchment_cluttered",
            "Scroll-Cluttered",
            "Bừa Bãi Bản Thảo",
            "universal_feudal",
            "strewn with cryptic planetary charts and vellum notes",
        ),
        (
            "sulfur_encrusted",
            "Brimstone-Encrusted",
            "Đọng Vàng Lưu Huỳnh",
            "universal_feudal",
            "yellow crystalline sulfur crust and vitriol stains",
        ),
    ]

    subs_alch = [
        (
            "athanor_tower_furnace_and_alembic",
            [
                (
                    "brick_athanor_philosophical_furnace",
                    "Masonry Tower Athanor Slow Furnace",
                    "Lò Nung Chậm Tháp Gạch Athanor",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "tend_athanor",
                    "structure",
                    "stone",
                ),
                (
                    "glass_alembic_distillation_train",
                    "Glass Cucurbit & Alembic Still Head",
                    "Bình Chưng Cất Thủy Tinh Cổ Ngỗng Alembic",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "distill_elixir",
                    "prop",
                    "glass",
                ),
                (
                    "sand_bath_heating_balneum",
                    "Sand Bath Balneum Heat Regulator Pan",
                    "Chảo Cát Điều Nhiệt Nung Hóa Chất",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "heat_mixture",
                    "prop",
                    "iron",
                ),
                (
                    "twin_bellows_draft_pipe_rig",
                    "Leather Foot Bellows Draft Blast Pipe",
                    "Ống Bơm Gió Đạp Chân Thổi Lửa Lò",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "pump_air",
                    "prop",
                    "organic",
                ),
                (
                    "vitriol_clay_storage_carboy",
                    "Wicker-Cased Clay Vitriol Acid Jar",
                    "Bình Gốm Bọc Nan Tre Đựng Axit Vitriol",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "loot_acid",
                    "prop",
                    "stone",
                ),
            ],
        ),
        (
            "astrolabe_armillary_sphere_and_charts",
            [
                (
                    "brass_planispheric_astrolabe_stand",
                    "Engraved Brass Planispheric Astrolabe",
                    "Thước Trắc Tinh Bằng Đồng Khắc Kinh Độ",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "calculate_stars",
                    "prop",
                    "iron",
                ),
                (
                    "revolving_armillary_sphere_globe",
                    "Gilded Astronomical Armillary Sphere",
                    "Mô Hình Thiên Cầu Vòng Kim Loại Xoay",
                    [1, 2],
                    "solid",
                    True,
                    "low",
                    "track_planets",
                    "prop",
                    "iron",
                ),
                (
                    "zodiacal_parchment_horoscope_board",
                    "Celestial Zodiac Chart on Oak Table",
                    "Bản Đồ Mười Hai Cung Hoàng Đạo Trên Bàn",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "cast_horoscope",
                    "prop",
                    "wood",
                ),
                (
                    "lead_plumb_line_quadrant_post",
                    "Sighting Geometrical Shadow Quadrant",
                    "Thước Phần Tư Quả Dọi Đo Góc Sao",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "measure_altitude",
                    "prop",
                    "wood",
                ),
                (
                    "compass_dividers_and_ink_ruler",
                    "Brass Dividers & Ruled Astrological Chart",
                    "Com-pa Đồng & Bút Kẻ Thước Thiên Văn",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "chart_course",
                    "prop",
                    "iron",
                ),
            ],
        ),
        (
            "herbal_apothecary_drawers_and_jars",
            [
                (
                    "apothecary_hundred_drawer_cabinet",
                    "Walnut Apothecary Drug Drawer Chest",
                    "Tủ Thuốc Trăm Ngăn Bằng Gỗ Óc Chó",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "search_drawers",
                    "prop",
                    "wood",
                ),
                (
                    "delft_majolica_albarello_jar_row",
                    "Row of Majolica Drug Jars (Albarello)",
                    "Dãy Bình Gốm Majolica Đựng Dược Liệu",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "take_medicine",
                    "prop",
                    "stone",
                ),
                (
                    "dried_alligator_suspended_ceiling",
                    "Stuffed Crocodile Hanging Ceiling Trophy",
                    "Xác Cá Sấu Khô Treo Trần Nhà Thầy Giả Kim",
                    [2, 1],
                    "cover",
                    False,
                    "transparent",
                    "gaze_up",
                    "prop",
                    "organic",
                ),
                (
                    "horn_powder_mortar_and_pestle",
                    "Heavy Brass Apothecary Pestle & Mortar",
                    "Cối & Chày Đồng Đúc Nghiền Dược Thảo",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "grind_powder",
                    "prop",
                    "iron",
                ),
                (
                    "hanging_drying_poppy_heads_cluster",
                    "Cluster of Dried Opium Poppy Seed Heads",
                    "Chùm Quả Thuốc Phiện Khô Treo Dốc Ngược",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "harvest_opium",
                    "prop",
                    "organic",
                ),
            ],
        ),
        (
            "homunculus_jar_and_transmutation_crucible",
            [
                (
                    "amber_glass_homunculus_vial",
                    "Fluid-Filled Glass Jar with Specimen",
                    "Lọ Thủy Tinh Màu Hổ Phách Chứa Mẫu Vật",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "inspect_specimen",
                    "prop",
                    "glass",
                ),
                (
                    "graphite_melting_crucible_tongs",
                    "Refractory Clay Crucible with Molten Slag",
                    "Nồi Nung Đất Sét Chịu Nhiệt Kèm Kẹp Sắt",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "smelt_metal",
                    "prop",
                    "stone",
                ),
                (
                    "calcination_iron_tripod_dish",
                    "Iron Tripod Calcining Dish with Ashes",
                    "Đĩa Sắt Kiềng Ba Chân Nung Khô Tro Thuốc",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "calcine",
                    "prop",
                    "iron",
                ),
                (
                    "philosophers_stone_lead_ingots",
                    "Lead Ingot Marked with Gold Transmutation",
                    "Thỏi Chì Đánh Dấu Biến Đổi Thành Vàng",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "transmute",
                    "prop",
                    "iron",
                ),
                (
                    "sealed_wax_philosophical_egg",
                    "Hermetically Sealed Glass Egg (Vas Hermetis)",
                    "Trứng Thủy Tinh Hàn Kín Vas Hermetis",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "incubate",
                    "prop",
                    "glass",
                ),
            ],
        ),
        (
            "scholars_reading_pulpit_and_codices",
            [
                (
                    "octagonal_revolving_bookwheel_desk",
                    "Revolving Scholar's Multiple Bookwheel",
                    "Bánh Xe Gỗ Quay Đọc Nhiều Sách Cùng Lúc",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "rotate_wheel",
                    "prop",
                    "wood",
                ),
                (
                    "clasped_pigskin_alchemy_folio",
                    "Chained Pigskin Illuminated Grimoire",
                    "Sách Bìa Da Lợn Có Khóa Xích Chép Thuật Giả Kim",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "read_folio",
                    "prop",
                    "organic",
                ),
                (
                    "monks_spectacles_and_reading_glass",
                    "Rivet Spectacles & Beryl Magnifying Lens",
                    "Kính Đeo Mắt Gọng Đinh Tán & Thấu Kính Beryl",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "examine_text",
                    "prop",
                    "glass",
                ),
                (
                    "candle_bracket_reading_stand",
                    "Adjustable Brass Candle Arm Desk Stand",
                    "Giá Đỡ Nến Đồng Có Cần Chỉnh Chiều Cao",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "adjust_light",
                    "prop",
                    "iron",
                ),
                (
                    "cabinet_of_curiosities_fossil_shelf",
                    "Curiosity Shelf Petrified Wood & Ammonite",
                    "Kệ Gỗ Trưng Bày Hóa Thạch Cúc Đá & Kỳ Vật",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "study_fossils",
                    "prop",
                    "stone",
                ),
            ],
        ),
    ]

    for sub_id, archetypes in subs_alch:
        for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
            for v_slug, v_name, v_vn, cult, desc in var4_alch:
                slug = f"{a_slug}_{v_slug}"
                name = f"{v_name} {a_name}"
                vn = f"{a_vn} ({v_vn})"
                prompt = (
                    f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                    f"Medieval alchemy laboratory and natural philosophy style, gouache hand-painted, ink contours, isolated on white background."
                )
                items.append(
                    make_asset(
                        cid,
                        slug,
                        name,
                        vn,
                        sub_id,
                        fp,
                        col,
                        blk,
                        vis,
                        vrb,
                        f"Alchemy and natural philosophy element ({a_name}).",
                        False,
                        mat,
                        cult,
                        prompt,
                        asset_type=atype,
                    )
                )

    # =========================================================================
    # 6. witchcraft_folklore_and_bog_magic (100 assets: 5 subs * 20)
    # =========================================================================
    cid = "witchcraft_folklore_and_bog_magic"
    var4_witch = [
        (
            "peat_stilted",
            "Bog-Waterlogged",
            "Ngập Nước Đầm Lầy",
            "celtic_gaelic",
            "dark rotting swamp timber and dripping mire",
        ),
        (
            "poppet_pinned",
            "Twig-Bound",
            "Buộc Cành Cây Dại",
            "celtic_gaelic",
            "woven willow withes and iron nail bindings",
        ),
        (
            "smoke_blackened",
            "Hex-Smoked",
            "Ám Khói Bùa Ngải",
            "celtic_gaelic",
            "pungent incense smoke of henbane and wormwood",
        ),
        (
            "fetish_hung",
            "Feather-Crowned",
            "Gắn Lông Quạ Đen",
            "celtic_gaelic",
            "black raven feathers and animal skull charms",
        ),
    ]

    subs_witch = [
        (
            "bog_stilt_thatched_witch_hut",
            [
                (
                    "crooked_stilted_mire_hovel",
                    "Crooked Willow-Stilted Thatched Witch Hut",
                    "Túp Lều Tranh Chân Cọc Cong Veo Giữa Đầm",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "enter",
                    "structure",
                    "wood",
                ),
                (
                    "thatched_eaves_hanging_skulls",
                    "Eaves Strung with Small Animal Skulls",
                    "Mái Tranh Treo Lủng Lẳng Đầu Lâu Thú Nhỏ",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "inspect",
                    "prop",
                    "organic",
                ),
                (
                    "decaying_peat_driftwood_dock",
                    "Rotting Peat Plank Skiff Mooring",
                    "Cầu Gỗ Mục Buộc Thuyền Ven Bãi Than Bùn",
                    [2, 1],
                    "walk_surface",
                    False,
                    "low",
                    "board",
                    "structure",
                    "wood",
                ),
                (
                    "bog_mire_stewing_black_cauldron",
                    "Tripod Iron Cauldron over Swampfire",
                    "Vạc Sắt Đen Nấu Nước Thuốc Trên Lửa Đầm",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "stir_brew",
                    "prop",
                    "iron",
                ),
                (
                    "crooked_mud_brick_chimney_flue",
                    "Twisted Clay Flue Belching Green Smoke",
                    "Ống Khói Đất Cong Nhả Làn Khói Xanh",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    None,
                    "prop",
                    "earth",
                ),
            ],
        ),
        (
            "straw_corn_dolly_and_hex_poppets",
            [
                (
                    "corn_dolly_harvest_queen_figure",
                    "Woven Wheat Straw Harvest Queen Dolly",
                    "Búp Bê Rơm Bện Mẹ Lúa Thu Hoạch",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "take_dolly",
                    "prop",
                    "organic",
                ),
                (
                    "wax_poppet_stuck_with_iron_pins",
                    "Beeswax Voodoo Poppet with Forged Nails",
                    "Búp Bê Sáp Ong Cắm Đinh Sắt Nguyền Rủa",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "pull_nail",
                    "prop",
                    "organic",
                ),
                (
                    "red_thread_tied_herb_bundle",
                    "Rowan Sprig Tied with Crimson Thread",
                    "Nhánh Cây Thanh Lương Trà Buộc Chỉ Đỏ",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "ward_evil",
                    "prop",
                    "organic",
                ),
                (
                    "crossroads_buried_witch_bottle",
                    "Stoneware Bellarmine Witch Bottle",
                    "Bình Gốm Phù Thủy Bellarmine Chôn Giấu",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "dig_up",
                    "prop",
                    "stone",
                ),
                (
                    "woven_willow_hag_stone_talisman",
                    "Perforated Adder Stone Hanging Charm",
                    "Viên Đá Thủng Lỗ Tự Nhiên Treo Trừ Tà",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "peer_through",
                    "prop",
                    "stone",
                ),
            ],
        ),
        (
            "poisonous_nightshade_and_fungi_ring",
            [
                (
                    "flowering_deadly_nightshade_bush",
                    "Purple-Flowered Belladonna Shrub",
                    "Bụi Cây Cà Độc Dược Belladonna Hoa Tím",
                    [1, 1],
                    "cover",
                    True,
                    "low",
                    "harvest_poison",
                    "flora",
                    "plant",
                ),
                (
                    "red_fly_agaric_fairy_ring_circle",
                    "Amanita Muscaria Toadstool Fairy Ring",
                    "Vòng Tròn Nấm Đỏ Chấm Trắng Cổ Tích",
                    [2, 2],
                    "walk_surface",
                    False,
                    "transparent",
                    "step_inside",
                    "flora",
                    "plant",
                ),
                (
                    "hemlock_and_henbane_clump",
                    "Tall Rank Water Hemlock Wild Patch",
                    "Bụi Cây Cần Độc Mọc Hoang Ven Bãi Nước",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "harvest_hemlock",
                    "flora",
                    "plant",
                ),
                (
                    "carved_mandrake_root_specimen",
                    "Bifurcated Mandrake Root in Jar",
                    "Củ Cây Nhân Thảo Mandrake Hình Người",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "inspect_mandrake",
                    "prop",
                    "organic",
                ),
                (
                    "rotting_log_glowing_foxfire",
                    "Bioluminescent Foxfire Decaying Log",
                    "Khúc Gỗ Mục Phát Sáng Lân Tinh Trong Đêm",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "gather_fungus",
                    "flora",
                    "wood",
                ),
            ],
        ),
        (
            "wyrd_standing_boulder_and_offerings",
            [
                (
                    "lichen_split_hag_stone_monolith",
                    "Mossy Split Hag Stone Megalith",
                    "Khối Cự Thạch Nứt Đôi Phủ Rêu Của Phù Thủy",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "commune",
                    "prop",
                    "stone",
                ),
                (
                    "bowl_of_stagnant_black_water",
                    "Rock Hollow Black Scrying Pool",
                    "Vũng Nước Đen Soi Tương Lai Khoét Trên Đá",
                    [1, 1],
                    "water",
                    False,
                    "low",
                    "scry",
                    "prop",
                    "stone",
                ),
                (
                    "braided_horsehair_fetish_totem",
                    "Pole Hung with Entwined Horsehair & Bones",
                    "Cọc Gỗ Treo Bờm Ngựa Bện Kèm Xương Động Vật",
                    [1, 2],
                    "cover",
                    False,
                    "low",
                    "inspect_totem",
                    "prop",
                    "organic",
                ),
                (
                    "offering_heap_milk_and_honey",
                    "Flat Stone Offering Bowl with Curdled Milk",
                    "Đĩa Đá Đựng Sữa & Mật Ong Cúng Tế Ma Rừng",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "leave_offering",
                    "prop",
                    "stone",
                ),
                (
                    "carved_spirals_megalith_base",
                    "Ancient Neolithic Spiral Carved Slab",
                    "Phiến Đá Khắc Hoa Văn Xoắn Ốc Thời Tiền Sử",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "trace_spiral",
                    "prop",
                    "stone",
                ),
            ],
        ),
        (
            "divination_table_and_bone_casting",
            [
                (
                    "carved_alder_scrying_table",
                    "Three-Legged Alder Witchcraft Table",
                    "Bàn Gỗ Ba Chân Bói Toán Của Mụ Phù Thủy",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "cast_bones",
                    "prop",
                    "wood",
                ),
                (
                    "scattered_knucklebones_and_runes",
                    "Cast Sheep Astragalus Divination Bones",
                    "Xương Cổ Chân Cừu Rơi Vãi Bói Điềm Hung Cát",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "read_omens",
                    "prop",
                    "organic",
                ),
                (
                    "black_obsidian_scrying_mirror",
                    "Polished Black Mirror in Carved Frame",
                    "Gương Đá Núi Lửa Đen Soi Linh Hồn Khung Gỗ",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "gaze_mirror",
                    "prop",
                    "stone",
                ),
                (
                    "raven_feather_smudge_wand",
                    "Smudge Wand of Mugwort & Crow Quills",
                    "Bó Cây Ngải Đốt Xông Khói Kèm Lông Quạ",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "cleanse_space",
                    "prop",
                    "organic",
                ),
                (
                    "spindle_and_black_wool_thread",
                    "Drop Spindle with Hand-Spun Black Fleece",
                    "Con Thoi Kéo Sợi Len Cừu Đen Nguyền Rủa",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "spin_fate",
                    "prop",
                    "wood",
                ),
            ],
        ),
    ]

    for sub_id, archetypes in subs_witch:
        for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
            for v_slug, v_name, v_vn, cult, desc in var4_witch:
                slug = f"{a_slug}_{v_slug}"
                name = f"{v_name} {a_name}"
                vn = f"{a_vn} ({v_vn})"
                prompt = (
                    f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                    f"Medieval folklore witchcraft and bog magic style, gouache hand-painted, ink contours, isolated on white background."
                )
                items.append(
                    make_asset(
                        cid,
                        slug,
                        name,
                        vn,
                        sub_id,
                        fp,
                        col,
                        blk,
                        vis,
                        vrb,
                        f"Witchcraft folklore element ({a_name}).",
                        False,
                        mat,
                        cult,
                        prompt,
                        asset_type=atype,
                    )
                )

    # =========================================================================
    # 7. plague_lazarettos_and_quarantine (90 assets: 5 subs * 18)
    # =========================================================================
    cid = "plague_lazarettos_and_quarantine"
    var3_plague = [
        (
            "lime_washed_quarantine",
            "Quicklime-Dusted",
            "Rắc Vôi Sống Sát Khuẩn",
            "universal_feudal",
            "white caustic quicklime powder dusting and quarantine marks",
        ),
        (
            "smoke_fumigated",
            "Fumigation-Smoked",
            "Xông Khói Trừ Tà Khí",
            "universal_feudal",
            "pungent aromatic sulfur and juniper smoke clouds",
        ),
        (
            "bleak_pestilence",
            "Pestilence-Stained",
            "Ám Dịch Bệnh Đen",
            "universal_feudal",
            "grim dark quarantine stains and ominous red crosses",
        ),
    ]
    # 6 archetypes * 3 variants = 18 per subcat -> 5 * 18 = 90
    subs_plague = [
        (
            "lazaretto_pest_house_ward",
            [
                (
                    "isolated_timber_pest_ward",
                    "Boarded Timber Quarantine Pesthouse",
                    "Nhà Cách Ly Dịch Bệnh Gỗ Bịt Kín Cửa",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "enter",
                    "structure",
                    "wood",
                ),
                (
                    "straw_pallet_quarantine_bed",
                    "Soiled Straw Bed with Vinegar Linen",
                    "Giường Đệm Rơm Khách Bệnh Lau Nước Giấm",
                    [1, 2],
                    "solid",
                    True,
                    "low",
                    "rest",
                    "prop",
                    "organic",
                ),
                (
                    "exterior_food_delivery_pulley",
                    "Rope Basket High Wall Food Delivery",
                    "Rổ Kéo Dây Thừng Chuyển Đồ Ăn Qua Tường",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "leave_rations",
                    "prop",
                    "wood",
                ),
                (
                    "steaming_herbal_fumigation_brazier",
                    "Iron Cauldron of Burning Sulfur & Pitch",
                    "Lò Sắt Đốt Lưu Huỳnh & Hắc Ín Xông Khói",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "fumigate",
                    "prop",
                    "iron",
                ),
                (
                    "lime_painted_red_quarantine_cross",
                    "Heavy Oak Door with Red Painted Cross",
                    "Cánh Cửa Gỗ Vẽ Dấu Chữ Thập Đỏ Cách Ly",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "inspect_warning",
                    "structure",
                    "wood",
                ),
                (
                    "pesthouse_corpse_chute_gate",
                    "Sloping Ground-Level Corpse Chute Hatch",
                    "Cửa Sập Đẩy Thi Hài Xuống Rãnh Chôn",
                    [1, 1],
                    "cover",
                    True,
                    "low",
                    "open_hatch",
                    "structure",
                    "wood",
                ),
            ],
        ),
        (
            "plague_doctor_attire_and_station",
            [
                (
                    "beaked_plague_mask_mannequin",
                    "Leather Beaked Doctor Mask on Stand",
                    "Mặt Nạ Mỏ Chim Bằng Da Thầy Thuốc Dịch Hạch",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "don_mask",
                    "prop",
                    "organic",
                ),
                (
                    "waxed_leather_protective_cloak",
                    "Floor-Length Waxed Linen Overcoat Stand",
                    "Áo Choàng Vải Bạt Tẩm Sáp Chống Truyền Nhiễm",
                    [1, 2],
                    "cover",
                    False,
                    "low",
                    "wear_cloak",
                    "prop",
                    "cloth",
                ),
                (
                    "aromatic_beak_herb_pot",
                    "Jar of Dried Cloves & Camphor for Beak",
                    "Hũ Đựng Đinh Hương & Long Não Nhét Mỏ Chim",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "refill_herbs",
                    "prop",
                    "stone",
                ),
                (
                    "wooden_touching_cane_pointer",
                    "Hazel Examination Wand with Brass Tip",
                    "Gậy Khám Bệnh Đầu Đồng Tránh Tiếp Xúc Tay",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "take_cane",
                    "prop",
                    "wood",
                ),
                (
                    "bloodletting_fleam_and_bronze_bowl",
                    "Spring Fleam Blade & Blood Catch Basin",
                    "Dao Trích Máu Cơ Giới & Chậu Đồng Hứng Máu",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "bleed_patient",
                    "prop",
                    "iron",
                ),
                (
                    "vinegar_sponge_breathing_cloth",
                    "Soaked Four Thieves Vinegar Sponge",
                    "Miếng Bọt Biển Tẩm Giấm Bốn Tên Cướp",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "sniff_vinegar",
                    "prop",
                    "organic",
                ),
            ],
        ),
        (
            "quarantine_barrier_and_watch_line",
            [
                (
                    "iron_spiked_cordon_sanitaire_barrier",
                    "Timber Cheval-de-Frise Quarantine Bar",
                    "Hàng Rào Cọc Gỗ Cordon Sanitaire Ngăn Làng",
                    [2, 1],
                    "solid",
                    True,
                    "low",
                    "inspect_cordon",
                    "structure",
                    "wood",
                ),
                (
                    "armed_watchman_sentry_sconce",
                    "Roadblock Guard Timber Shelter Shed",
                    "Chòi Gác Gỗ Có Lính Canh Chốt Chặn Dịch",
                    [2, 1],
                    "solid",
                    True,
                    "opaque",
                    "check_papers",
                    "structure",
                    "wood",
                ),
                (
                    "vinegar_coin_disinfection_trough",
                    "Stone Trough of Disinfecting Vinegar",
                    "Máng Đá Chứa Giấm Sát Trùng Tiền Xu Giao Dịch",
                    [1, 1],
                    "water",
                    False,
                    "low",
                    "drop_coin_vinegar",
                    "prop",
                    "stone",
                ),
                (
                    "iron_tongs_for_passing_bread",
                    "Long Iron Bakers' Quarantine Tongs",
                    "Kẹp Sắt Dài Chuyền Bánh Mì Tránh Tiếp Xúc",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "hand_food",
                    "prop",
                    "iron",
                ),
                (
                    "toll_road_quarantine_signpost",
                    "Pitched Sign Prohibiting Entry to Town",
                    "Bảng Gỗ Cắm Đường Cấm Người Lạ Vào Thành",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "read_quarantine",
                    "prop",
                    "wood",
                ),
                (
                    "smoldering_tar_drum_sanitary_barrier",
                    "Smoldering Pine Tar Drum Smoke Screen",
                    "Thùng Phuy Hắc Ín Đốt Khói Mịt Mù Chắn Gió",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "stifle_cough",
                    "prop",
                    "iron",
                ),
            ],
        ),
        (
            "mass_pestilence_trench_grave",
            [
                (
                    "open_quicklime_pest_trench",
                    "Deep Rectangular Soil Plague Trench",
                    "Hố Chôn Tập Thể Sâu Rải Vôi Sống Trắng Xóa",
                    [2, 2],
                    "walk_surface",
                    False,
                    "low",
                    "inspect_pit",
                    "structure",
                    "earth",
                ),
                (
                    "wooden_plague_death_cart",
                    "High-Sided Two-Wheeled Dead Cart",
                    "Xe Cút Kít Gỗ Hai Bánh Chở Xác Bệnh Chết",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "push_cart",
                    "prop",
                    "wood",
                ),
                (
                    "quicklime_barrel_and_wooden_shovel",
                    "Wooden Barrel of Slaked Caustic Lime",
                    "Thùng Gỗ Đựng Vôi Sống Kèm Xẻng Xúc Vôi",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "spread_lime",
                    "prop",
                    "wood",
                ),
                (
                    "shrouded_corpse_linen_stack",
                    "Row of Linen-Bound Wrapped Cadavers",
                    "Hàng Xác Chết Quấn Vải Lanh Thô Chờ Chôn",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "say_prayer",
                    "prop",
                    "cloth",
                ),
                (
                    "handbell_of_the_dead_bearer",
                    "Dead-Carter Bronze Ringing Handbell",
                    "Chuông Cầm Tay Đồng Kêu Leng Keng Thu Gom Xác",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "sound_death_bell",
                    "prop",
                    "iron",
                ),
                (
                    "makeshift_rough_pine_mass_cross",
                    "Unhewn Pine Trunk Memorial Grave Cross",
                    "Cây Thánh Giá Gỗ Thông Thô Cắm Đầu Hố Chôn",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "pray_for_dead",
                    "prop",
                    "wood",
                ),
            ],
        ),
        (
            "fumigation_herbs_and_cleansing_fires",
            [
                (
                    "aromatic_juniper_fumigation_fire",
                    "Burning Pile of Green Juniper & Rosemary",
                    "Đống Cây Cù Tùng & Hương Thảo Đốt Bốc Khói",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "breathe_smoke",
                    "prop",
                    "organic",
                ),
                (
                    "sulfur_pot_corridor_cleanser",
                    "Smoldering Iron Crucible of Brimstone",
                    "Nồi Sắt Nấu Lưu Huỳnh Xông Khói Hành Lang",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "stifle_fumes",
                    "prop",
                    "iron",
                ),
                (
                    "burning_pitch_kettle_tripod",
                    "Boiling Pine Resin Pitch Kettle Stand",
                    "Nồi Nhựa Cây Thông Sôi Bốc Hơi Diệt Khuẩn",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "tend_fire",
                    "prop",
                    "iron",
                ),
                (
                    "scorched_bedding_burn_heap",
                    "Charred Pile of Infected Wool Mattresses",
                    "Đống Đệm Len Nhiễm Bệnh Đốt Thành Than",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "rake_embers",
                    "prop",
                    "organic",
                ),
                (
                    "vinegar_soaked_linen_quarantine_flag",
                    "Yellow Cloth Quarantine Flag on Pole",
                    "Lá Cờ Vàng Nhúng Giấm Báo Hiệu Có Dịch Bệnh",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "inspect_flag",
                    "prop",
                    "cloth",
                ),
                (
                    "censing_pan_long_iron_wand",
                    "Long Wand Pan for Spreading Incense",
                    "Cán Sắt Dài Đưa Bột Trầm Sưởi Ấm Phòng Bệnh",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "cense_room",
                    "prop",
                    "iron",
                ),
            ],
        ),
    ]

    for sub_id, archetypes in subs_plague:
        for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
            for v_slug, v_name, v_vn, cult, desc in var3_plague:
                slug = f"{a_slug}_{v_slug}"
                name = f"{v_name} {a_name}"
                vn = f"{a_vn} ({v_vn})"
                prompt = (
                    f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                    f"Medieval plague quarantine lazaretto pestilence style, gouache hand-painted, ink contours, isolated on white background."
                )
                items.append(
                    make_asset(
                        cid,
                        slug,
                        name,
                        vn,
                        sub_id,
                        fp,
                        col,
                        blk,
                        vis,
                        vrb,
                        f"Plague lazaretto and quarantine element ({a_name}).",
                        False,
                        mat,
                        cult,
                        prompt,
                        asset_type=atype,
                    )
                )

    return items
