# -*- coding: utf-8 -*-
"""Sphere I: The Cultural Crossroads (8 Categories, 900 Assets).

Categories:
1. anglo_norman_feudal_heartland (120: 5 subs * 24)
2. hanseatic_and_flemish_burgher (120: 5 subs * 24)
3. nordic_and_norse_coastal (120: 5 subs * 24)
4. mediterranean_and_moorish_quarter (120: 5 subs * 24)
5. slavic_eastern_taiga_and_logcraft (110: 5 subs * 22)
6. celtic_highland_and_atlantic_fringe (110: 5 subs * 22)
7. byzantine_and_crusader_frontier (100: 5 subs * 20)
8. wayfarers_nomads_and_tinker_camps (100: 5 subs * 20)
"""

from __future__ import annotations
from typing import Callable


def generate_sphere1(make_asset: Callable) -> list[dict]:
    items: list[dict] = []

    # =========================================================================
    # 1. anglo_norman_feudal_heartland (120 assets)
    # =========================================================================
    cid = "anglo_norman_feudal_heartland"
    var6 = [
        (
            "pristine_hewn",
            "Hewn Oak",
            "Gỗ Đẽo Mới",
            "anglo_norman",
            "clean freshly worked wood and sharp chisel marks",
        ),
        (
            "weathered_grey",
            "Weathered Grey",
            "Phong Hóa Xám",
            "anglo_norman",
            "silvered weathered grain with aged surface",
        ),
        (
            "rain_mossy",
            "Mossy Damp",
            "Phủ Rêu Ẩm",
            "anglo_norman",
            "deep forest moss and rain-slicked dark patches",
        ),
        (
            "scorch_marked",
            "Scorched Defense",
            "Ám Khói Chiến Trận",
            "anglo_norman",
            "soot stains and charred defensive timber",
        ),
        (
            "iron_banded",
            "Iron-Banded",
            "Bọc Sắt Kiên Cố",
            "anglo_norman",
            "heavy forged iron reinforcement straps and studs",
        ),
        (
            "creeper_clad",
            "Ivy-Clothed",
            "Dây Leo Bao Phủ",
            "anglo_norman",
            "creeping ivy tendrils and wild lichen crust",
        ),
    ]

    subs_120 = [
        (
            "motte_and_bailey_earthwork",
            [
                (
                    "palisade_stake_wall",
                    "Palisade Timber Stake Wall",
                    "Hàng Rào Cọc Gỗ Chiến Lũy",
                    [2, 1],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "wood",
                ),
                (
                    "ditched_rampart_embankment",
                    "Ditched Earthwork Rampart",
                    "Gờ Đất Hào Phòng Thủ",
                    [2, 2],
                    "cover",
                    False,
                    "low",
                    None,
                    "structure",
                    "earth",
                ),
                (
                    "motte_access_stair",
                    "Motte Timber Ascending Stair",
                    "Bậc Gỗ Leo Gò Motte",
                    [1, 2],
                    "walk_surface",
                    False,
                    "transparent",
                    "climb",
                    "structure",
                    "wood",
                ),
                (
                    "bailey_log_gatehouse",
                    "Bailey Log Gatehouse Portal",
                    "Cổng Gỗ Doanh Trại Bailey",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "open",
                    "structure",
                    "wood",
                ),
            ],
        ),
        (
            "square_norman_donjon_keep",
            [
                (
                    "limestone_corner_buttress",
                    "Norman Keep Pilaster Buttress",
                    "Trụ Áp Tường Đá Vôi Donjon",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "high_portal_draw_stair",
                    "First-Floor Defense Portal Stair",
                    "Cầu Thang Rút Cửa Tầng Hai",
                    [2, 1],
                    "walk_surface",
                    False,
                    "low",
                    "climb",
                    "structure",
                    "wood",
                ),
                (
                    "barrel_vault_store_arch",
                    "Barrel-Vaulted Cellar Arch",
                    "Vòm Đá Hầm Rượu Donjon",
                    [2, 1],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "crenellated_turret_angle",
                    "Angle Bartizan Turret",
                    "Chòi Canh Góc Tường Thành",
                    [1, 1],
                    "solid",
                    True,
                    "opaque",
                    "inspect",
                    "structure",
                    "stone",
                ),
            ],
        ),
        (
            "chevron_carved_stone_archway",
            [
                (
                    "chevron_entry_portal",
                    "Chevron Zigzag Carved Portal",
                    "Vòm Cửa Chạm Họa Tiết Răng Cưa",
                    [2, 2],
                    "walk_surface",
                    False,
                    "transparent",
                    "open",
                    "structure",
                    "stone",
                ),
                (
                    "cushion_capital_column",
                    "Norman Cushion Capital Pier",
                    "Cột Trụ Đầu Cột Nệm Norman",
                    [1, 1],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "tympanum_saint_relief",
                    "Carved Stone Tympanum Relief",
                    "Bức Phù Điêu Vòm Cửa Đá",
                    [2, 1],
                    "solid",
                    True,
                    "opaque",
                    "inspect",
                    "prop",
                    "stone",
                ),
                (
                    "billet_molding_corbel",
                    "Billet-Molded Stone Corbel",
                    "Gờ Đá Đỡ Chạm Họa Tiết Con Lăn",
                    [1, 1],
                    "solid",
                    True,
                    "transparent",
                    None,
                    "prop",
                    "stone",
                ),
            ],
        ),
        (
            "great_hall_oak_dais",
            [
                (
                    "high_lord_oak_throne",
                    "Norman Lord High Oak Chair",
                    "Ghế Tựa Lãnh Chúa Gỗ Sồi",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "sit",
                    "prop",
                    "wood",
                ),
                (
                    "trestle_feasting_board",
                    "Long Trestle Dining Board",
                    "Bàn Tiệc Gỗ Dài Trestle",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "inspect",
                    "prop",
                    "wood",
                ),
                (
                    "heraldic_woven_canopy",
                    "Baronial Woven Cloth Canopy",
                    "Mái Che Trướng Thêu Phù Hiệu",
                    [2, 1],
                    "cover",
                    False,
                    "transparent",
                    None,
                    "prop",
                    "cloth",
                ),
                (
                    "bronze_charcoal_brazier",
                    "Standing Bronze Charcoal Brazier",
                    "Lò Sưởi Đồng Than Hồng",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "warm_hands",
                    "prop",
                    "iron",
                ),
            ],
        ),
        (
            "feudal_homage_court_furnishing",
            [
                (
                    "oath_swearing_relic_chest",
                    "Reliquary Oath-Swearing Casket",
                    "Hòm Xương Thánh Thề Trung Thành",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "inspect",
                    "prop",
                    "stone",
                ),
                (
                    "knight_homage_faldstool",
                    "Folding Iron Homage Faldstool",
                    "Ghế Xếp Sắt Quỳ Tuyên Thệ",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "sit",
                    "prop",
                    "iron",
                ),
                (
                    "charter_parchment_lectern",
                    "Feudal Charter Oak Lectern",
                    "Bục Gỗ Để Hiến Chương Lãnh Địa",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "read",
                    "prop",
                    "wood",
                ),
                (
                    "heraldic_shield_stand",
                    "Norman Kite Shield Display Rack",
                    "Giá Treo Khiên Hình Diều Norman",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "inspect",
                    "prop",
                    "wood",
                ),
            ],
        ),
    ]

    for sub_id, archetypes in subs_120:
        for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
            for v_slug, v_name, v_vn, cult, desc in var6:
                slug = f"{a_slug}_{v_slug}"
                name = f"{v_name} {a_name}"
                vn = f"{a_vn} ({v_vn})"
                prompt = (
                    f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                    f"Anglo-Norman medieval feudal style, gouache hand-painted, ink contours, isolated on white background."
                )
                items.append(
                    make_asset(
                        cid,
                        slug,
                        name,
                        vn,
                        sub_id,
                        fp,
                        col,
                        blk,
                        vis,
                        vrb,
                        f"Feudal Anglo-Norman component ({a_name}).",
                        False,
                        mat,
                        cult,
                        prompt,
                        asset_type=atype,
                    )
                )

    # =========================================================================
    # 2. hanseatic_and_flemish_burgher (120 assets)
    # =========================================================================
    cid = "hanseatic_and_flemish_burgher"
    var6_hanse = [
        (
            "baltic_glazed",
            "Baltic Glazed",
            "Men Bóng Baltic",
            "flemish_hanseatic",
            "dark clinker glazed bricks and smooth mortar",
        ),
        (
            "fog_damp",
            "North Sea Damp",
            "Ẩm Ướt Biển Bắc",
            "flemish_hanseatic",
            "salt-fog patina and weathered reddish terracotta",
        ),
        (
            "gilded_trim",
            "Guild Gilded",
            "Dát Vàng Phường Hội",
            "flemish_hanseatic",
            "fine gold-leaf filigree and copper verge accents",
        ),
        (
            "iron_reinforced",
            "Iron-Braced",
            "Nẹp Sắt Kiên Cố",
            "flemish_hanseatic",
            "wrought iron wall tie anchors and forged hooks",
        ),
        (
            "soot_merchant",
            "Chimney-Sooted",
            "Bám Muội Khói",
            "flemish_hanseatic",
            "urban coal smoke smudges on masonry corners",
        ),
        (
            "mossy_canal",
            "Canal-Splashed",
            "Ngấm Nước Kênh Rêu",
            "flemish_hanseatic",
            "waterline tidal algae and wet brick base",
        ),
    ]

    subs_hanse = [
        (
            "stepped_gable_brick_facade",
            [
                (
                    "crow_stepped_roofline",
                    "Crow-Stepped Red Brick Gable",
                    "Đầu Hồi Bậc Thang Gạch Đỏ",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "pulley_beam_attic_dormer",
                    "Goods Hoist Attic Beam Dormer",
                    "Dầm Ròng Rọc Gác Mái Kéo Hàng",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "inspect",
                    "structure",
                    "wood",
                ),
                (
                    "blind_pointed_arcade_niche",
                    "Backsteingotik Blind Arch Niche",
                    "Hốc Vòm Cuốn Gạch Đỏ Trang Trí",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "leaded_bay_oriel_window",
                    "Carved Timber Oriel Bay Window",
                    "Cửa Sổ Nhô Gỗ Khắc Phường Hội",
                    [1, 1],
                    "cover",
                    True,
                    "transparent",
                    "open",
                    "structure",
                    "glass",
                ),
            ],
        ),
        (
            "canal_water_lock_and_embankment",
            [
                (
                    "heavy_timber_lock_gate",
                    "Canal Oak Sluice Lock Gate",
                    "Cửa Cống Gỗ Sồi Kênh Đào",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "turn",
                    "structure",
                    "wood",
                ),
                (
                    "mooring_iron_bollard_wharf",
                    "Quayside Forged Mooring Bollard",
                    "Cột Buộc Tàu Sắt Đúc Bờ Kênh",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "tie_boat",
                    "prop",
                    "iron",
                ),
                (
                    "stone_canal_quay_stair",
                    "Canal Water Stone Landing Steps",
                    "Bậc Đá Lên Bến Nước Kênh Đào",
                    [1, 2],
                    "walk_surface",
                    False,
                    "low",
                    "climb",
                    "structure",
                    "stone",
                ),
                (
                    "turnstile_toll_boom_barrier",
                    "Floating River Toll Timber Boom",
                    "Thanh Gỗ Chắn Thu Phí Kênh Đào",
                    [2, 1],
                    "cover",
                    True,
                    "low",
                    "inspect",
                    "prop",
                    "wood",
                ),
            ],
        ),
        (
            "cloth_hall_and_weigh_house",
            [
                (
                    "great_steelyard_balance",
                    "Suspended Iron Beam Scales (Waag)",
                    "Cân Đòn Treo Lớn Trạm Đo Lường",
                    [1, 2],
                    "cover",
                    False,
                    "low",
                    "inspect",
                    "prop",
                    "iron",
                ),
                (
                    "wool_bale_inspect_counter",
                    "Cloth Inspection Oak Counter",
                    "Bàn Gỗ Kiểm Định Kiện Vải Dạ",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "examine",
                    "prop",
                    "wood",
                ),
                (
                    "flemish_drapery_stack_shelf",
                    "Flemish Dyed Cloth Bolt Stack",
                    "Chồng Cuộn Vải Dạ Flanders Nhuộm",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "harvest",
                    "prop",
                    "cloth",
                ),
                (
                    "lead_cloth_seal_stamping_press",
                    "Guild Quality Lead Seal Press",
                    "Máy Dập Chì Dấu Phường Thợ Dệt",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "stamp",
                    "prop",
                    "iron",
                ),
            ],
        ),
        (
            "guild_merchant_counting_room",
            [
                (
                    "checkerboard_exchequer_table",
                    "Chequered Cloth Reckoning Table",
                    "Bàn Kế Toán Kẻ Ô Cờ Thuế Phí",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "reckon",
                    "prop",
                    "wood",
                ),
                (
                    "iron_clad_merchant_strongbox",
                    "Iron-Strapped Hanseatic Lockbox",
                    "Rương Sắt Khóa Ba Ổ Thương Nhân",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "open",
                    "prop",
                    "iron",
                ),
                (
                    "parchment_ledger_shelf",
                    "Bound Guild Roll & Ledger Shelf",
                    "Kệ Sách Sổ Sách Giao Thương Da Cừu",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "read",
                    "prop",
                    "wood",
                ),
                (
                    "brass_abacus_and_tallies",
                    "Brass Calculating Board & Tallies",
                    "Bàn Tính Đồng & Thẻ Gỗ Ghi Nợ",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "reckon",
                    "prop",
                    "iron",
                ),
            ],
        ),
        (
            "belfry_curfew_bell_spire",
            [
                (
                    "bronze_curfew_bell_cradle",
                    "Civic Bronze Bell in Timber Frame",
                    "Chuông Đồng Giới Nghiêm Khung Gỗ",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "ring",
                    "structure",
                    "iron",
                ),
                (
                    "copper_weathercock_finial",
                    "Gilded Burgher Weathercock Vane",
                    "Con Gà Trống Đồng Chỉ Gió Đỉnh Tháp",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "inspect",
                    "prop",
                    "iron",
                ),
                (
                    "gargoyle_lead_spout",
                    "Cast Lead Lion Rainwater Spout",
                    "Máng Thoát Nước Mưa Hình Đầu Sư Tử",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    None,
                    "prop",
                    "iron",
                ),
                (
                    "belfry_wooden_watch_walk",
                    "Timber Belfry Watchman Gallery",
                    "Hành Lang Gỗ Vọng Canh Tháp Chuông",
                    [2, 1],
                    "walk_surface",
                    False,
                    "low",
                    "watch",
                    "structure",
                    "wood",
                ),
            ],
        ),
    ]

    for sub_id, archetypes in subs_hanse:
        for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
            for v_slug, v_name, v_vn, cult, desc in var6_hanse:
                slug = f"{a_slug}_{v_slug}"
                name = f"{v_name} {a_name}"
                vn = f"{a_vn} ({v_vn})"
                prompt = (
                    f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                    f"Hanseatic Flemish burgher town style, gouache hand-painted, ink contours, isolated on white background."
                )
                items.append(
                    make_asset(
                        cid,
                        slug,
                        name,
                        vn,
                        sub_id,
                        fp,
                        col,
                        blk,
                        vis,
                        vrb,
                        f"Hanseatic urban burgher feature ({a_name}).",
                        False,
                        mat,
                        cult,
                        prompt,
                        asset_type=atype,
                    )
                )

    # =========================================================================
    # 3. nordic_and_norse_coastal (120 assets)
    # =========================================================================
    cid = "nordic_and_norse_coastal"
    var6_norse = [
        (
            "frost_cured",
            "Rime-Frosted",
            "Phủ Băng Giá",
            "nordic_norse",
            "rime frost crystals and pale chilled timber",
        ),
        (
            "tarred_black",
            "Pine-Tarred",
            "Quét Hắc Ín Gỗ",
            "nordic_norse",
            "thick glossy black pine tar weatherproofing",
        ),
        (
            "driftwood_weathered",
            "Driftwood Grey",
            "Gỗ Trôi Xám Bạc",
            "nordic_norse",
            "salt-scoured pale grey ocean timber",
        ),
        (
            "lichen_crusted",
            "Sea-Lichen Crusted",
            "Phủ Địa Y Biển",
            "nordic_norse",
            "yellow and green maritime lichen patches",
        ),
        (
            "smoke_stained",
            "Longhouse Peat-Smoked",
            "Ám Khói Bếp Than",
            "nordic_norse",
            "sooty golden patina from indoor turf fires",
        ),
        (
            "rune_inscribed",
            "Rune-Carved",
            "Khắc Chữ Cổ Runic",
            "nordic_norse",
            "deep red-ochre painted elder futhark runes",
        ),
    ]

    subs_norse = [
        (
            "turf_roofed_timber_longhouse",
            [
                (
                    "turf_sod_roof_section",
                    "Lush Turf Sod Roof Section",
                    "Mái Nhà Phủ Đất Cỏ Xanh Norse",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "earth",
                ),
                (
                    "curved_cruck_post",
                    "Curved Bog Oak Cruck Ship-Post",
                    "Cột Gỗ Cong Khung Nhà Thuyền",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "wood",
                ),
                (
                    "central_hearth_trench",
                    "Sunken Longhouse Stone Hearth Trench",
                    "Rãnh Bếp Lửa Dài Giữa Nhà Dài",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "warm_hands",
                    "prop",
                    "stone",
                ),
                (
                    "carved_bed_nook",
                    "Enclosed Oak Sleeping Alcove",
                    "Hốc Ngủ Gỗ Khắc Hoa Văn Bắc Âu",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "sleep",
                    "prop",
                    "wood",
                ),
            ],
        ),
        (
            "stave_pillar_dragon_carving",
            [
                (
                    "beast_head_ridge_prow",
                    "Dragonhead Timber Ridge Gable Prow",
                    "Đầu Rồng Gỗ Chạm Đỉnh Mái Nhà",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "inspect",
                    "prop",
                    "wood",
                ),
                (
                    "interlace_stave_pier",
                    "Urnes Style Interlace Knotwork Pillar",
                    "Cột Gỗ Chạm Dây Bện Kiểu Urnes",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "wood",
                ),
                (
                    "thor_mask_threshold_post",
                    "Deity Mask Carved Threshold Post",
                    "Cột Cửa Chạm Mặt Thần Bảo Hộ",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "inspect",
                    "prop",
                    "wood",
                ),
                (
                    "gripping_beast_bracket",
                    "Gripping Beast Support Bracket",
                    "Con Bọ Đỡ Gỗ Chạm Thú Ôm Chân",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    None,
                    "prop",
                    "wood",
                ),
            ],
        ),
        (
            "runestone_monument_and_grave",
            [
                (
                    "granite_runic_monolith",
                    "Granite Memorial Runestone Monolith",
                    "Bia Đá Cẩm Thạch Khắc Chữ Rune",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "read",
                    "prop",
                    "stone",
                ),
                (
                    "ship_setting_boulder",
                    "Viking Ship-Setting Stone Ring",
                    "Vòng Tròn Đá Mộ Hình Thuyền",
                    [2, 2],
                    "cover",
                    False,
                    "low",
                    "inspect",
                    "prop",
                    "stone",
                ),
                (
                    "carved_grave_slab_eski",
                    "Serpent-Carved Flat Burial Slab",
                    "Phiến Đá Nằm Chạm Hình Rắn Biển",
                    [2, 1],
                    "walk_surface",
                    False,
                    "transparent",
                    "inspect",
                    "prop",
                    "stone",
                ),
                (
                    "cremation_cairn_pile",
                    "Coastal Sea-Cairn Boulders",
                    "Đống Đá Mộ Gió Thổi Ven Biển",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "inspect",
                    "prop",
                    "stone",
                ),
            ],
        ),
        (
            "boathouse_naust_and_skiff",
            [
                (
                    "naust_stone_foundation_trench",
                    "Naust Drystone Boat Slipway Trench",
                    "Rãnh Đá Kéo Thuyền Tránh Bão",
                    [2, 2],
                    "walk_surface",
                    False,
                    "low",
                    "launch_boat",
                    "structure",
                    "stone",
                ),
                (
                    "clinker_rowing_faering_skiff",
                    "Four-Oared Clinker Fishing Faering",
                    "Thuyền Gỗ Bốn Mái Chèo Bắc Âu",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "row",
                    "prop",
                    "wood",
                ),
                (
                    "whale_oil_greased_rollers",
                    "Timber Hauling Rollers & Winch",
                    "Con Lăn Gỗ Kéo Thuyền Tẩm Mỡ Cá",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "operate",
                    "prop",
                    "wood",
                ),
                (
                    "tar_pot_cauldron_brazier",
                    "Boiling Pine-Tar Iron Cauldron",
                    "Vạc Sắt Nấu Nhựa Hắc Ín Quét Thuyền",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "boil_tar",
                    "prop",
                    "iron",
                ),
            ],
        ),
        (
            "whalebone_arch_and_stockfish",
            [
                (
                    "baleen_whale_jaw_gateway",
                    "Whale Jawbone Monument Archway",
                    "Cổng Vòm Xương Hàm Cá Voi Lớn",
                    [2, 2],
                    "walk_surface",
                    False,
                    "transparent",
                    "step_through",
                    "structure",
                    "organic",
                ),
                (
                    "timber_drying_cod_hjell",
                    "Atlantic Cod Drying Timber Rack (Hjell)",
                    "Giàn Gỗ Phơi Cá Tuyết Gió Biển",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "harvest",
                    "structure",
                    "wood",
                ),
                (
                    "bundle_salted_stockfish",
                    "Twine-Bound Stockfish Dried Stack",
                    "Bó Cá Tuyết Khô Cứng Đóng Bó",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "loot",
                    "prop",
                    "organic",
                ),
                (
                    "blubber_rendering_pit",
                    "Coastal Stone Seal Blubber Pit",
                    "Hố Đá Nấu Mỡ Hải Cẩu Bờ Vịnh",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "inspect",
                    "prop",
                    "stone",
                ),
            ],
        ),
    ]

    for sub_id, archetypes in subs_norse:
        for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
            for v_slug, v_name, v_vn, cult, desc in var6_norse:
                slug = f"{a_slug}_{v_slug}"
                name = f"{v_name} {a_name}"
                vn = f"{a_vn} ({v_vn})"
                prompt = (
                    f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                    f"Nordic Norse coastal settlement style, gouache hand-painted, ink contours, isolated on white background."
                )
                items.append(
                    make_asset(
                        cid,
                        slug,
                        name,
                        vn,
                        sub_id,
                        fp,
                        col,
                        blk,
                        vis,
                        vrb,
                        f"Nordic coastal cultural feature ({a_name}).",
                        False,
                        mat,
                        cult,
                        prompt,
                        asset_type=atype,
                    )
                )

    # =========================================================================
    # 4. mediterranean_and_moorish_quarter (120 assets)
    # =========================================================================
    cid = "mediterranean_and_moorish_quarter"
    var6_moor = [
        (
            "sun_baked_terracotta",
            "Sun-Baked",
            "Nắng Rám Địa Trung Hải",
            "mediterranean_moorish",
            "warm terracotta glow and chalky white plaster",
        ),
        (
            "cobalt_glazed",
            "Cobalt-Glazed",
            "Men Xanh Cobalt",
            "mediterranean_moorish",
            "vibrant deep blue and turquoise ceramic luster",
        ),
        (
            "verdigris_copper",
            "Verdigris Patina",
            "Đồng Gỉ Xanh",
            "mediterranean_moorish",
            "ancient green verdigris on beaten copper fittings",
        ),
        (
            "shaded_pergola",
            "Vine-Shaded",
            "Bóng Râm Giàn Nho",
            "mediterranean_moorish",
            "cool dappled shadows and leafy grape tendrils",
        ),
        (
            "fragrant_herbal",
            "Citrus-Wreathed",
            "Quấn Quýt Hương Cam",
            "mediterranean_moorish",
            "blossoming orange sprigs and jasmine garlands",
        ),
        (
            "weathered_adobe",
            "Stucco-Weathered",
            "Vữa Trát Phong Hóa",
            "mediterranean_moorish",
            "flaking white stucco revealing baked red clay brick",
        ),
    ]

    subs_moor = [
        (
            "arcaded_patio_courtyard",
            [
                (
                    "horseshoe_arch_portico",
                    "Moorish Horseshoe Arch Columnade",
                    "Dãy Vòm Cửa Móng Ngựa Moorish",
                    [2, 2],
                    "walk_surface",
                    False,
                    "low",
                    "walk_under",
                    "structure",
                    "stone",
                ),
                (
                    "slender_twin_marble_shaft",
                    "Twin Slender Marble Column Pier",
                    "Cặp Cột Cẩm Thạch Thanh Mảnh",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "muqarnas_stalactite_vault",
                    "Stucco Muqarnas Corbel Vault",
                    "Vòm Thạch Cao Xếp Tầng Muqarnas",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "admire",
                    "prop",
                    "stone",
                ),
                (
                    "courtyard_shaded_veranda",
                    "Terracotta Tiled Patio Veranda",
                    "Hiên Sân Vườn Lát Gạch Nung Đỏ",
                    [2, 1],
                    "walk_surface",
                    False,
                    "transparent",
                    "rest",
                    "structure",
                    "stone",
                ),
            ],
        ),
        (
            "azulejo_glazed_tile_fountain",
            [
                (
                    "octagonal_star_water_basin",
                    "Octagonal Geometric Tile Basin",
                    "Bể Nước Bát Giác Lát Gạch Sao",
                    [2, 2],
                    "water",
                    False,
                    "low",
                    "drink",
                    "structure",
                    "stone",
                ),
                (
                    "central_bubbling_copper_jet",
                    "Central Marble Jet Fountain",
                    "Vòi Phun Nước Cẩm Thạch Trung Tâm",
                    [1, 1],
                    "solid",
                    True,
                    "low",
                    "inspect",
                    "prop",
                    "stone",
                ),
                (
                    "acequia_irrigation_rill",
                    "Glazed Tile Garden Water Rill",
                    "Mương Dẫn Nước Nhỏ Lát Gạch Men",
                    [2, 1],
                    "water",
                    False,
                    "transparent",
                    "step_over",
                    "structure",
                    "stone",
                ),
                (
                    "carved_water_spout_lion",
                    "Alhambra Marble Lion Water Spout",
                    "Đầu Sư Tử Phun Nước Bằng Đá",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "fill_canteen",
                    "prop",
                    "stone",
                ),
            ],
        ),
        (
            "terracotta_stucco_villa_wall",
            [
                (
                    "whitewashed_patio_wall",
                    "Whitewashed Lime Villa Wall",
                    "Tường Vữa Quét Vôi Trắng Biệt Thự",
                    [2, 1],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "curved_terracotta_eaves_tile",
                    "Spanish Curved Red Clay Ridge Eaves",
                    "Mái Ngói Máng Đỏ Địa Trung Hải",
                    [2, 1],
                    "cover",
                    True,
                    "low",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "wrought_iron_window_reja",
                    "Wrought Iron Grille Reja Balcony",
                    "Ban Công Chấn Song Sắt Uốn Reja",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "peer_through",
                    "prop",
                    "iron",
                ),
                (
                    "arched_timber_stud_portal",
                    "Studded Cedarwood Courtyard Gate",
                    "Cổng Gỗ Tuyết Tùng Tán Đinh Đồng",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "open",
                    "structure",
                    "wood",
                ),
            ],
        ),
        (
            "olive_press_and_citrus_grove",
            [
                (
                    "heavy_beam_olive_press",
                    "Counterweighted Wooden Olive Press",
                    "Máy Ép Dầu Ô Liu Dầm Gỗ Nặng",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "press_oil",
                    "structure",
                    "wood",
                ),
                (
                    "giant_clay_oil_tinaja",
                    "Terracotta Oil Storage Jar (Tinaja)",
                    "Chum Gốm Đất Nung Khổng Lồ Đựng Dầu",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "loot",
                    "prop",
                    "stone",
                ),
                (
                    "potted_seville_orange_tree",
                    "Glazed Planter Bitter Orange Shrub",
                    "Chậu Gốm Cây Cam Đắng Seville",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "harvest",
                    "flora",
                    "plant",
                ),
                (
                    "stone_threshing_circular_floor",
                    "Cobbled Olive Sorting Yard",
                    "Sân Tròn Lát Sỏi Sơ Chế Ô Liu",
                    [2, 2],
                    "walk_surface",
                    False,
                    "transparent",
                    "work",
                    "structure",
                    "stone",
                ),
            ],
        ),
        (
            "spice_bazaar_and_silk_alcove",
            [
                (
                    "striped_canvas_market_awning",
                    "Saffron & Indigo Striped Stall Awning",
                    "Mái Bạt Sọc Màu Nghệ Tây & Chàm",
                    [2, 1],
                    "cover",
                    False,
                    "transparent",
                    None,
                    "prop",
                    "cloth",
                ),
                (
                    "copper_spice_pyramid_bowl",
                    "Woven Basket Saffron & Cumin Heap",
                    "Mẹt Đan Xếp Đầy Bột Nghệ & Thì Là",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "sample",
                    "prop",
                    "organic",
                ),
                (
                    "damascus_silk_display_rack",
                    "Moorish Embroidered Silk Drape Rack",
                    "Giá Treo Vải Lụa Thêu Damascus",
                    [1, 2],
                    "cover",
                    False,
                    "low",
                    "inspect",
                    "prop",
                    "cloth",
                ),
                (
                    "brass_hanging_perfume_censer",
                    "Perforated Brass Incense Lantern",
                    "Đèn Lồng Đồng Xông Trầm Treo",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "smell",
                    "prop",
                    "iron",
                ),
            ],
        ),
    ]

    for sub_id, archetypes in subs_moor:
        for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
            for v_slug, v_name, v_vn, cult, desc in var6_moor:
                slug = f"{a_slug}_{v_slug}"
                name = f"{v_name} {a_name}"
                vn = f"{a_vn} ({v_vn})"
                prompt = (
                    f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                    f"Mediterranean Moorish Al-Andalus style, gouache hand-painted, ink contours, isolated on white background."
                )
                items.append(
                    make_asset(
                        cid,
                        slug,
                        name,
                        vn,
                        sub_id,
                        fp,
                        col,
                        blk,
                        vis,
                        vrb,
                        f"Mediterranean Moorish quarter feature ({a_name}).",
                        False,
                        mat,
                        cult,
                        prompt,
                        asset_type=atype,
                    )
                )

    # =========================================================================
    # 5. slavic_eastern_taiga_and_logcraft (110 assets: 5 subs * 22)
    # =========================================================================
    cid = "slavic_eastern_taiga_and_logcraft"
    var_slavic = [
        (
            "fresh_pine",
            "Fresh Hewn Pine",
            "Gỗ Thông Mới Đẽo",
            "slavic_rus",
            "golden resinous aromatic pine wood",
        ),
        (
            "mossy_swamp",
            "Taiga Bog Mossy",
            "Rêu Rừng Đầm Lầy",
            "slavic_rus",
            "thick northern peat moss and damp log bark",
        ),
        (
            "rime_winter",
            "Winter Rime Chilled",
            "Sương Băng Mùa Đông",
            "slavic_rus",
            "frozen icicles and frosted roof timber",
        ),
        (
            "smoked_birch",
            "Smoked Birch Bark",
            "Ám Khói Vỏ Bạch Dương",
            "slavic_rus",
            "dark woodsmoke soot and birch tar sheen",
        ),
        (
            "red_painted",
            "Folk Red Ochre",
            "Sơn Đỏ Dân Gian",
            "slavic_rus",
            "traditional red ochre painted motifs",
        ),
    ]
    # For 22 assets per sub: 4 archetypes * 5 variants = 20 + 2 special hero variants = 22
    subs_slavic = [
        (
            "interlocking_log_izba_cabin",
            [
                (
                    "saddle_notch_timber_corner",
                    "Saddle-Notched Log Wall Corner",
                    "Góc Tường Gỗ Thông Ghép Ngàm",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "wood",
                ),
                (
                    "russian_clay_pech_stove",
                    "Massive Whitewashed Clay Pech Stove",
                    "Bếp Lò Đất Nung Khổng Lồ Kiểu Nga",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "warm_up",
                    "prop",
                    "stone",
                ),
                (
                    "timber_plank_shed_roof",
                    "Steep Pine Shingle Gable Roof",
                    "Mái Dốc Lợp Ván Gỗ Rừng Taiga",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "wood",
                ),
                (
                    "high_timber_kryltsio_porch",
                    "Covered Carved Kryltsio Porch",
                    "Hiên Nhà Gỗ Có Mái Che Kryltsio",
                    [2, 1],
                    "walk_surface",
                    False,
                    "low",
                    "enter",
                    "structure",
                    "wood",
                ),
            ],
        ),
        (
            "wooden_kremlin_rampart_wall",
            [
                (
                    "goroddnya_log_wall_chest",
                    "Soil-Filled Log Palisade Crib (Gorodnya)",
                    "Tường Thành Gỗ Chèn Đất Gorodnya",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "wood",
                ),
                (
                    "timber_crenellated_tier",
                    "Covered Wooden Wall Walk Gallery",
                    "Hành Lang Gỗ Có Mái Bắn Tên",
                    [2, 1],
                    "walk_surface",
                    False,
                    "low",
                    "patrol",
                    "structure",
                    "wood",
                ),
                (
                    "tent_roof_log_watchtower",
                    "Octagonal Tent-Roofed Log Tower",
                    "Tháp Canh Gỗ Tám Cạnh Mái Chóp",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "watch",
                    "structure",
                    "wood",
                ),
                (
                    "iron_studded_timber_gate",
                    "Log Fort Iron-Bolted Double Gate",
                    "Cổng Thành Gỗ Rừng Đóng Đinh Sắt",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "open",
                    "structure",
                    "wood",
                ),
            ],
        ),
        (
            "onion_domed_timber_chapel",
            [
                (
                    "wooden_onion_shingle_dome",
                    "Aspen Shingle Onion Cupola Dome",
                    "Mái Vòm Củ Hành Ván Gỗ Cây Tiêu Rung",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "admire",
                    "structure",
                    "wood",
                ),
                (
                    "tiered_bochka_barrel_roof",
                    "Bochka Tiered Barrel-Arched Eaves",
                    "Mái Vòm Hình Thùng Rượu Bochka",
                    [2, 1],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "wood",
                ),
                (
                    "orthodox_three_bar_cross",
                    "Carved Wooden Three-Bar Cross",
                    "Thánh Giá Ba Thanh Ngang Gỗ Khắc",
                    [1, 2],
                    "cover",
                    False,
                    "low",
                    "pray",
                    "prop",
                    "wood",
                ),
                (
                    "timber_iconostasis_stand",
                    "Carved Pine Iconostasis Screen",
                    "Vách Để Tranh Thánh Icon Gỗ Thông",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "inspect",
                    "prop",
                    "wood",
                ),
            ],
        ),
        (
            "carved_window_nalichniki_frame",
            [
                (
                    "lace_carved_window_surround",
                    "Intricate Nalichniki Lace Window",
                    "Khung Cửa Sổ Gỗ Chạm Ren Nalichniki",
                    [1, 1],
                    "cover",
                    True,
                    "transparent",
                    "peer_inside",
                    "prop",
                    "wood",
                ),
                (
                    "sun_symbol_wooden_gable_pediment",
                    "Solar Symbol Carved Gable Apex",
                    "Đỉnh Hồi Nhà Gỗ Chạm Mặt Trời",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "inspect",
                    "prop",
                    "wood",
                ),
                (
                    "decorative_carved_prichina_board",
                    "Carved Eaves Fringe Board (Prichalina)",
                    "Diềm Mái Nhà Gỗ Chạm Răng Cưa",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    None,
                    "prop",
                    "wood",
                ),
                (
                    "shutters_painted_folk_flower",
                    "Floral Folk-Painted Timber Shutters",
                    "Cánh Cửa Sổ Gỗ Vẽ Hoa Dân Gian",
                    [1, 1],
                    "cover",
                    True,
                    "opaque",
                    "close",
                    "prop",
                    "wood",
                ),
            ],
        ),
        (
            "taiga_fur_trappers_post",
            [
                (
                    "sable_fur_curing_timber_rack",
                    "Sable & Fox Fur Drying Stretcher",
                    "Khung Căng Da Chồn Zibellin & Cáo",
                    [1, 2],
                    "cover",
                    False,
                    "low",
                    "harvest_fur",
                    "prop",
                    "wood",
                ),
                (
                    "wooden_deadfall_bear_trap",
                    "Taiga Heavy Log Deadfall Trap",
                    "Bẫy Gỗ Đè Sập Săn Gấu Taiga",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "disarm",
                    "prop",
                    "wood",
                ),
                (
                    "birch_bark_backpack_kuzov",
                    "Woven Birch Bark Trapper Pack (Kuzov)",
                    "Gùi Đan Vỏ Bạch Dương Đi Rừng",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "loot",
                    "prop",
                    "organic",
                ),
                (
                    "smoked_venison_log_cache",
                    "Stilt Log Food Cache (Labaz)",
                    "Nhà Kho Nhỏ Trên Cọc Chống Thú Dữ",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "open",
                    "structure",
                    "wood",
                ),
            ],
        ),
    ]

    for sub_id, archetypes in subs_slavic:
        # 4 archetypes * 5 variants = 20
        for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
            for v_slug, v_name, v_vn, cult, desc in var_slavic:
                slug = f"{a_slug}_{v_slug}"
                name = f"{v_name} {a_name}"
                vn = f"{a_vn} ({v_vn})"
                prompt = (
                    f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                    f"Slavic Kievan Rus taiga style, gouache hand-painted, ink contours, isolated on white background."
                )
                items.append(
                    make_asset(
                        cid,
                        slug,
                        name,
                        vn,
                        sub_id,
                        fp,
                        col,
                        blk,
                        vis,
                        vrb,
                        f"Slavic taiga cultural feature ({a_name}).",
                        False,
                        mat,
                        cult,
                        prompt,
                        asset_type=atype,
                    )
                )
        # 2 bonus hero items to hit exactly 22 per subcat
        hero1 = make_asset(
            cid,
            f"{sub_id}_ancient_relic",
            f"Ancient Relic {sub_id.replace('_', ' ').title()}",
            f"Bảo Vật Cổ {sub_id.replace('_', ' ').title()}",
            sub_id,
            [2, 2],
            "solid",
            True,
            "opaque",
            "commune",
            "Ancient ancestral relic of the taiga.",
            False,
            "wood",
            "slavic_rus",
            f"Ancient ancestral relic of {sub_id}, carved wooden masterwork, Slavic Rus folklore, gouache anime style.",
        )
        hero2 = make_asset(
            cid,
            f"{sub_id}_frost_preserved",
            f"Frost-Preserved {sub_id.replace('_', ' ').title()}",
            f"Đóng Băng Vĩnh Cửu {sub_id.replace('_', ' ').title()}",
            sub_id,
            [1, 1],
            "cover",
            False,
            "low",
            "inspect",
            "Frost-preserved northern timber artifact.",
            False,
            "organic",
            "slavic_rus",
            f"Northern frost-preserved artifact of {sub_id}, encrusted in rime ice, Slavic Rus taiga, gouache style.",
        )
        items.extend([hero1, hero2])

    # =========================================================================
    # 6. celtic_highland_and_atlantic_fringe (110 assets: 5 subs * 22)
    # =========================================================================
    cid = "celtic_highland_and_atlantic_fringe"
    var_celtic = [
        (
            "ancient_granite",
            "Ancient Granite",
            "Đá Hoa Cương Cổ",
            "celtic_gaelic",
            "weather-beaten rugged granite boulders",
        ),
        (
            "peat_stained",
            "Peat-Stained",
            "Ám Màu Than Bùn",
            "celtic_gaelic",
            "dark waterlogged peat soil and rust stains",
        ),
        (
            "heather_strewn",
            "Heather-Strewn",
            "Phủ Hoa Thạch Nam",
            "celtic_gaelic",
            "purple flowering moorland heather",
        ),
        (
            "atlantic_salt",
            "Gale-Washed",
            "Gió Biển Mặn Thổi",
            "celtic_gaelic",
            "salt spray worn stone and wind-bent scrub",
        ),
        (
            "cloutie_hung",
            "Cloutie-Blessed",
            "Buộc Vải Cầu May",
            "celtic_gaelic",
            "colorful rags of prayer fluttering in the wind",
        ),
    ]

    subs_celtic = [
        (
            "circular_drystone_broch_tower",
            [
                (
                    "broch_double_hollow_wall",
                    "Drystone Broch Double Hollow Wall",
                    "Tường Đá Đôi Không Vữa Tháp Broch",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "intramural_stone_staircase",
                    "Broch Intramural Winding Stair",
                    "Bậc Thang Đá Xoắn Trong Lòng Tường",
                    [1, 2],
                    "walk_surface",
                    False,
                    "low",
                    "climb",
                    "structure",
                    "stone",
                ),
                (
                    "broch_low_linteled_entrance",
                    "Low Triangular-Linteled Entrance",
                    "Cửa Vào Tháp Đá Xà Ngang Tam Giác",
                    [1, 2],
                    "walk_surface",
                    False,
                    "transparent",
                    "crouch_enter",
                    "structure",
                    "stone",
                ),
                (
                    "guard_cell_stone_alcove",
                    "Intramural Guard Cell Alcove",
                    "Hốc Đá Gác Canh Trong Tường Tháp",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "rest",
                    "structure",
                    "stone",
                ),
            ],
        ),
        (
            "lake_dwelling_crannog_jetty",
            [
                (
                    "alder_timber_submerged_piling",
                    "Alder Wood Underwater Stilt Piling",
                    "Cọc Gỗ Cây Tiêu Rừng Cắm Lòng Hồ",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "wood",
                ),
                (
                    "wattle_hurdle_crannog_walkway",
                    "Woven Wattle Hurdle Lake Walkway",
                    "Cầu Gỗ Đan Nan Lối Vào Đảo Crannog",
                    [2, 1],
                    "walk_surface",
                    False,
                    "low",
                    "walk",
                    "structure",
                    "wood",
                ),
                (
                    "crannog_roundhouse_palisade",
                    "Circular Timber Lake-Fort Palisade",
                    "Hàng Rào Cọc Tròn Quanh Đảo Hồ",
                    [2, 1],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "wood",
                ),
                (
                    "dugout_log_canoe_dock",
                    "Oak Dugout Canoe Moored at Post",
                    "Thuyền Độc Mộc Buộc Cọc Ven Đảo Hồ",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "board_canoe",
                    "prop",
                    "wood",
                ),
            ],
        ),
        (
            "turf_beehive_clochan_hut",
            [
                (
                    "corbelled_stone_beehive_dome",
                    "Corbelled Stone Beehive Cell (Clochán)",
                    "Nhà Vòm Đá Xếp Hình Tổ Ong Clochán",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "enter",
                    "structure",
                    "stone",
                ),
                (
                    "hermit_monk_stone_sleeping_slab",
                    "Ascetic Hermit Stone Bed Slab",
                    "Giường Đá Tu Sĩ Khổ Hạnh Celtic",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "rest",
                    "prop",
                    "stone",
                ),
                (
                    "peat_fuel_stack_alcove",
                    "Cut Peat Briquette Storage Wall",
                    "Vách Xếp Bánh Than Bùn Sưởi Ấm",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "harvest",
                    "prop",
                    "earth",
                ),
                (
                    "drystone_prayer_ambry_niche",
                    "Small Recessed Stone Wall Prayer Niche",
                    "Hốc Tường Đá Nhỏ Thờ Cầu Nguyện",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "pray",
                    "prop",
                    "stone",
                ),
            ],
        ),
        (
            "celtic_wheel_high_cross",
            [
                (
                    "ringed_wheel_stone_monument",
                    "Celtic Wheel Ringed High Cross",
                    "Thánh Giá Đá Vòng Tròn Celtic",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "pray",
                    "prop",
                    "stone",
                ),
                (
                    "biblical_panel_carved_shaft",
                    "Carved Biblical Panel Cross Shaft",
                    "Thân Thánh Giá Khắc Phù Điêu Kinh Thánh",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "read",
                    "prop",
                    "stone",
                ),
                (
                    "celtic_knotwork_cross_base",
                    "Interlocking Triquetra Cross Base",
                    "Bệ Thánh Giá Chạm Họa Tiết Nút Thắt",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "inspect",
                    "prop",
                    "stone",
                ),
                (
                    "weathered_sanctuary_boundary_stone",
                    "Termon Sanctuary Boundary Marker",
                    "Cột Đá Đánh Dấu Ranh Giới Thánh Địa",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "inspect",
                    "prop",
                    "stone",
                ),
            ],
        ),
        (
            "peat_fire_hearth_and_well",
            [
                (
                    "cloutie_healing_holy_well",
                    "Cloutie Tree & Sacred Stone Well",
                    "Giếng Nước Thánh Buộc Vải Cầu Lành Bệnh",
                    [2, 2],
                    "water",
                    False,
                    "low",
                    "drink_holy_water",
                    "prop",
                    "stone",
                ),
                (
                    "central_flagstone_peat_hearth",
                    "Open Peat Fire Iron Cauldron Crane",
                    "Bếp Lửa Than Bùn Có Cần Treo Nồi",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "cook",
                    "prop",
                    "iron",
                ),
                (
                    "slated_spring_box_cistern",
                    "Spring Water Slate-Lined Cistern",
                    "Bể Đá Hứng Nước Suối Nguồn Tự Nhiên",
                    [1, 1],
                    "water",
                    False,
                    "transparent",
                    "fill_canteen",
                    "prop",
                    "stone",
                ),
                (
                    "standing_ogham_inscribed_stone",
                    "Ogham Alphabet Inscribed Standing Stone",
                    "Trụ Đá Khắc Chữ Khía Cổ Ogham",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "decipher",
                    "prop",
                    "stone",
                ),
            ],
        ),
    ]

    for sub_id, archetypes in subs_celtic:
        for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
            for v_slug, v_name, v_vn, cult, desc in var_celtic:
                slug = f"{a_slug}_{v_slug}"
                name = f"{v_name} {a_name}"
                vn = f"{a_vn} ({v_vn})"
                prompt = (
                    f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                    f"Celtic highland and Atlantic fringe style, gouache hand-painted, ink contours, isolated on white background."
                )
                items.append(
                    make_asset(
                        cid,
                        slug,
                        name,
                        vn,
                        sub_id,
                        fp,
                        col,
                        blk,
                        vis,
                        vrb,
                        f"Celtic highland cultural feature ({a_name}).",
                        False,
                        mat,
                        cult,
                        prompt,
                        asset_type=atype,
                    )
                )
        hero1 = make_asset(
            cid,
            f"{sub_id}_clan_heirloom",
            f"Highland Clan Heirloom {sub_id.replace('_', ' ').title()}",
            f"Kỷ Vật Bộ Tộc {sub_id.replace('_', ' ').title()}",
            sub_id,
            [2, 2],
            "solid",
            True,
            "opaque",
            "inspect",
            "Celtic clan sacred heirloom.",
            False,
            "stone",
            "celtic_gaelic",
            f"Ancient Celtic highland clan heirloom of {sub_id}, Gaelic mythology, gouache anime style.",
        )
        hero2 = make_asset(
            cid,
            f"{sub_id}_sacred_druidic",
            f"Sacred Druidic {sub_id.replace('_', ' ').title()}",
            f"Thánh Vật Druid {sub_id.replace('_', ' ').title()}",
            sub_id,
            [1, 1],
            "cover",
            False,
            "low",
            "commune",
            "Sacred druidic highland site.",
            False,
            "organic",
            "celtic_gaelic",
            f"Sacred druidic site component of {sub_id}, Celtic folklore, gouache anime style.",
        )
        items.extend([hero1, hero2])

    # =========================================================================
    # 7. byzantine_and_crusader_frontier (100 assets: 5 subs * 20)
    # =========================================================================
    cid = "byzantine_and_crusader_frontier"
    var4_byz = [
        (
            "levantine_sun",
            "Sun-Bleached",
            "Nắng Nở Vôi Trắng",
            "byzantine_crusader",
            "sun-bleached limestone and warm sandstone",
        ),
        (
            "brick_banded",
            "Roman Brick-Banded",
            "Chèn Gạch Gốm La Mã",
            "byzantine_crusader",
            "alternating layers of flat red Roman brick and ashlar",
        ),
        (
            "gilded_icon",
            "Byzantine Gilded",
            "Dát Vàng Byzantine",
            "byzantine_crusader",
            "gold-leaf mosaics and orthodox iconographic trims",
        ),
        (
            "siege_scarred",
            "Arrow-Pocked",
            "Vết Tên Công Thành",
            "byzantine_crusader",
            "impact craters from ballista bolts and catapult stones",
        ),
    ]
    # 5 archetypes * 4 variants = 20 per subcat
    subs_byz = [
        (
            "crusader_limestone_curtain_wall",
            [
                (
                    "bossed_ashlar_wall_tier",
                    "Rusticated Bossed Limestone Wall",
                    "Tường Đá Vôi Đẽo Gồ Ghề Kiểu Thập Tự Quân",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "talus_glacis_sloped_base",
                    "Sloped Defensive Glacis Talus",
                    "Chân Thành Vát Nghiêng Chống Đào Hầm",
                    [2, 1],
                    "solid",
                    True,
                    "low",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "machicolation_corbel_overhang",
                    "Overhanging Stone Machicolation",
                    "Lỗ Đổ Dầu Nhô Ra Đỡ Bằng Giá Đá",
                    [1, 1],
                    "solid",
                    True,
                    "opaque",
                    "defend",
                    "structure",
                    "stone",
                ),
                (
                    "cruciform_arrow_slit_pier",
                    "Cruciform Pierced Arrow Loop",
                    "Khe Bắn Tên Hình Chữ Thập",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "shoot",
                    "structure",
                    "stone",
                ),
                (
                    "potern_sally_port_arched",
                    "Reinforced Potern Sally Port",
                    "Cửa Phụ Đột Kích Vòm Cung Gia Cố",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "open",
                    "structure",
                    "wood",
                ),
            ],
        ),
        (
            "byzantine_brick_and_stone_band",
            [
                (
                    "opus_mixtum_masonry_course",
                    "Opus Mixtum Alternating Brick Wall",
                    "Tường Gạch Đá Xen Kẽ Opus Mixtum",
                    [2, 1],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "pendentive_dome_support",
                    "Brick Vault Pendentive Arch",
                    "Vòm Góc Chuyển Tiếp Đỡ Mái Vòm",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "cloisonne_patterned_facade",
                    "Cloisonné Mortared Wall Panel",
                    "Mảng Tường Viền Khung Gạch Cloisonné",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    None,
                    "structure",
                    "stone",
                ),
                (
                    "marble_revetment_facing",
                    "Polished Marble Wall Panel Revetment",
                    "Tấm Đá Cẩm Thạch Ốp Tường Cung Điện",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "inspect",
                    "prop",
                    "stone",
                ),
                (
                    "terracotta_flue_tile_stack",
                    "Hollow Roman Heating Brick Stack",
                    "Chồng Gạch Rỗng Dẫn Nhiệt Sưởi Sàn",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "inspect",
                    "prop",
                    "stone",
                ),
            ],
        ),
        (
            "roadside_iconostasis_shrine",
            [
                (
                    "marble_screen_chancel_barrier",
                    "Low Marble Chancel Templon Screen",
                    "Vách Ngăn Đá Cẩm Thạch Chancel Templon",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "pray",
                    "structure",
                    "stone",
                ),
                (
                    "hanging_silver_oil_polycandelon",
                    "Pierced Silver Polycandelon Lamp",
                    "Đèn Dầu Bạc Nhiều Ngọn Treo Thờ",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "light_lamp",
                    "prop",
                    "iron",
                ),
                (
                    "mosaic_theotokos_icon_panel",
                    "Gilded Mosaic Holy Virgin Icon",
                    "Tranh Thánh Khảm Đá Vàng Theotokos",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "venerate",
                    "prop",
                    "stone",
                ),
                (
                    "carved_peacock_marble_slab",
                    "Peacock Relief Byzantine Slab",
                    "Phiến Đá Cẩm Thạch Khắc Đôi Chim Công",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "inspect",
                    "prop",
                    "stone",
                ),
                (
                    "votive_wax_taper_stand",
                    "Wrought Brass Candle Taper Stand",
                    "Chân Cắm Nến Sáp Đồng Khấn Nguyện",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "light_candle",
                    "prop",
                    "iron",
                ),
            ],
        ),
        (
            "caravanserai_walled_compound",
            [
                (
                    "vaulted_camel_stabling_iwan",
                    "Vaulted Stabling Bay & Manger",
                    "Gian Chuồng Lạc Đà Vòm Cuốn Kèm Máng Ăn",
                    [2, 2],
                    "walk_surface",
                    False,
                    "low",
                    "stable_mount",
                    "structure",
                    "stone",
                ),
                (
                    "central_courtyard_water_cistern",
                    "Covered Central Fountain Cistern",
                    "Bể Chứa Nước Mái Vòm Giữa Sân Trạm",
                    [2, 2],
                    "water",
                    False,
                    "low",
                    "drink",
                    "structure",
                    "stone",
                ),
                (
                    "merchants_raised_sleeping_platform",
                    "Carpeted Stone Sleeping Platform",
                    "Bệ Đá Nằm Nghỉ Của Thương Lữ Trải Thảm",
                    [2, 1],
                    "walk_surface",
                    False,
                    "low",
                    "rest",
                    "structure",
                    "stone",
                ),
                (
                    "iron_clad_caravan_gatehouse",
                    "Massive Caravanserai Outer Portal",
                    "Cổng Lớn Kiên Cố Trạm Nghỉ Thương Gia",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "close",
                    "structure",
                    "wood",
                ),
                (
                    "feed_bag_and_saddle_rack",
                    "Leather Saddles & Grain Nosebags",
                    "Giá Treo Yên Cương & Bao Thóc Lạc Đà",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "loot",
                    "prop",
                    "organic",
                ),
            ],
        ),
        (
            "border_beacon_watchtower",
            [
                (
                    "square_sandstone_beacon_tower",
                    "Square Border Beacon Stone Turret",
                    "Tháp Canh Lửa Hiệu Đá Sa Thạch",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "climb",
                    "structure",
                    "stone",
                ),
                (
                    "iron_signal_fire_brazier_basket",
                    "Rooftop Signal Fire Iron Brazier",
                    "Giỏ Sắt Đốt Lửa Hiệu Đỉnh Tháp",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "light_beacon",
                    "prop",
                    "iron",
                ),
                (
                    "optical_heliograph_mirror_mount",
                    "Polished Bronze Reflecting Disk",
                    "Gương Đồng Đánh Tín Hiệu Ánh Sáng",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "signal",
                    "prop",
                    "iron",
                ),
                (
                    "lookout_timber_shading_awning",
                    "Watchman Sun-Canvas Shade Canopy",
                    "Mái Bạt Che Nắng Lính Canh Đỉnh Tháp",
                    [2, 1],
                    "cover",
                    False,
                    "transparent",
                    None,
                    "prop",
                    "cloth",
                ),
                (
                    "border_stone_boundary_stele",
                    "Imperial Frontier Border Inscription",
                    "Bia Đá Cắm Mốc Biên Cương Đế Chế",
                    [1, 2],
                    "solid",
                    True,
                    "opaque",
                    "read",
                    "prop",
                    "stone",
                ),
            ],
        ),
    ]

    for sub_id, archetypes in subs_byz:
        for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
            for v_slug, v_name, v_vn, cult, desc in var4_byz:
                slug = f"{a_slug}_{v_slug}"
                name = f"{v_name} {a_name}"
                vn = f"{a_vn} ({v_vn})"
                prompt = (
                    f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                    f"Byzantine Crusader frontier outpost style, gouache hand-painted, ink contours, isolated on white background."
                )
                items.append(
                    make_asset(
                        cid,
                        slug,
                        name,
                        vn,
                        sub_id,
                        fp,
                        col,
                        blk,
                        vis,
                        vrb,
                        f"Byzantine Crusader frontier feature ({a_name}).",
                        False,
                        mat,
                        cult,
                        prompt,
                        asset_type=atype,
                    )
                )

    # =========================================================================
    # 8. wayfarers_nomads_and_tinker_camps (100 assets: 5 subs * 20)
    # =========================================================================
    cid = "wayfarers_nomads_and_tinker_camps"
    var4_nomad = [
        (
            "traveled_dusty",
            "Dust-Covered",
            "Bụi Đường Xa",
            "wayfarer_nomad",
            "worn canvas and dust-stained road timber",
        ),
        (
            "rain_soaked",
            "Rain-Drenched",
            "Mưa Ướt Sũng",
            "wayfarer_nomad",
            "dark soaked wool canvas with water runoff streaks",
        ),
        (
            "festive_ribbon",
            "Ribbon-Adorned",
            "Buộc Dải Ruy Băng",
            "wayfarer_nomad",
            "brightly dyed festive ribbons and brass jingle bells",
        ),
        (
            "patchwork_stitched",
            "Patchwork-Mended",
            "Vá Víu Chắp Vá",
            "wayfarer_nomad",
            "colorful mismatched cloth and leather patch mends",
        ),
    ]

    subs_nomad = [
        (
            "barrel_top_wooden_vardo_wagon",
            [
                (
                    "bow_top_painted_living_wagon",
                    "Painted Bow-Top Living Vardo Wagon",
                    "Xe Ngựa Mui Cong Vardo Vẽ Hoa Văn",
                    [2, 2],
                    "solid",
                    True,
                    "opaque",
                    "enter",
                    "structure",
                    "wood",
                ),
                (
                    "wagon_iron_stove_pipe_chimney",
                    "Tiny Tin Stove Chimney Pipe",
                    "Ống Khói Lò Sưởi Nhỏ Trên Mui Xe",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    None,
                    "prop",
                    "iron",
                ),
                (
                    "heavy_spoked_wagon_wheel_spare",
                    "Carved Wooden Spoked Wagon Wheel",
                    "Bánh Xe Bò Gỗ Nan Hoa Dự Phòng",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "repair",
                    "prop",
                    "wood",
                ),
                (
                    "under_chassis_chicken_coop",
                    "Undercarriage Slatted Chicken Crate",
                    "Lồng Gà Nan Tre Dưới Gầm Xe",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "loot_eggs",
                    "prop",
                    "wood",
                ),
                (
                    "wagon_hitch_pole_and_whippletree",
                    "Horse Draft Shaft & Singletree",
                    "Càng Xe Kéo Ngựa Kèm Trục Đòn Gánh",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "hitch_horse",
                    "prop",
                    "wood",
                ),
            ],
        ),
        (
            "tinker_brazier_and_tin_pots",
            [
                (
                    "traveling_tinker_charcoal_brazier",
                    "Portable Iron Sheet Tinker Forge",
                    "Bếp Lò Than Mini Di Động Thợ Hàn Nồi",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "mend_pot",
                    "prop",
                    "iron",
                ),
                (
                    "hanging_clattering_copper_pots",
                    "Timber Tripod Hanging Kettle Rack",
                    "Giá Gỗ Treo Ấm Nồi Đồng Đang Hàn",
                    [1, 2],
                    "cover",
                    False,
                    "low",
                    "loot",
                    "prop",
                    "iron",
                ),
                (
                    "soldering_iron_and_lead_pellets",
                    "Tinker Tool Sack & Solder Ingot",
                    "Túi Đồ Nghề Mỏ Hàn & Thỏi Chì",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "craft",
                    "prop",
                    "iron",
                ),
                (
                    "grindstone_pedal_sharpening_rig",
                    "Pedal-Driven Mower Sharpening Wheel",
                    "Bàn Đạp Đá Mài Dao Kéo Lưu Động",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "sharpen_blade",
                    "prop",
                    "stone",
                ),
                (
                    "repaired_pewter_tankard_tray",
                    "Tray of Patched Pewter Tankards",
                    "Khay Cốc Thiếc Đã Hàn Miệng",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "inspect",
                    "prop",
                    "iron",
                ),
            ],
        ),
        (
            "nomad_canvas_wedge_tent",
            [
                (
                    "triangular_ridge_canvas_tent",
                    "Low Wedge Ridge Canvas Traveler Tent",
                    "Lều Vải Hình Tam Giác Du Mục",
                    [2, 2],
                    "cover",
                    True,
                    "low",
                    "rest",
                    "structure",
                    "cloth",
                ),
                (
                    "open_awning_shade_shelter",
                    "Pole-Propped Canvas Sun Awning",
                    "Mái Che Bạt Chống Cột Tránh Nắng",
                    [2, 1],
                    "walk_surface",
                    False,
                    "low",
                    "rest",
                    "structure",
                    "cloth",
                ),
                (
                    "sheepskin_bedroll_spread",
                    "Thick Wool Sheepskin Sleeping Pelt",
                    "Tấm Thảm Lông Cừu Trải Ngủ",
                    [1, 1],
                    "walk_surface",
                    False,
                    "transparent",
                    "sleep",
                    "prop",
                    "organic",
                ),
                (
                    "tied_canvas_guyline_and_peg",
                    "Carved Ashwood Tent Peg & Rope",
                    "Cọc Gỗ Cắm Lều & Dây Buộc Chằng",
                    [1, 1],
                    "walk_surface",
                    False,
                    "transparent",
                    None,
                    "prop",
                    "wood",
                ),
                (
                    "hanging_oil_lamp_tent_pole",
                    "Center Pole Hanging Tin Lantern",
                    "Đèn Bão Thiếc Treo Cột Lều Giữa",
                    [1, 1],
                    "cover",
                    False,
                    "transparent",
                    "light",
                    "prop",
                    "iron",
                ),
            ],
        ),
        (
            "horse_tether_line_and_saddles",
            [
                (
                    "high_picket_rope_tether_line",
                    "Braided Rope Horse Picket Line",
                    "Dây Thừng Căng Buộc Đàn Ngựa",
                    [2, 1],
                    "walk_surface",
                    False,
                    "low",
                    "tether",
                    "prop",
                    "organic",
                ),
                (
                    "worn_leather_pack_saddle_trestle",
                    "Wooden Pack Saddle on Trestle Stand",
                    "Yên Thồ Hàng Bằng Da Đặt Trên Giá",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "loot",
                    "prop",
                    "wood",
                ),
                (
                    "oat_grain_feeding_trough_log",
                    "Hollowed Pine Log Horse Feeder",
                    "Máng Cỏ Gỗ Thông Khoét Rỗng Cho Ngựa",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "feed_mount",
                    "prop",
                    "wood",
                ),
                (
                    "horse_blanket_drying_fence",
                    "Woolen Saddle Blanket on Hurdle",
                    "Chăn Yên Ngựa Bằng Len Phơi Trên Rào",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "inspect",
                    "prop",
                    "cloth",
                ),
                (
                    "iron_curry_comb_and_hoof_pick",
                    "Grooming Box Hoof Pick & Brushes",
                    "Hộp Bàn Chải & Móc Vệ Sinh Móng Ngựa",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "groom",
                    "prop",
                    "iron",
                ),
            ],
        ),
        (
            "campfire_circle_and_instruments",
            [
                (
                    "river_stone_campfire_ring",
                    "Circular Stone Campfire Pit with Embers",
                    "Hố Lửa Trại Quây Đá Cuội Than Hồng",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "cook_campfire",
                    "prop",
                    "stone",
                ),
                (
                    "wooden_hurdy_gurdy_case",
                    "Carved Hurdy-Gurdy & Lute Case",
                    "Đàn Hurdy-Gurdy & Hộp Đàn Lute Gỗ",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "play_music",
                    "prop",
                    "wood",
                ),
                (
                    "sitting_log_with_carved_chess",
                    "Debarked Sitting Log with Chess Grid",
                    "Khúc Gỗ Ngồi Khắc Bàn Cờ Vua",
                    [2, 1],
                    "cover",
                    False,
                    "low",
                    "sit",
                    "prop",
                    "wood",
                ),
                (
                    "spit_roasted_grouse_tripod",
                    "Iron Tripod Spit-Roasted Wild Fowl",
                    "Giá Sắt Quay Chim Rừng Trên Lửa",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "eat",
                    "prop",
                    "organic",
                ),
                (
                    "leather_wine_bota_bag_post",
                    "Hanging Leather Wine Bota Skin",
                    "Bình Da Đựng Rượu Treo Trên Cọc",
                    [1, 1],
                    "cover",
                    False,
                    "low",
                    "drink_wine",
                    "prop",
                    "organic",
                ),
            ],
        ),
    ]

    for sub_id, archetypes in subs_nomad:
        for a_slug, a_name, a_vn, fp, col, blk, vis, vrb, atype, mat in archetypes:
            for v_slug, v_name, v_vn, cult, desc in var4_nomad:
                slug = f"{a_slug}_{v_slug}"
                name = f"{v_name} {a_name}"
                vn = f"{a_vn} ({v_vn})"
                prompt = (
                    f"2D orthographic top-down game sprite of {name.lower()}, {desc}, "
                    f"Medieval itinerant wayfarer nomad camp style, gouache hand-painted, ink contours, isolated on white background."
                )
                items.append(
                    make_asset(
                        cid,
                        slug,
                        name,
                        vn,
                        sub_id,
                        fp,
                        col,
                        blk,
                        vis,
                        vrb,
                        f"Wayfarer nomad campsite feature ({a_name}).",
                        False,
                        mat,
                        cult,
                        prompt,
                        asset_type=atype,
                    )
                )

    return items
