# -*- coding: utf-8 -*-
"""Complete scaffolding generator for Ancient Chinese Mortal World asset pack (Categories 7-14)."""

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
PACK_PATH = REPO_ROOT / "game/assets/packs/ancient_china_mortal/ancient_china_mortal_pack.json"

def make_asset(
    cat_id: str,
    slug: str,
    name: str,
    vn_name: str,
    hanzi: str,
    sub_cat: str,
    footprint: list[int],
    collision: str,
    blocks_proj: bool,
    vision: str,
    verb: str | None,
    role: str,
    destructible: bool,
    material: str,
    element: str,
    prompt: str,
    asset_type: str,
    alpha: str,
    pivot: str,
    hooks: dict
) -> dict:
    return {
        "id": f"ancient_china_mortal.{cat_id}.{slug}",
        "name": name,
        "vietnamese_name": vn_name,
        "hanzi": hanzi,
        "category": cat_id,
        "sub_category": sub_cat,
        "type": asset_type,
        "alpha": alpha,
        "pivot": pivot,
        "footprint_cells": footprint,
        "canvas_px": [footprint[0] * 128, footprint[1] * 128],
        "collision_type": collision,
        "blocks_projectile": blocks_proj,
        "vision_mode": vision,
        "interactive_verb": verb,
        "gameplay_role": role,
        "destructible": destructible,
        "material": material,
        "cultivation_element": element,
        "prompt_summary": prompt,
        "racial_faction": "mortal_dynasty",
        "environment_name": "Ancient China Mortal World (Cửu Châu Phàm Trần)",
        "environment_theme": "2D Orthographic top-down, gouache hand-painted, ink contour lines (#263A35), grounded East Asian mortal palette.",
        "world_tier": "Mortal World (Phàm Nhân Giới / Cửu Châu)",
        "status": "planned",
        "reference_ids": ["docs/art-direction.md#top-down-world-map"],
        "source": "ComfyUI local unet: krea2/raySemiReal_krea2TurboV1Nsfw.safetensors, lora: krea2/Scottie__Krea2.safetensors (1.0)",
        "license": "Generated locally; source checkpoint license terms apply",
        "gameplay_gap_hooks": hooks
    }

def generate_all_remaining() -> list[dict]:
    all_new: list[dict] = []
    
    # Load Category 7 from partial file if available
    partial = REPO_ROOT / "build/scaffold_batch3_partial.json"
    if partial.is_file():
        all_new.extend(json.loads(partial.read_text(encoding="utf-8")))

    # --------------------------------------------------------------------------
    # CATEGORY 8: TRADE, CRAFT & INDUSTRY (55 assets)
    # sub_categories: salt_evaporation_pan (9), ceramic_and_brick_kiln (10), charcoal_burning_mound (9), iron_smithy_forge (10), dye_vat_and_silk_rack (9), grain_threshing_floor (8)
    # --------------------------------------------------------------------------
    c8_subs = [
        ("salt_evaporation_pan", [
            ("ind_salt_coastal_pan_crystallized", "Coastal Tidal Salt Evaporation Pan", "Ruộng Muối Kết Tinh Ven Biển", "沿海结晶盐田", [3, 2], "none", False, "transparent", "harvest_salt", "Grid of shallow square clay pans glistening with white salt crystals.", False, "clay", "water", "Top-down view of ancient Chinese coastal salt evaporation pan grid, white crystallized salt crust reflecting sky.", "structure", "transparent", "center", {"salt_yield": 50}),
            ("ind_salt_brine_boiling_furnace_dome", "Clay Dome Brine Evaporation Furnace", "Lò Nấu Muối Bằng Nồi Gang Lớn", "煮盐穹顶土灶", [2, 2], "solid", True, "solid", "boil_brine", "Large domed clay stove boiling seawater in cast iron pans.", False, "clay", "fire", "Ancient round clay dome furnace for boiling sea brine with iron boiling pan and wood fuel stack.", "building", "transparent", "bottom_center", {"heat_source": True}),
            ("ind_salt_rake_wooden_scraper_tool", "Long Wooden Salt Harvesting Rakes", "Cào Gỗ Thu Gom Muối Hạt", "木制刮盐板耙", [1, 1], "ground_contact", False, "transparent", "pick_up", "T-shaped wooden scraper boards on long poles.", True, "wood", "mortal", "Pair of long-handled wooden salt gathering scraping rakes leaning against salt mound.", "prop", "transparent", "bottom_center", {"tool": "salt_rake"}),
            ("ind_salt_storage_thatched_pyramid_shed", "Conical Thatch Salt Storage Hovel", "Chòi Mái Bổi Trữ Muối Chống Mưa", "圆锥草盖盐仓", [2, 2], "solid", True, "solid", "doorway", "Cone-shaped thatch roofed hut protecting refined salt from rain.", False, "straw", "mortal", "Conical straw thatch storehouse shed sitting on elevated dry wooden platform on salt flat.", "building", "transparent", "bottom_center", {"salt_storage": 500}),
            ("ind_salt_white_mound_drying_heap", "Pure White Refined Salt Pyramid Mound", "Đụn Muối Trắng Tinh Phơi Nắng", "洁白日晒盐堆", [2, 1], "ground_contact", False, "transparent", "shovel_salt", "Pyramid mound of coarse white sea salt drying in breeze.", True, "salt", "mortal", "Cone pyramid mound of sparkling coarse white sea salt crystals on hard earth.", "prop", "transparent", "bottom_center", {"resource": "refined_salt"}),
            ("ind_salt_windmill_brine_pump", "Cloth Sail Coastal Brine Pumping Windmill", "Cối Xay Gió Bơm Nước Biển Nấu Muối", "布翼风力汲卤水车", [2, 2], "solid", True, "transparent", "operate_pump", "Small wooden windmill with four canvas sails pumping sea water.", False, "wood", "wind", "Ancient Chinese wooden coastal drainage windmill with four linen cloth sails turning wooden pump.", "structure", "transparent", "bottom_center", {"automated_pumping": True}),
            ("ind_salt_bamboo_brine_pipeline", "Elevated Split Bamboo Brine Aqueduct", "Máng Tre Dẫn Nước Biển Trên Cao", "架空竹管卤水道", [3, 1], "walk_surface", False, "transparent", None, "Overhead bamboo trough carrying brine to pans.", False, "bamboo", "water", "Elevated trestle supporting halved giant bamboo tubes carrying flowing seawater to salt pans.", "structure", "transparent", "bottom_center", {"fluid_conduit": True}),
            ("ind_salt_official_tax_weighing_station", "Monopoly Salt Bureau Official Scales", "Trạm Cân Muối Độc Quyền Triều Đình", "官收官运量盐亭", [2, 2], "core_ring", True, "transparent", "sell_salt", "Imperial monopoly bureau controlling salt commerce.", False, "wood", "mortal", "Open timber kiosk with official imperial brass balances and copper seal stamps for salt taxation.", "building", "transparent", "bottom_center", {"state_monopoly": True}),
            ("ind_salt_cart_heavy_wooden_salt_dray", "Heavy Ox Cart Loaded with Salt Sacks", "Xe Bò Chở Muối Đóng Bao Kín", "牛拉粗盐大货车", [2, 1], "solid", True, "transparent", "loot", "Heavy two-wheeled cart carrying salt bags wrapped in straw.", True, "wood", "mortal", "Heavy wooden cart with straw-covered sacks of crystalline salt tied with thick rope.", "prop", "transparent", "bottom_center", {"loot_salt": 100})
        ]),
        ("ceramic_and_brick_kiln", [
            ("ind_kiln_sloping_dragon_kiln_long", "Chambered Dragon Kiln on Hillside (Longyao)", "Lò Rồng Nung Gốm Bậc Thang (Long Diêu)", "依山斜坡古龙窑", [5, 2], "solid", True, "solid", "fire_pottery", "Long terraced tunnel kiln creeping up slope like sleeping dragon.", False, "brick", "fire", "Ancient Chinese climbing Dragon Kiln (Longyao) built up grassy hillside slope with multiple brick stoking ports and billowing smoke.", "building", "transparent", "bottom_center", {"kiln_tier": "masterwork"}),
            ("ind_kiln_round_beehive_brick_kiln", "Beehive Brick-Fired Ceramic Kiln", "Lò Bầu Nung Gạch Ngói Hình Tổ Ong", "馒头型砖瓦窑", [3, 3], "solid", True, "solid", "doorway", "Round dome brick furnace with iron stoking door.", False, "brick", "fire", "Round dome beehive brick-firing kiln made of blackened scorched firebricks with tall chimney.", "building", "transparent", "bottom_center", {"brick_production": True}),
            ("ind_kiln_unfired_clay_brick_pallets", "Neat Rows of Sun-Drying Green Bricks", "Hàng Gạch Mộc Đang Phơi Khô", "整齐晾干生泥砖", [2, 1], "solid", False, "transparent", "crush", "Neat staggered stacks of unfired loess clay bricks drying.", True, "clay", "earth", "Staggered open-air stacks of raw grey-yellow unfired clay bricks drying on wooden boards.", "prop", "transparent", "bottom_center", {"raw_bricks": 200}),
            ("ind_kiln_potters_foot_wheel_bench", "Potter Foot-Treadle Kickwheel Station", "Bàn Xoay Gốm Đạp Chân Dưới Mái Hiên", "陶工手拉坯脚踏轮", [1, 1], "ground_contact", False, "transparent", "throw_clay", "Heavy wooden turntable spun by foot with wet clay vase.", False, "wood", "mortal", "Rustic potters workshop bench with wooden kickwheel, bowl of slip water, and half-shaped clay urn on wheel.", "prop", "transparent", "bottom_center", {"craft_pottery": True}),
            ("ind_kiln_glaze_preparation_stone_mortar", "Glaze Mineral Crushing Stone Mortar", "Cối Đá Nghiền Men Gốm Sứ", "水碓捣碎釉石碓", [1, 1], "solid", False, "transparent", "grind_glaze", "Deep granite hollow mortar with heavy pestle for feldspar.", False, "stone", "mortal", "Deep carved granite mortar with iron pestle containing powdered celadon glaze minerals.", "prop", "transparent", "bottom_center", {"alchemy_glaze": True}),
            ("ind_kiln_saggar_fireclay_box_stacks", "Stacked Ceramic Firing Saggars (Xiaobo)", "Chồng Hộp Đất Chịu Lửa Nung Đồ Sứ", "耐火陶土匣钵堆", [2, 1], "solid", False, "transparent", "inspect", "Cylindrical fireclay containers protecting porcelain in kiln.", True, "ceramic", "mortal", "Pyramid stack of cylindrical brown fireclay saggar boxes protecting delicate vases during firing.", "prop", "transparent", "bottom_center", {"ceramic_parts": True}),
            ("ind_kiln_discarded_shards_cullet_mound", "Mountain of Cracked Glazed Potsherds", "Gò Mảnh Gốm Vỡ Phế Thải Men Lam", "碎瓷片碎陶大废堆", [2, 2], "ground_contact", False, "transparent", "salvage_shards", "Huge mound of shiny blue-and-white cracked porcelain shards.", False, "ceramic", "mortal", "Heap of discarded broken glazed ceramics, celadon shards, and flawed earthenware vases gleaming in sun.", "prop", "transparent", "bottom_center", {"sharp_hazard": True}),
            ("ind_kiln_wood_fuel_stacked_cordwood", "Split Oak & Pine Kiln Firewood Cords", "Đống Củi Gỗ Thông Đốt Lò Nung", "松木窑柴大木垛", [3, 1], "solid", True, "transparent", "take_wood", "Cords of resinous split pine logs for high temperature firing.", True, "wood", "fire", "Massive neat rectangular stack of split dry pine logs with axe embedded in chopping stump.", "prop", "transparent", "bottom_center", {"fuel_firewood": 300}),
            ("ind_kiln_drying_racks_greenware_pots", "Shelved Racks of Unfired Vases & Bowls", "Giá Gỗ Phơi Bình Gốm Mộc Chưa Nung", "阴干生坯陶器架", [2, 1], "ground_contact", False, "transparent", "smash", "Tiered wooden shelves holding greenware teapots and jars.", True, "wood", "mortal", "Three-tier wooden drying shelf holding dozens of delicate unfired grey clay bowls, cups, and jugs.", "prop", "transparent", "bottom_center", {"fragile": True}),
            ("ind_kiln_master_office_sample_display", "Kiln Master Showroom & Specimen Cabinet", "Gian Trưng Bày Đồ Sứ Tinh Xảo Lò Nung", "窑主鉴赏样品阁", [2, 2], "core_ring", True, "transparent", "appraise_ceramics", "Refined pavilion displaying gleaming tea sets and celadon ware.", False, "wood", "mortal", "Elegant timber showroom displaying lustrous green celadon bowls and fine white porcelain vases.", "building", "transparent", "bottom_center", {"luxury_trade": True})
        ]),
        ("charcoal_burning_mound", [
            ("ind_charcoal_earth_covered_smoldering_kiln", "Earthen Smoldering Charcoal Mound (Tan Yao)", "Gò Đất Đốt Than Củi Âm Ỉ", "覆土焖烧炭窑堆", [3, 3], "solid", True, "solid", "tend_fire", "Domed earth-covered mound venting white wood vinegar smoke.", False, "earth", "fire", "Large round domed earthen mound of smoking charcoal with vent holes puffing sweet white smoke.", "structure", "transparent", "bottom_center", {"charcoal_yield": 80}),
            ("ind_charcoal_cooling_charcoal_black_heaps", "Fresh Cooling Lumps of Black Charcoal", "Đống Than Đen Vừa Dỡ Lò Nguội Dần", "冷却黑炭大堆", [2, 1], "ground_contact", False, "transparent", "gather_charcoal", "Mound of shiny black crystalline fuel chunks on dirt.", True, "charcoal", "fire", "Mound of freshly raked shiny black charcoal lumps with faint grey ash fringes on burnt earth.", "prop", "transparent", "bottom_center", {"fuel_charcoal": 50}),
            ("ind_charcoal_woven_wicker_transport_baskets", "Pair of Giant Charcoal Carrying Baskets", "Cặp Sọt Tre Đựng Than Củi Cỡ Lớn", "大竹篓装炭筐", [1, 1], "ground_contact", False, "transparent", "carry_basket", "Deep conical woven wicker panniers with shoulder pole.", True, "bamboo", "mortal", "Pair of tall conical woven wicker baskets filled with black charcoal chunks with shoulder carrying yoke.", "prop", "transparent", "bottom_center", {"container": "charcoal"}),
            ("ind_charcoal_woodcutter_broad_axe_stump", "Heavy Charcoal Felling Axe on Oak Stump", "Rìu Bổ Củi Nặng Cắm Trên Khúc Gỗ", "伐木大斧砍木桩", [1, 1], "ground_contact", False, "transparent", "pick_up_axe", "Heavy iron axe head driven into large tree stump.", False, "iron", "mortal", "Heavy double-handed iron felling axe embedded deep in cracked round oak stump with split chips.", "prop", "transparent", "bottom_center", {"tool": "felling_axe"}),
            ("ind_charcoal_stack_raw_hardwood_billets", "Stacked Hardwood Charcoal Billets", "Chồng Khúc Cỗ Sồi Chờ Đốt Than", "紧密硬木炭材堆", [2, 1], "solid", True, "transparent", "chop_wood", "Uniform length green oak branches trimmed for stacking.", True, "wood", "mortal", "Uniformly cut round logs of green oak and birch wood stacked tightly between upright wooden stakes.", "prop", "transparent", "bottom_center", {"wood_billets": 100}),
            ("ind_charcoal_turf_stripping_sod_pile", "Grass Sod Squares for Sealing Kiln", "Chồng Tảng Cỏ Đắp Kín Lò Than", "封窑草皮土块", [1, 1], "ground_contact", False, "transparent", "use_sod", "Layered squares of damp earth turf used to smother kiln flames.", False, "earth", "mortal", "Neat stack of cut square grass turf sods with moist earth roots for capping burning charcoal pits.", "prop", "transparent", "bottom_center", {"seal_material": True}),
            ("ind_charcoal_collier_thatched_lean_to", "Charcoal Burner Primitive Forest Shanty", "Lán Tranh Của Người Thợ Đốt Than", "炭翁森林草棚", [2, 2], "core_ring", True, "solid", "rest", "Crude lean-to of bark and branches for lonely forest collier.", True, "wood", "mortal", "Primitive single-pitch thatched lean-to shack made of tree branches, straw bedding, hanging soot kettle.", "building", "transparent", "bottom_center", {"shelter": "rustic"}),
            ("ind_charcoal_soot_blackened_rake_hoe", "Long-Handled Iron Charcoal Rake & Hoe", "Cào Sắt Khều Than Dài Cán Gỗ", "铁齿捞炭扒", [1, 1], "ground_contact", False, "transparent", "pick_up", "Curved heavy iron rake used to drag out hot charcoal.", False, "iron", "mortal", "Long-handled forged iron claw rake with soot-blackened wooden shaft resting against rock.", "prop", "transparent", "bottom_center", {"tool": "charcoal_rake"}),
            ("ind_charcoal_wood_vinegar_collection_jar", "Pottery Jar Collecting Condensation Liquid", "Vò Gốm Hứng Giấm Gỗ Tự Nhiên", "接木醋液土陶坛", [1, 1], "ground_contact", False, "transparent", "take_vinegar", "Clay pot receiving distilled brown wood smoke essence.", True, "ceramic", "water", "Earthenware jar positioned under bamboo kiln spout collecting condensed brown wood vinegar drops.", "prop", "transparent", "bottom_center", {"alchemical_liquid": "wood_vinegar"})
        ]),
        ("iron_smithy_forge", [
            ("ind_forge_blacksmith_workshop_pavilion", "Open-Front Village Iron Smithy Forge", "Lò Rèn Sắt Thôn Làng Mái Ngói Mở", "铁匠铺打铁工坊", [3, 2], "solid", True, "solid", "doorway", "Soot-blackened stone building with hearth, bellows, and tools.", False, "brick", "fire", "Open-sided village blacksmith workshop with brick furnace, heavy water quench trough, hanging tongs and hammers.", "building", "transparent", "bottom_center", {"blacksmith_craft": True}),
            ("ind_forge_great_bellows_wind_box", "Double-Action Piston Wooden Wind Box (Feng Xiang)", "Ống Thổi Bễ Gỗ Thổi Lửa (Phong Tương)", "双动活塞风箱", [2, 1], "solid", False, "transparent", "pump_bellows", "Large wooden box with push-pull lever generating continuous air blast.", False, "wood", "wind", "Ancient Chinese wooden rectangular piston box bellows (Fengxiang) with wooden handle and air exhaust pipe into forge.", "prop", "transparent", "bottom_center", {"forge_heat_bonus": 2.0}),
            ("ind_forge_heavy_forged_iron_anvil", "Heavy Block Iron Anvil on Tree Stump", "Đe Sắt Đúc Nặng Trên Gốc Cây", "老铁砧木底座", [1, 1], "solid", False, "transparent", "strike_iron", "Massive cast-iron anvil with horn set into banded oak block.", False, "iron", "metal", "Heavy dark iron anvil with horn resting on steel-banded solid tree trunk block, hammer resting on top.", "prop", "transparent", "bottom_center", {"smithing_station": True}),
            ("ind_forge_water_quench_cooling_trough", "Stone Water Quenching & Tempering Trough", "Bể Đá Tôi Sắt Nước Bốc Khói", "石凿淬火冷水槽", [2, 1], "solid", False, "transparent", "quench_blade", "Deep stone trough of murky water with hissing steam wisps.", False, "stone", "water", "Deep carved stone water trough filled with murky water and oily film for sword quenching.", "prop", "transparent", "bottom_center", {"tempering": True}),
            ("ind_forge_tool_rack_tongs_hammers", "Smithy Tool Wall of Tongs & Sledgehammers", "Giá Treo Kìm Búa Lò Rèn Đủ Loại", "铁匠钳子铁锤排架", [1, 1], "ground_contact", False, "transparent", "take_hammer", "Wall rack holding tongs of every jaw shape and heavy hammers.", False, "iron", "mortal", "A-frame wooden tool rack hung with heavy sledgehammers, curved tongs, chisels, and iron files.", "prop", "transparent", "bottom_center", {"tool_set": "smithing"}),
            ("ind_forge_raw_pig_iron_ingot_stack", "Stacked Cast Pig Iron Bars & Blooms", "Chồng Thỏi Sắt Sống Đúc Thô", "生铁块熟铁条堆", [1, 1], "ground_contact", False, "transparent", "take_iron", "Heavy rectangular rough iron ingots stamped with furnace marks.", False, "iron", "metal", "Stacked criss-cross pile of dark grey raw pig iron bars and sponge iron blooms.", "prop", "transparent", "bottom_center", {"craft_resource": "iron_ingots", "count": 20}),
            ("ind_forge_grindstone_pedal_treadle", "Pedal-Operated Rotary Sandstone Grinder", "Bàn Mài Dao Kéo Đạp Chân Bằng Đá", "脚踏旋转磨刀石", [1, 1], "ground_contact", False, "transparent", "sharpen_weapon", "Circular sandstone wheel rotated by foot treadle with water drip.", False, "stone", "mortal", "Wooden frame holding circular rotating sandstone grinding wheel with leather foot treadle and water drip can.", "prop", "transparent", "bottom_center", {"sharpen_buff": 0.15}),
            ("ind_forge_spark_shield_wattle_screen", "Fireproof Mud-Plastered Spark Screen", "Vách Trát Bùn Chắn Tàn Lửa Bay", "防飞火泥抹屏障", [2, 1], "solid", False, "transparent", None, "Wattle screen coated in mud to stop forge sparks igniting thatch.", True, "clay", "mortal", "Thick mud-plastered wattle wall screen charred with brown soot marks protecting building corners from sparks.", "structure", "transparent", "bottom_center", {"fireproof": True}),
            ("ind_forge_plowshares_hoes_finished_pile", "Finished Iron Plowshares & Sickles Pile", "Đống Lưỡi Cày Lưỡi Liềm Rèn Xong", "锻造完成铁犁铧堆", [1, 1], "ground_contact", False, "transparent", "gather_tools", "Shining newly ground agricultural iron implements.", True, "iron", "mortal", "Neat pile of freshly sharpened curved iron sickles, heavy plowshares, and agricultural hoes.", "prop", "transparent", "bottom_center", {"farm_implements": 10}),
            ("ind_forge_scrap_iron_recycle_heap", "Rusted Scrap Iron & Broken Armor Barrel", "Thùng Sắt Vụn Chờ Nấu Lại", "废铁回收熔炼篓", [1, 1], "ground_contact", False, "transparent", "scavenge_iron", "Barrel filled with horse shoes, bent sword tips, and chain links.", True, "iron", "metal", "Wooden barrel overflowing with tangled rusted iron chain links, bent horseshoes, and dull knives.", "prop", "transparent", "bottom_center", {"scrap_yield": 15})
        ]),
        ("dye_vat_and_silk_rack", [
            ("ind_dye_indigo_dyeing_earthen_vats", "Cluster of Deep Indigo Blue Dye Vats", "Dãy Vại Gốm Nhuộm Chàm Xanh Thẫm", "深蓝染布大陶缸排", [2, 2], "solid", False, "transparent", "dye_cloth", "Four round ceramic vats filled with dark blue fermented indigo dye.", False, "ceramic", "water", "Cluster of four large round earthenware dye vats sunken into earth filled with frothy dark indigo blue liquid.", "structure", "transparent", "bottom_center", {"craft_dye": "indigo"}),
            ("ind_dye_high_bamboo_fabric_drying_tower", "Towering Timber Rack of Billowing Silk", "Giàn Phơi Vải Lụa Nhuộm Cao Ngất", "高架垂挂晾布架", [3, 3], "solid", True, "transparent", "admire_silk", "Tall scaffolding where 20-foot banners of dyed cloth billow.", True, "bamboo", "wind", "Tall bamboo scaffolding tower hung with long billowing vertical streamers of brilliant indigo, vermilion, and yellow dyed cloth.", "building", "transparent", "bottom_center", {"scenic": True}),
            ("ind_dye_sericulture_silkworm_hurdles", "Silkworm Rearing Trays Multi-Tier Rack", "Giá Nuôi Tằm Ăn Dâu Nhiều Tầng", "多层养蚕竹箅架", [2, 1], "ground_contact", False, "transparent", "feed_silkworms", "Shelved racks of round bamboo trays with mulberry leaves and worms.", True, "bamboo", "wood", "Tall wooden frame holding seven tiers of round woven bamboo trays covered in chopped green mulberry leaves.", "prop", "transparent", "bottom_center", {"sericulture": True}),
            ("ind_dye_silk_cocoon_boiling_caldron", "Silk Cocoon Boiling Pot & Reeling Wheel", "Nồi Luộc Kén Tằm & Bánh Xe Kéo Tơ", "缫丝煮茧铜锅台", [2, 1], "solid", False, "transparent", "reel_silk", "Bronze pot of steaming water with wooden hand reel spooling fine silk.", False, "wood", "water", "Clay hearth holding bronze basin of steaming water with floating white silk cocoons, wooden hand-cranked reeling spool.", "prop", "transparent", "bottom_center", {"silk_production": True}),
            ("ind_dye_wooden_loom_weaving_frame", "Traditional Wooden Shuttle Silk Loom", "Khung Cửi Gỗ Dệt Lụa Truyền Thống", "传统木质提花织布机", [2, 2], "solid", True, "transparent", "weave_silk", "Intricate timber loom frame with pedals, warp threads, and shuttle.", False, "wood", "mortal", "Intricate ancient Chinese wooden handloom frame with suspended heddles, spool shuttles, and half-woven floral silk.", "building", "transparent", "bottom_center", {"weaving_station": True}),
            ("ind_dye_mordant_alum_crystal_jars", "Alum & Potash Dye Mordant Clay Crocks", "Chum Phèn Chua & Tro Ngâm Nhuộm Màu", "定色明矾石灰坛", [1, 1], "ground_contact", False, "transparent", "take_alum", "Sealed crocks holding chemical fixatives for vibrant cloth.", True, "ceramic", "mortal", "Pair of wide clay jars with wooden scoops containing white crystalline alum and wood ash for fixing colors.", "prop", "transparent", "bottom_center", {"chemical_fixative": True}),
            ("ind_dye_beating_paddle_stone_fluting", "Cloth Calendering Stone & Wooden Beetle", "Đá Ép Bóng Vải & Chày Gỗ Nện Vải", "踹布石碾木槌", [1, 1], "solid", False, "transparent", "calender_cloth", "Boat-shaped heavy granite rock balanced on cloth with wooden stomper.", False, "stone", "mortal", "Heavy saddle-shaped granite calendering stone rock with wooden balance frame for polishing silk.", "prop", "transparent", "bottom_center", {"silk_finishing": True}),
            ("ind_dye_bolts_of_folded_silk_table", "Bolts of Vibrant Folded Silk Table", "Bàn Trưng Bày Cuộn Vải Lụa Nhiều Màu", "叠齐染色锦缎案", [2, 1], "solid", False, "transparent", "loot_silk", "Low table stacked with neat rolls of emerald, crimson, and gold silk.", True, "silk", "mortal", "Low wooden merchant table laden with neatly folded rectangular bolts of shimmering crimson, indigo, and saffron silk.", "prop", "transparent", "bottom_center", {"loot_silk_value": 300}),
            ("ind_dye_waste_rinse_drain_waterway", "Colorful Effluent Stone Rinse Canal", "Kênh Đá Xả Nước Nhuộm Nhiều Sắc", "染坊洗布水渠石桥", [3, 1], "walk_surface", False, "transparent", "rinse_cloth", "Stone-lined drainage channel with purple and blue dyed running water.", False, "stone", "water", "Stone-lined narrow water canal with vivid streaks of indigo and purple dye swirling past wooden washing platform.", "structure", "transparent", "bottom_center", {"colorful_water": True})
        ]),
        ("grain_threshing_floor", [
            ("ind_grain_round_beaten_clay_floor", "Circular Beaten Clay Threshing Floor", "Sân Phơi Thóc Bằng Đất Nện Phẳng Lì", "圆形硬实打谷场", [4, 4], "none", False, "transparent", "thresh_grain", "Large smooth circular earthen clearing bounded by low stone curbs.", False, "earth", "mortal", "Broad circular beaten-clay village threshing floor surrounded by golden grain chaff and smooth field boundary stones.", "structure", "transparent", "center", {"threshing_space": True}),
            ("ind_grain_stone_roller_ox_harness", "Heavy Cylindrical Granite Grain Roller", "Con Lăn Bằng Đá Kéo Bằng Trâu Đập Lúa", "碾谷圆柱大石磙", [2, 1], "solid", False, "transparent", "roll_grain", "Heavy fluted granite cylinder with wooden pulling yoke for ox.", False, "stone", "mortal", "Heavy cylindrical grey granite roller with wooden towing harness resting on sun-dried wheat chaff.", "prop", "transparent", "bottom_center", {"threshing_tool": True}),
            ("ind_grain_flail_wooden_jointed_beater", "Hinged Wooden Grain Threshing Flails", "Cây Đập Lúa Gỗ Khớp Nối Năng Suất", "连枷打谷农具", [1, 1], "ground_contact", False, "transparent", "pick_up", "Pair of jointed wooden beating rods on long swing handles.", True, "wood", "mortal", "Two jointed wooden grain flails with swiveling beaters resting against golden straw bale.", "prop", "transparent", "bottom_center", {"tool": "grain_flail"}),
            ("ind_grain_hand_winnowing_fan_machine", "Enclosed Wooden Winnowing Fan (Fengche)", "Cối Quạt Thóc Bằng Gỗ Quay Tay (Phong Xa)", "手摇木质风谷车", [2, 1], "solid", True, "transparent", "crank_fan", "Wooden box with internal blades separating chaff from heavy grain.", False, "wood", "wind", "Traditional Chinese wooden hand-cranked rotary winnowing machine (Fengche) with hopper and grain chute.", "prop", "transparent", "bottom_center", {"winnow_grain": True}),
            ("ind_grain_winnowing_bamboo_forks_sieves", "Bamboo Winnowing Shovels & Sieves", "Xẻng Tre & Mẹt Sàng Sảy Thóc", "扬场木锨竹筛簸箕", [1, 1], "ground_contact", False, "transparent", "winnow", "Wide flat wooden shovels used to throw grain up into wind.", True, "bamboo", "mortal", "Collection of wide wooden wind shovels, curved bamboo winnowing trays, and woven grain sieves.", "prop", "transparent", "bottom_center", {"tool": "winnowing_basket"}),
            ("ind_grain_giant_millet_chaff_mound", "Giant Pile of Winnowed Golden Chaff", "Đống Trấu Vàng Óng Cao Ngất", "金黄谷壳大草垛", [2, 2], "ground_contact", False, "transparent", "search_pile", "Huge soft mound of dusty yellow husks and fine grain dust.", True, "straw", "mortal", "Large soft dome mound of golden yellow winnowed rice chaff and grain husks with wooden rake stuck in top.", "prop", "transparent", "bottom_center", {"hideout": "soft_straw"}),
            ("ind_grain_straw_rope_twisting_bench", "Hemp & Straw Rope Twisting Treadle", "Ghế Xoắn Dây Thừng Bằng Rơm Rạ", "编麻搓草绳长凳", [1, 1], "ground_contact", False, "transparent", "twist_rope", "Low wooden bench with rotating hooks for braiding tough straw cord.", False, "wood", "mortal", "Low wooden bench with rotating iron hooks and guide comb for twisting straw into heavy cordage.", "prop", "transparent", "bottom_center", {"craft_rope": True}),
            ("ind_grain_measuring_bushel_baskets", "Woven Willow Grain Measuring Bushels", "Bồ Đựng Thóc Đan Bằng Liễu", "盛粮柳条大粮筐", [1, 1], "ground_contact", False, "transparent", "take_grain", "Tall woven wicker baskets brimming with golden harvested wheat.", True, "bamboo", "mortal", "Three large woven cylindrical willow baskets brimming with golden unhusked grain on straw mat.", "prop", "transparent", "bottom_center", {"grain_loot": 50})
        ])
    ]
    for sub_name, items in c8_subs:
        for item in items:
            all_new.append(make_asset("trade_craft_industry", *item))

    # --------------------------------------------------------------------------
    # CATEGORY 9: OUTLAW & JIANGHU (50 assets)
    # sub_categories: bandit_stockade_palisade (9), skull_boundary_pole (8), wilderness_tavern_black_inn (9), secret_tunnel_trapdoor (8), escort_caravan_wagon (8), underworld_gambling_den (8)
    # --------------------------------------------------------------------------
    c9_subs = [
        ("bandit_stockade_palisade", [
            ("outlaw_palisade_spiked_log_wall", "Mountain Bandit Spiked Log Palisade", "Tường Hàng Rào Gỗ Cọc Nhọn Sơn Tặc", "山寨尖木排栅", [3, 2], "solid", True, "solid", None, "Rough-hewn tree trunks lashed with iron spikes barring mountain path.", True, "wood", "mortal", "Rough mountain bandit fort palisade wall made of unstripped pine logs with sharpened tops bound with hemp.", "structure", "transparent", "bottom_center", {"bandit_defense": 80}),
            ("outlaw_palisade_crude_timber_gate", "Fortified Mountain Stockade Double Gate", "Cổng Trại Sơn Tặc Gỗ Dày Khóa Xích", "山寨重木吊门", [3, 2], "solid", True, "solid", "smash_gate", "Heavy cross-braced timber gate reinforced with animal skulls.", True, "wood", "mortal", "Crude heavy wooden stockade gate with bone ornaments, crossbeams, and dangling warning ropes.", "structure", "transparent", "bottom_center", {"gate_health": 800}),
            ("outlaw_palisade_rustic_watchtower_spire", "Treestump Sniper Watchtower Platform", "Chòi Gác Gỗ Cây Rừng Của Thổ Phỉ", "山林土匪了望木台", [2, 2], "core_ring", True, "transparent", "climb_tower", "Tower on four tree trunks with archer roof and signal horn.", False, "wood", "mortal", "Rustic high wooden watchtower built on four sturdy tree trunks with rough timber ladder and thatched roof.", "building", "transparent", "bottom_center", {"sniper_post": True}),
            ("outlaw_palisade_spiked_log_drop_trap", "Deadfall Log Trap Suspended by Ropes", "Bẫy Gỗ Lăn Khổng Lồ Treo Trên Dốc", "山道滚木陷阱架", [2, 2], "solid", True, "transparent", "trigger_deadfall", "Heavy bundle of sharpened logs rigged to roll down hillside.", True, "wood", "mortal", "Overhead wooden scaffold holding a bundle of five massive sharpened logs tied with a trip rope.", "structure", "transparent", "bottom_center", {"trap_damage": 600}),
            ("outlaw_palisade_iron_bear_claw_snare", "Concealed Large Iron Game & Man Trap", "Bẫy Kẹp Chân Sắt Cỡ Lớn Giấu Dưới Lá", "生铁捕兽大夹齿", [1, 1], "none", False, "transparent", "disarm", "Toothed iron jaw spring trap hidden among dead leaves.", True, "iron", "mortal", "Serrated circular iron spring trap anchored by chain to stake, hidden under scatter of dead forest leaves.", "prop", "transparent", "center", {"immobilize_time": 5.0}),
            ("outlaw_palisade_campfire_roasting_spit", "Bandit Campfire with Whole Boar on Spit", "Bếp Lửa Trại Nướng Nguyên Con Heo Rừng", "山寨野味烤乳猪架", [2, 1], "ground_contact", False, "transparent", "eat_meat", "Stone firepit with whole wild boar turning over glowing coals.", False, "wood", "fire", "Large stone fire ring with crackling logs, iron roasting spit holding whole roasted wild boar.", "prop", "transparent", "bottom_center", {"food_buff": 100}),
            ("outlaw_palisade_looted_goods_hoard_pile", "Looted Caravan Cargo & Strongbox Pile", "Đống Cướp Bóc Hòm Xiểng Lụa Là Của Sơn Tặc", "抢劫辎重宝箱堆", [2, 1], "solid", True, "solid", "loot_treasure", "Disorderly mound of robbed trade chests, silks, and wine jugs.", False, "wood", "mortal", "Disorderly mound of ransacked trade chests, spilled bronze coins, broken jade ornaments, and kegs of wine.", "prop", "transparent", "bottom_center", {"gold_loot": 500}),
            ("outlaw_palisade_training_weapon_rack", "Bandit Ragged Weapon Rack & Cleavers", "Giá Vũ Khí Mã Tấu Lưỡi Búa Của Sơn Tặc", "土匪破旧兵刃架", [1, 1], "ground_contact", False, "transparent", "take_cleaver", "Weapon stand filled with heavy chopping sabers and wolf tooth clubs.", True, "wood", "mortal", "Crude wooden weapon rack holding spiked wolf-tooth maces, heavy butcher cleavers, and rusted spears.", "prop", "transparent", "bottom_center", {"weapon": "wolf_mace"}),
            ("outlaw_palisade_prisoner_cage_bamboo", "Hanging Bamboo Prisoner Suspension Cage", "Lồng Tre Nhốt Con Gái Con Tin Treo Cành Cây", "悬空吊装竹囚笼", [1, 2], "ground_contact", False, "transparent", "free_hostage", "Cylindrical bamboo cage suspended from gallows branch.", True, "bamboo", "mortal", "Cylindrical woven bamboo cage hanging from thick wooden gallows beam holding hostage or skeleton.", "structure", "transparent", "bottom_center", {"hostage_rescue": True})
        ]),
        ("skull_boundary_pole", [
            ("outlaw_skull_territory_marking_totem", "Bleached Skulls Boundary Warning Pole", "Cột Gỗ Cắm Đầu Lâu Cảnh Báo Sơn Phỉ", "骷髅示警界桩木", [1, 2], "ground_contact", False, "transparent", "examine", "Tall notched tree trunk topped with multiple human skulls.", False, "bone", "mortal", "Tall rough wooden marker totem pole crowned with three weathered human skulls and black raven feathers.", "prop", "transparent", "bottom_center", {"intimidation": 40}),
            ("outlaw_skull_severed_heads_gallows_beam", "Iron Hook Gallows with Severed Heads", "Khung Gỗ Treo Thủ Cấp Bị Chém", "挂首示众木桁", [2, 2], "solid", True, "transparent", "inspect", "Overhead crossbeam with dangling iron meat hooks and cages.", True, "wood", "mortal", "Rough wooden crossbeam scaffold with rusted iron chains hanging iron gibbet cages and dried bones.", "structure", "transparent", "bottom_center", {"dread_aura": True}),
            ("outlaw_skull_impaled_bandit_spear_marker", "Crossed Spears with Straw Warning Effigy", "Cặp Giáo Cắm Chéo Buộc Hình Nộm Cảnh Báo", "十字插矛草人示界", [1, 1], "ground_contact", False, "transparent", None, "Two spears driven into earth holding straw effigy and warning blood text.", True, "wood", "mortal", "Two crossed iron spears driven into mound holding straw man effigy painted with blood characters.", "prop", "transparent", "bottom_center", {"warning_sign": True}),
            ("outlaw_skull_cairn_piled_stone_boundary", "Crude Stone Cairn with Red Threat Characters", "Gò Đá Sơn Tặc Vẽ Chữ Máu Cấm Vào", "血字堆石断道标", [1, 1], "solid", False, "transparent", "read_blood_script", "Pyramid of river boulders splashed with red cinnabar warning.", False, "stone", "mortal", "Pyramid stone cairn of jagged rocks marked with dripping red painted ideograms: Enter and Die.", "prop", "transparent", "bottom_center", {"lore": "bandit_threat"}),
            ("outlaw_skull_animal_horns_gateway_arch", "Stag & Buffalo Antler Boundary Arch", "Cổng Vòm Sừng Trâu Sừng Hươu Của Sơn Trại", "水牛鹿角野性木门", [3, 2], "core_ring", True, "solid", "pass_under", "Crude wooden archway decorated with massive water buffalo horns.", False, "wood", "bone", "Low rustic timber boundary archway mounted with massive curved water buffalo horns and wolf pelts.", "building", "transparent", "bottom_center", {"camp_gateway": True}),
            ("outlaw_skull_hanging_bone_chime_strings", "Wind Chime of Bleached Finger Bones", "Dây Chuông Xương Treo Lắc Lư Kêu Lách Cách", "风吹白骨骨串铃", [1, 1], "none", False, "transparent", "touch", "Strings of hollow bones dangling from tree branch clattering in breeze.", True, "bone", "mortal", "Strands of bleached animal rib bones and iron bells hung from branch clattering ominously in wind.", "prop", "transparent", "center", {"eerie_sound": True}),
            ("outlaw_skull_flayed_wolf_pelt_standard", "Flayed Timber Wolf Skin Banner", "Cột Cờ Da Chó Sói Rừng Nanh Vuốt", "整张剥皮恶狼战旗", [1, 2], "ground_contact", False, "transparent", None, "Full wolf pelt complete with snarling head mounted on pike.", True, "leather", "mortal", "High wooden spear pole displaying full grey timber wolf pelt with bared fangs flapping in wind.", "prop", "transparent", "bottom_center", {"bandit_banner": True}),
            ("outlaw_skull_blood_stained_roadside_boulder", "Roadside Ambush Boulder with Blood Splatter", "Tảng Đá Ven Đường Vấy Máu Tươi Phục Kích", "沾血伏击路边巨石", [2, 1], "solid", True, "solid", "inspect_blood", "Large granite rock used as ambush blind with dried blood stains.", False, "stone", "mortal", "Weathered granite boulder beside road track marked with dark oxidized blood stains from highway ambush.", "prop", "transparent", "bottom_center", {"ambush_cover": True})
        ]),
        ("wilderness_tavern_black_inn", [
            ("outlaw_inn_dragon_gate_isolated_rampart", "Isolated Wilderness Black Tavern (Hei Dian)", "Hắc Điếm Quán Trọ Vùng Hoang Dã", "荒野黑店龙门客栈", [4, 3], "solid", True, "solid", "enter_inn", "Two-story fortified rammed-earth inn with shuttered windows.", False, "wood", "mortal", "Two-story fortified wilderness inn of rammed earth and weathered timber, wine flag fluttering, iron-barred shutters.", "building", "transparent", "bottom_center", {"secret_black_market": True}),
            ("outlaw_inn_meat_chopping_butcher_block", "Tavern Kitchen Human-Cleaver Chopping Block", "Bàn Thớt Chặt Thịt Nhà Bếp Hắc Điếm", "黑店庖厨斩肉大台", [1, 1], "solid", False, "transparent", "inspect_meat", "Heavy wooden meat block with suspicious cleavers and bone hooks.", True, "wood", "mortal", "Grim kitchen butcher block with deep cleaver gouges, meat hooks, and pottery bowls of mystery mince.", "prop", "transparent", "bottom_center", {"sinister_secret": True}),
            ("outlaw_inn_drugged_wine_jars_cluster", "Sealed Jars of Drugged 'Mugwort' Wine", "Hũ Rượu Bỏ Thuốc Mê Mông Hãn Dược", "蒙汗药毒酒大陶坛", [1, 1], "ground_contact", False, "transparent", "drink_drugged_wine", "Sealed ceramic jars containing potent sleeping powders.", True, "ceramic", "mortal", "Three red-sealed earthenware wine jugs marked with small secret scratch indicating sleep poison.", "prop", "transparent", "bottom_center", {"poison_potency": 0.9}),
            ("outlaw_inn_backroom_gambling_table", "Backroom Mahjong & Dice Gambling Table", "Bàn Đổ Bác Lắc Xúc Xắc Gian Phòng Sau", "密室博戏骰子木桌", [2, 1], "solid", False, "transparent", "play_dice", "Square wooden table with ivory dice, copper cup, and silver piles.", False, "wood", "mortal", "Low square wooden gambling table with bone dice, leather shaker cup, and scattered silver ingots.", "prop", "transparent", "bottom_center", {"gambling_minigame": True}),
            ("outlaw_inn_bamboo_screen_hiding_closet", "Woven Reed Screen Concealing Peep Hole", "Bức Mành Tre Che Giấu Lỗ Nhìn Lén", "窥孔竹编遮风屏", [1, 1], "ground_contact", False, "transparent", "peer_through", "Folding screen concealing wall peepholes into guest rooms.", True, "bamboo", "mortal", "Three-fold painted bamboo screen concealing secret wall viewing peepholes into guest bedrooms.", "prop", "transparent", "bottom_center", {"spy_hole": True}),
            ("outlaw_inn_hidden_trapdoor_cellar_stair", "Kitchen Trapdoor to Secret Cellar", "Cửa Sập Xuống Hầm Ngầm Dưới Bếp", "厨房暗门地窖口", [1, 1], "none", False, "transparent", "open_trapdoor", "Hinged wooden trapdoor flush with stone floor leading down.", False, "wood", "mortal", "Square wooden cellar hatch trapdoor set into flagstone floor with iron ring handle.", "structure", "transparent", "center", {"cellar_door": True}),
            ("outlaw_inn_hanging_ragged_wine_flag", "Tattered 'Fine Wine' Wind Flag Banner", "Cờ Hiệu Rượu Rách Nát Bay Trong Gió", "破烂褪色酒字旗", [1, 2], "ground_contact", False, "transparent", None, "Tattered hemp flag with single black character 'Jiu' (Wine).", True, "fabric", "wind", "Tall bamboo pole with ragged faded indigo cloth flag painted with single black character 'Wine'.", "prop", "transparent", "bottom_center", {"signpost": "inn"}),
            ("outlaw_inn_stabling_stalls_robbed_horses", "Dark Stables for Travelers Stolen Mounts", "Chuồng Ngựa Tối Nhốt Ngựa Bị Cướp", "藏匿良驹暗马厩", [3, 2], "solid", True, "transparent", "inspect_mounts", "Secluded covered shed where stolen horses have brands altered.", False, "wood", "mortal", "Dark covered timber stable stalls with hay bedding and iron branding irons for altering horse marks.", "building", "transparent", "bottom_center", {"stolen_horses": True}),
            ("outlaw_inn_dry_water_well_hideaway", "Deceptive Dry Well Hiding Loot & Bodies", "Giếng Cạn Giấu Xác & Hòm Báu", "枯井暗藏秘窟", [1, 1], "solid", False, "transparent", "climb_down", "Stone wellhead concealing ladder into underground cavern.", False, "stone", "mortal", "Weathered stone wellhead with fake wooden windlass concealing dry shaft with rope ladder descending.", "prop", "transparent", "bottom_center", {"secret_entrance": True})
        ]),
        ("secret_tunnel_trapdoor", [
            ("outlaw_tunnel_hollow_boulder_door", "Counterweighted Hollow Stone Cave Entry", "Tảng Đá Giả Mở Lối Vào Hầm Bí Mật", "机关假山石暗门", [2, 2], "solid", True, "solid", "push_rock", "Massive natural boulder pivoting on iron axle to reveal tunnel.", False, "stone", "mortal", "Massive natural granite boulder resting against hillside that swings outward to reveal dark tunnel.", "building", "transparent", "bottom_center", {"hidden_door": True}),
            ("outlaw_tunnel_rotted_tree_stump_opening", "Hollow Ancient Tree Stump Tunnel Descent", "Gốc Cây Cổ Thụ Rỗng Lòng Chui Xuống Hầm", "空心树桩暗道口", [2, 2], "solid", True, "transparent", "crawl_inside", "Ancient gnarled oak with hollow trunk concealing iron ladder.", True, "wood", "mortal", "Massive hollowed-out ancient oak tree stump with mossy roots concealing vertical tunnel shaft.", "structure", "transparent", "bottom_center", {"concealed_exit": True}),
            ("outlaw_tunnel_underground_torch_sconce", "Smoky Iron Wall Torch Sconce in Tunnel", "Đuốc Sắt Cắm Vách Hầm Bốc Khói", "地道石壁铁油炬", [1, 1], "ground_contact", False, "transparent", "take_torch", "Iron bracket holding burning pitch torch illuminating masonry.", False, "iron", "fire", "Forged iron wall sconce mounted on rough cave wall holding blazing tar torch and smoke stain.", "prop", "transparent", "bottom_center", {"tunnel_light": 15.0}),
            ("outlaw_tunnel_cave_in_rubble_barrier", "Collapsed Tunnel Ceiling Rockfall Rubble", "Đoạn Hầm Sụp Đổ Đá Đè Bít Lối", "塌方碎石封路堆", [2, 1], "solid", True, "solid", "clear_rubble", "Tumbled ceiling boulders and shattered support timbers.", False, "stone", "mortal", "Pile of tumbled ceiling rock boulders and cracked timber shoring beams blocking underground passage.", "structure", "transparent", "bottom_center", {"dig_excavate": True}),
            ("outlaw_tunnel_underground_smugglers_cache", "Subterranean Sealed Salt & Silk Cache", "Kho Giấu Muối & Lụa Ngầm Dưới Đất", "暗道私盐藏匿点", [2, 1], "solid", True, "solid", "loot_cache", "Underground dry chamber stacked with illegal salt bags.", False, "wood", "mortal", "Underground rock niche stacked with waterproof waxed bags of illicit salt and bolts of silk.", "prop", "transparent", "bottom_center", {"contraband_yield": 400}),
            ("outlaw_tunnel_wooden_shoring_tunnel_arch", "Heavy Timber Mine Shoring Support Arch", "Khung Gỗ Chống Đỡ Hầm Mỏ Tránh Sập", "地道支护木柱排", [2, 1], "solid", True, "solid", "pass_under", "Square timber post-and-beam frame keeping earth from caving.", False, "wood", "mortal", "Stout square oak post-and-lintel tunnel support arch shoring up cracked stone ceiling.", "structure", "transparent", "bottom_center", {"structural_support": True}),
            ("outlaw_tunnel_iron_spiked_floor_pit", "Underground False-Floor Pit Trap", "Hầm Chông Sắt Đáy Sâu Bẫy Sập", "翻板落坑铁刺陷阱", [1, 1], "none", False, "transparent", "disarm_trap", "Pivoting floor slab dropping unsuspecting intruders onto spikes.", True, "iron", "mortal", "Concealed pivoting flagstone floor hatch revealing deep pit of rusty iron spikes below.", "prop", "transparent", "center", {"fatal_trap": True}),
            ("outlaw_tunnel_water_sump_drainage_culvert", "Subterranean Muddy Drainage Sump & Grate", "Hố Thu Nước Ngầm Song Sắt Trong Hang", "地道集水暗渠格栅", [1, 1], "none", False, "transparent", "wade", "Low muddy culvert channel draining seepage out of tunnel.", False, "stone", "water", "Low arched masonry water drain channel with rusty iron bar grate and muddy seepage water.", "structure", "transparent", "bottom_center", {"drainage_route": True})
        ]),
        ("escort_caravan_wagon", [
            ("outlaw_escort_biaoju_four_wheel_wagon", "Armed Escort Agency Armored Freight Wagon", "Tiêu Xa Bốn Bánh Tiêu Cục Áp Tải", "威武镖局重装大车", [3, 2], "solid", True, "solid", "inspect_cargo", "Heavy four-wheel baggage wagon with flying Biaoju triangle pennant.", False, "wood", "mortal", "Heavy four-wheeled iron-reinforced freight wagon carrying locked chests, flying yellow 'Zhen Yuan' escort flag.", "building", "transparent", "bottom_center", {"caravan_defense": 100}),
            ("outlaw_escort_caravan_flag_triangle", "Official Martial Escort Triangular Guidon", "Tiêu Kỳ Tam Giác Vàng Của Tiêu Cục", "金字镖局三角旗", [1, 1], "ground_contact", False, "transparent", "admire_flag", "Triangular swallowtail pennant bearing martial agency surname.", False, "silk", "mortal", "Small wooden staff bearing a triangular yellow silk escort flag with black embroidered character 'Biao'.", "prop", "transparent", "bottom_center", {"escort_reputation": 50}),
            ("outlaw_escort_heavy_iron_treasure_trunk", "Triple-Locked Iron Paymaster Chest", "Rương Sắt Khóa Ba Ổ Cực Nặng", "三簧重铁押运箱", [1, 1], "solid", True, "solid", "lockpick", "Solid iron safe with three complex brass padlock keys.", False, "iron", "mortal", "Solid cast iron security chest reinforced with diagonal straps and three heavy brass sliding locks.", "prop", "transparent", "bottom_center", {"safe_gold": 1000}),
            ("outlaw_escort_rest_circle_wagon_fort", "Encircled Caravan Night Defense Camp", "Vòng Tròn Tiêu Xa Kết Thành Phòng Tuyến", "结营抵御大车圆阵", [4, 4], "solid", True, "solid", "enter_fort", "Three wagons pushed together forming barricade around campfire.", False, "wood", "mortal", "Circular defensive wagon fort formed by three interlocked transport wagons surrounding a small watchfire.", "structure", "transparent", "bottom_center", {"defensive_camp": True}),
            ("outlaw_escort_guard_sleeping_bedroll_tent", "Escort Guard Folding Cot & Leather Tent", "Lều Bạt & Giường Xếp Của Tiêu Sư", "行镖武师折叠营帐", [2, 2], "core_ring", True, "solid", "rest", "Low oilskin shelter with leather scabbards and travel boots.", False, "leather", "mortal", "Low leather traveling shelter tent with wool bedroll, water gourd, and sheathed saber outside.", "building", "transparent", "bottom_center", {"guard_rest": True}),
            ("outlaw_escort_horse_feed_folding_troughs", "Portable Canvas Mount Feeding Trough", "Máng Vải Gấp Cho Ngựa Ăn Dọc Đường", "帆布折叠喂马槽", [1, 1], "ground_contact", False, "transparent", "feed_horses", "Folding canvas and wood trough for grain on long highways.", True, "canvas", "mortal", "Collapsible folding canvas water and grain trough suspended between four wooden stakes.", "prop", "transparent", "bottom_center", {"horse_care": True}),
            ("outlaw_escort_broken_axle_repaired_jack", "Wagon Jack Prop Supporting Broken Axle", "Kích Gỗ Nâng Xe Bị Gãy Trục Ven Đường", "木千斤顶支车架", [2, 1], "solid", False, "transparent", "repair_wagon", "Heavy timber screw jack lifting wagon while wheel replaced.", True, "wood", "mortal", "Heavy wooden screw jack lever supporting the tilted rear of a supply cart with wheel detached.", "prop", "transparent", "bottom_center", {"repair_task": True}),
            ("outlaw_escort_bell_alert_trip_wire", "Caravan Perimeter Alarm Chime Strings", "Dây Giăng Chuông Báo Động Ban Đêm", "夜宿护营铜铃绳", [2, 1], "none", False, "transparent", "disarm", "Thin cords surrounding night camp hung with small bells.", True, "bronze", "mortal", "Thin hemp perimeter twine strung between low pegs around camp hung with six small brass alarm bells.", "prop", "transparent", "center", {"ambush_alert": True})
        ]),
        ("underworld_gambling_den", [
            ("outlaw_den_underground_casino_hall", "Secret Jianghu Dice & Pai Gow Saloon", "Sòng Bạc Bí Mật Trong Lòng Đất", "地下快活林赌场", [4, 3], "solid", True, "solid", "doorway", "Sprawling basement hall with smoky lamps, tables, and guards.", False, "brick", "mortal", "Dim subterranean underworld gambling hall with smoky red lanterns, felt tables, and cash counter.", "building", "transparent", "bottom_center", {"gambling_palace": True}),
            ("outlaw_den_paigow_bone_dominoes_table", "Pai Gow Bone Dominoes Table & Counters", "Bàn Đánh Bài Cẩu Bằng Xương Đen", "骨牌牌九圆毡桌", [2, 1], "solid", False, "transparent", "play_paigow", "Green felt table with 32 black bone domino tiles and chips.", False, "wood", "mortal", "Round wooden gaming table with green felt cloth, black bone Pai Gow tiles, and wooden counter chips.", "prop", "transparent", "bottom_center", {"game": "pai_gow"}),
            ("outlaw_den_money_changer_high_cage", "Iron-Barred Money Exchange Cashier Cage", "Lồng Sắt Đổi Tiền & Vàng Bạc", "兑银铁栅高账台", [2, 1], "solid", True, "solid", "exchange_silver", "High fortified counter with iron bars protecting money stacks.", False, "iron", "mortal", "High wooden cashier counter enclosed by thick iron bars with brass weighing scales and silver ingots.", "building", "transparent", "bottom_center", {"currency_exchange": True}),
            ("outlaw_den_heavy_bouncers_wooden_bench", "Enforcer Bouncers Bench & Cudgels", "Ghế Dài Tay Sai Đao Búa Canh Giữ Sòng Bạc", "护庄打手长条凳", [2, 1], "solid", False, "transparent", "sit", "Long rough bench where hired muscle drink wine with clubs.", False, "wood", "mortal", "Stout wooden tavern bench with leather blackjack saps, iron-banded clubs, and spilled liquor jugs.", "prop", "transparent", "bottom_center", {"enforcers": 4}),
            ("outlaw_den_opium_and_tobacco_divan", "Plush Daybed with Smoking Waterpipe", "Giường Nằm Hút Thuốc Bằng Tre Êm Ái", "软榻水烟竹榻", [2, 1], "solid", False, "transparent", "smoke_pipe", "Low wooden divan with silk pillows and carved brass waterpipe.", False, "wood", "mortal", "Low carved wooden lounger divan with silk cushions, brass waterpipe, and small charcoal burner.", "prop", "transparent", "bottom_center", {"relaxation": True}),
            ("outlaw_den_hidden_exit_wine_barrel_door", "False Giant Wine Vat Tunnel Doorway", "Thùng Rượu Giả Làm Cửa Thoát Hiểm", "假大酒缸遁身门", [1, 1], "solid", True, "solid", "escape_tunnel", "Hollow wooden vat with pivoting back into drainage ditch.", False, "wood", "mortal", "Giant upright wooden wine barrel with false hinged back opening into secret dark exit tunnel.", "structure", "transparent", "bottom_center", {"emergency_exit": True}),
            ("outlaw_den_debtors_iron_holding_cell", "Gamblers Unpaid Debt Iron Cell", "Song Sắt Nhốt Con Nợ Không Trả Tiền", "拘禁赌债小铁牢", [2, 1], "solid", True, "solid", "free_debtor", "Small iron cage where ruined gamblers wait for ransom.", False, "iron", "mortal", "Grim narrow iron-bar holding cell in corner with straw mat, holding chained desperate debtors.", "structure", "transparent", "bottom_center", {"rescue_mission": True}),
            ("outlaw_den_blood_contract_desk", "Usury High-Interest Blood Contract Desk", "Bàn Ký Giấy Nợ Vay Nặng Lãi Điểm Chỉ", "高利九出十三归案", [1, 1], "ground_contact", False, "transparent", "sign_loan", "Small ledger desk with red inkpads and indentured servant papers.", False, "wood", "mortal", "Dark wood writing table with inkstone, indentured labor contracts, and red fingerprint seals.", "prop", "transparent", "bottom_center", {"loan_shark": True})
        ])
    ]
    for sub_name, items in c9_subs:
        for item in items:
            all_new.append(make_asset("outlaw_and_jianghu", *item))

    return all_new

if __name__ == "__main__":
    new_assets = generate_all_remaining()
    print(f"Generated {len(new_assets)} assets for Categories 7, 8, 9.")
