$title = "DESIGN QUESTION (human must rule): 2428 items claim a forager that does not exist - what is a `gather` supposed to MEAN, and may it be anything other than a forager module?"

$reason = @'
DEF-0169 records that gather is a MISSING SUBSYSTEM and hands a 3-step plan; this entry adds the question DEF-0169 does not ask, plus a corrected lever arithmetic that inverts its execution order. MEASURED (my own run, tools/data.py loaders, scratchpad/edges.txt): 7982 items, 1553 deliverable, 6429 blocked, signatures gather|quest 4150 / quest 1392 / gather 821 / unattributed 66. LEVER SIZES, both re-measured from scratch and both LARGER than the inherited figures: quest alone moves 1553 -> 7078 (+5525), gather alone moves 1553 -> 6591 (+5038), both -> 7981 (+6428; one item left, curr_spirit_coin, which declares no source at all). So quest is the BIGGER prize, not the cheaper half, and +1392 is only the quest-ONLY signature class, not the quest lever's edge: 3029 blocked items declare quest directly and the recipe closure carries the rest. THE UNRESOLVED QUESTION: holdings cannot be the forager - that is an ACCEPTED constraint, not a guess (BL-0191 status done; ADR 0097:59-65 "A node pays a ledger line, never items"; resource_node_def.gd:15-19; holdings/api.gd:21-24), pinned by two tests that state their own removal condition (tests/modules/holdings/test_holdings_yields_units_not_items.gd:26-32 and :218-231 forbid holdings/api.gd naming ItemsApi; tests/modules/quest/test_quest_cannot_deliver_an_item.gd:160-188 pins no_inventory_dependency). So a forager MUST be a new module. But nothing says what it may do, and the corpus does not agree with itself: of the 2428 gather items, 1174 are recipe inputs (forage as supply) and 373 are ALSO recipe outputs (forage duplicating craft), while the category census is material 1432 / consumable 268 / equipment 233 / technique 213 / misc 74 / currency 71 / key 70 / quest 67 - i.e. 487 of them are legendary equipment, techniques, CURRENCY and KEYS, which a forage action does not obviously hand out. The fiction cannot be read from the data either: ItemDef.description exists (item_def.gd:18) and is authored EMPTY on 0-of-7982 items, so no prose says a player picks these up. Also DEF-0174 is STALE: BeatDirector IS constructed at app/item_workbench_app.gd:77 and its QuestBeatHandler sink IS registered at app/world_pulse.gd:154, so the quest plumbing is more complete than DEF-0169 assumes and the quest option is cheaper than it looks.
'@

$next = @'
Rule on the MEANING before anyone builds, because all four options cost real work and the meaning decides which is cheap: (a) FORAGE AS SUPPLY - a new forager module that yields only the 1174 recipe-input materials from placed nodes, leaving ~1250 non-input gather claims still unshipped; (b) FORAGE AS LOOT - a forager whose yield table is authored per node, which requires authoring node content (game/data/holdings/nodes/ does not exist) and deciding what a node may yield, since a node type carrying an item id is exactly what the holdings test forbids and a forager needs its OWN node type; (c) LET QUEST ABSORB THEM - strip gather from every item that also declares quest (4150 items) and author real QuestDefs, since quest is the bigger edge (+5525) and the quest module already ships; (d) RETIRE THE CLAIMS - delete or rewrite the gather source from the items no option above reaches. Whatever is chosen, the audit's numbers must move with it: flip KIND_GATHER shipped:false->true in item_sources.gd:89 AND add the matching RUNTIME_ROUTES entry in tools/data.py:246 in the SAME change, or _route_agreement_problems at tools/data.py:1089 fails. First concrete step for (b): author three node records under the NEW module's own data dir carrying the item ids they yield, and show one item actually arriving before the route is declared - the order named at tests/modules/holdings/test_holdings_yields_units_not_items.gd:26-32.
'@

$source = "acquisition decision brief 2026-10-03, measured with tools data audit + tools data report + independent re-measurement (scratchpad/probe_edges.py)"

uv run python -m tools deferred add --area "items" --title $title --source $source --reason $reason --next $next
Write-Output "exit=$LASTEXITCODE"
