extends TestCase

## DEF-0084: the three cultivation realm seeds are generated by
## `tools/cultivation/seed.py` (body) and `tools/cultivation/seed_systems.py`
## (qi, mind), but both generators skip files that already exist. That let the
## authored `.tres` seeds drift silently from the code that claims to define
## them, so a fresh checkout that regenerated a seed produced different numbers
## and changed every per-realm step ratio.
##
## The authored data is the shipped balance: 18,000+ tests pass against it. So
## the DATA is truth and this suite pins the generator formulas to it. Each
## `_*_generator` function below is a transcription of the Python generator's
## expression, and each test asserts it still equals the value loaded from the
## shipped `.tres` at every one of the 30 realms. If a generator expression
## changes, these fail; if a shipped seed changes, they fail too.
##
## The step-ratio tests at the bottom pin the numbers the technique system's
## cost ladder (ADR 0055) is sized against, which is why the drift mattered.
##
## DEF-0130: the body ladder was deliberately retuned (HEAD -> working tree) to
## `tools/cultivation/ladder.py`, which fixes DEF-0079 (five realms had
## `chance_base >= chance_cap`, so huyệt quality could not enter the roll) and
## DEF-0104 (26 of 30 realms gated on a physique floor the ladder already
## granted). Three of the identities this file pinned did not survive it, and
## each is handled below on its own merits rather than re-pinned wholesale:
##   - `work_required`/`acupoint_work`/`meridian_work` are now DERIVED in
##     `BodyRealmSeed` from `progress_required`, so nothing was lost; the derived
##     values are asserted here instead.
##   - The body's own labour ladder is UNCHANGED. Only its sub-budgets were
##     removed, and they were byte-identical copies of `progress_required` cut
##     against a count that is also derived. The +2 R1->R2 step assertion still
##     holds and still encodes a real invariant.
##   - `body.physique_required == qi.comprehension_required` is GONE, and that
##     one is gone on purpose. See `test_body_physique_required_clears_the_...`
##     for why the coupling was never a balance rule and why keeping it would
##     have re-broken DEF-0104.
##   - `body.insight_required == mind.comprehension_required` is GONE for the
##     same reason. The mind gate moved onto the actor power ladder
##     (`core/mind_comprehension_scale.gd`), so the two numbers now answer
##     different questions; see `test_body_insight_required_still_matches_its_own_ladder`.
##
## The mind comprehension gate is the one case where the SSOT is NOT a Python
## expression any more. It was `10 + 6i + 2i^2` in the ladder ORDINAL — a private
## quadratic disagreeing with `core/realm_power_table.tres` (1.00 -> 551.46) by up
## to 22.2x, i.e. a second power curve for a binding entry gate (the ADR 0116 shape).
## `MindComprehensionScale.required(realm_id)` is now the ladder answer and these
## tests delegate to it. `tools/cultivation/seed_systems.py:124` still carries the
## quadratic; it skips existing files, so it cannot rewrite a shipped seed, and it
## belongs to another live session. Tracked in `docs/deferred.jsonl`.

## The authored body labour budget, in labour units per realm (R1..R30).
## Read from the shipped seeds, not from `P**0.55`: the power table tops out at
## 551.46x while these numbers imply a 4328.76x ladder, and no single exponent
## against the power table reproduces more than 3 of the 30. See
## `BODY_WORK_REQUIRED` in tools/cultivation/seed.py.
const BODY_WORK_REQUIRED := [
	40,
	42,
	44,
	47,
	51,
	55,
	60,
	66,
	73,
	82,
	92,
	105,
	120,
	138,
	161,
	188,
	222,
	265,
	318,
	385,
	469,
	577,
	714,
	892,
	1123,
	1425,
	1823,
	2350,
	3054,
	4000,
]

## The qi `progress_required` step at R29->R30, measured from the shipped seeds:
## 2900 / 2800 = 1.0357142857142858. DEF-0083 and ADR 0055 quote it truncated to
## six decimals as 1.035714 and use that as the floor for the technique
## learning-cost ladder: a technique step may be this tight or looser, but never
## tighter than the qi work budget it is paid out of.
const QI_R29_R30_STEP := 2900.0 / 2800.0
const ADR_0055_QI_STEP_FLOOR := 1.035714
const STEP_RATIO_EPSILON := 0.0000001

## `BodyProgress.MILESTONE_PHYSIQUE_RATIO`: base physique granted per completed
## realm milestone, as a fraction of that realm's `integrity_maximum`. READ by
## `ladder.py`, transcribed here: the floor is priced against it, so a change to
## the runtime constant moves the authored floors with it.
const MILESTONE_PHYSIQUE_RATIO := 0.02

## ladder.PHYSIQUE_REWARD: base physique the ladder grants for clearing a realm.
const PHYSIQUE_REWARD := 2.0

## ladder.QUALITY_CEILING_BASE / QUALITY_STEP: the huyệt quality ceiling.
const QUALITY_CEILING_BASE := 0.62
const QUALITY_STEP := 0.0105

## ladder.QUALITY_HEADROOM: how far the entry gate sits BELOW the ceiling.
const QUALITY_HEADROOM := 0.08

## ladder.INTEGRITY_GAP: reservoir charge target above the quality ceiling.
const INTEGRITY_GAP := 0.05

## ladder.CHANCE_BASE_START / CHANCE_BASE_DECAY: the floor a realm offers with no
## huyệt work behind it. It DECLINES with depth (DEF-0079: the old pair rose into
## a falling ceiling and crossed at R26, leaving `chance_base >= chance_cap` on
## five realms).
const CHANCE_BASE_START := 0.49
const CHANCE_BASE_DECAY := 0.008

## ladder.CHANCE_CAP_HEADROOM: the cap is the floor plus half the quality ceiling
## plus this, so it sits above anything a fully trained body can roll.
const CHANCE_CAP_HEADROOM := 0.05

# --- Generator transcriptions (mirrors of the Python generator expressions) ---


func qi_progress_generator(index: int) -> float:
	# seed_systems.qi_progress: 100 * max(1, i)
	return 100.0 * maxf(1.0, float(index))


func qi_comprehension_generator(index: int) -> float:
	# seed_systems.qi_comprehension: 10 + 2 * max(0, i - 1)
	return 10.0 + 2.0 * maxf(0.0, float(index - 1))


func qi_dantian_quality_generator(index: int) -> float:
	# seed_systems.qi_dantian_quality: 0.50 + 0.01 * max(0, i - 1)
	return 0.50 + 0.01 * maxf(0.0, float(index - 1))


func mind_comprehension_generator(index: int) -> float:
	# RETIRED: this transcribed `seed_systems.mind_comprehension: 10 + 6i + 2i^2`,
	# a private quadratic in the ladder ORDINAL that disagreed with
	# `core/realm_power_table.tres` (1.00 -> 551.46) by up to 22.2x — a second power
	# curve for a binding entry gate. The ladder now governs it, so the SSOT is
	# `core/mind_comprehension_scale.gd` and the tests below delegate to it instead
	# of transcribing an expression. The Python generator at
	# `tools/cultivation/seed_systems.py:124` still carries the quadratic and is
	# owned by another live session; tracked in `docs/deferred.jsonl`.
	return MindComprehensionScale.required(RealmDefaults.ladder().realms()[index].id)


func mind_progress_generator(index: int) -> float:
	# seed_systems (mind): round(100 * max(1, i) ^ 1.45)
	return roundf(100.0 * pow(maxf(1.0, float(index)), 1.45))


func body_work_generator(index: int) -> float:
	# seed.labour_budget: the authored per-realm ladder
	return float(BODY_WORK_REQUIRED[index])


# --- DEF-0130: the retuned body ladders -------------------------------------
#
# The balance scalars below are transcriptions of `tools/cultivation/ladder.py`,
# which `cultivation retune` writes into all 30 `.tres` and `audit.validate`
# re-checks against. They exist here so the parity suite still fails when one of
# those numbers moves without the suite being told.


func integrity_maximum_generator(index: int) -> float:
	# ladder.integrity_maximum: 100 * (1 + 0.1 * i)
	return 100.0 * (1.0 + 0.1 * float(index))


func quality_ceiling_generator(index: int) -> float:
	# ladder.quality_ceiling: QUALITY_CEILING_BASE + QUALITY_STEP * i
	return QUALITY_CEILING_BASE + QUALITY_STEP * float(index)


func quality_gate_generator(index: int) -> float:
	# ladder.quality_gate: the ceiling less QUALITY_HEADROOM
	return quality_ceiling_generator(index) - QUALITY_HEADROOM


func integrity_target_generator(index: int) -> float:
	# ladder.integrity_target: the ceiling plus INTEGRITY_GAP
	return quality_ceiling_generator(index) + INTEGRITY_GAP


func free_physique_generator(index: int) -> float:
	# ladder.free_physique: every earlier realm's breakthrough reward plus one
	# milestone each, summed. Zero at R1.
	var granted := 0.0
	for earlier in range(index):
		granted += PHYSIQUE_REWARD + integrity_maximum_generator(earlier) * MILESTONE_PHYSIQUE_RATIO
	return granted


func body_physique_required_generator(index: int) -> float:
	# ladder.physique_required: the free grant plus a 12.0 margin, so the ladder
	# never hands out the physique its own gate demands (DEF-0104).
	return free_physique_generator(index) + 12.0


func chance_base_generator(index: int) -> float:
	# ladder.chance_base: CHANCE_BASE_START - CHANCE_BASE_DECAY * i
	return CHANCE_BASE_START - CHANCE_BASE_DECAY * float(index)


func chance_cap_generator(index: int) -> float:
	# ladder.chance_cap: the floor + half the quality ceiling + the headroom
	return (
		chance_base_generator(index) + 0.5 * quality_ceiling_generator(index) + CHANCE_CAP_HEADROOM
	)


func cut_budget(index: int, divisor: int) -> float:
	# BodyRealmSeed._cut_budget: the budget divided by `divisor`, rounded half up
	# (`floorf(x + 0.5)`). Transcribed because the derived sub-budgets have no
	# `.tres` line left to read them from.
	return floorf(body_work_generator(index) / float(maxi(1, divisor)) + 0.5)


# --- qi parity --------------------------------------------------------------


func test_qi_progress_required_matches_generator() -> void:
	var realms := RealmDefaults.ladder().realms()
	for index in range(realms.size()):
		var seed := QiRealmSeed.for_realm(realms[index].id)
		assert_almost_eq(
			seed.progress_required,
			qi_progress_generator(index),
			"qi R%d progress_required" % (index + 1)
		)


func test_qi_comprehension_required_matches_generator() -> void:
	var realms := RealmDefaults.ladder().realms()
	for index in range(realms.size()):
		var seed := QiRealmSeed.for_realm(realms[index].id)
		assert_almost_eq(
			seed.comprehension_required,
			qi_comprehension_generator(index),
			"qi R%d comprehension_required" % (index + 1)
		)


func test_qi_dantian_quality_matches_generator() -> void:
	var realms := RealmDefaults.ladder().realms()
	for index in range(realms.size()):
		var seed := QiRealmSeed.for_realm(realms[index].id)
		assert_almost_eq(
			seed.dantian_quality_required,
			qi_dantian_quality_generator(index),
			"qi R%d dantian_quality_required" % (index + 1)
		)


func test_qi_dantian_capacity_is_the_quarter_per_realm_ladder() -> void:
	# qi.dantian_capacity == mind.sea_capacity == 100 * (1 + 0.25 * i)
	var realms := RealmDefaults.ladder().realms()
	for index in range(realms.size()):
		var qi_seed := QiRealmSeed.for_realm(realms[index].id)
		var mind_seed := MindRealmSeed.for_realm(realms[index].id)
		var expected := 100.0 * (1.0 + 0.25 * float(index))
		assert_almost_eq(
			qi_seed.dantian_capacity, expected, "qi R%d dantian_capacity" % (index + 1)
		)
		assert_almost_eq(mind_seed.sea_capacity, expected, "mind R%d sea_capacity" % (index + 1))


func test_qi_first_step_is_flat() -> void:
	# R1 -> R2 does not raise the qi's work or quality gate.
	var r1 := QiRealmSeed.for_realm(&"qi_refining")
	var r2 := QiRealmSeed.for_realm(&"foundation")
	assert_almost_eq(r2.progress_required, r1.progress_required, "qi progress flat at R1->R2")
	assert_almost_eq(
		r2.comprehension_required, r1.comprehension_required, "qi comprehension flat at R1->R2"
	)
	assert_almost_eq(
		r2.dantian_quality_required, r1.dantian_quality_required, "qi quality flat at R1->R2"
	)


# --- mind parity ------------------------------------------------------------


func test_mind_progress_required_matches_generator() -> void:
	var realms := RealmDefaults.ladder().realms()
	for index in range(realms.size()):
		var seed := MindRealmSeed.for_realm(realms[index].id)
		assert_almost_eq(
			seed.progress_required,
			mind_progress_generator(index),
			"mind R%d progress_required" % (index + 1)
		)


func test_mind_comprehension_required_matches_generator() -> void:
	# The shipped seed IS the ladder answer, to the last decimal. `required()` returns
	# `round(SCALE * power)` and the `.tres` carries that same nearest integer, so
	# this is an equality rather than a tolerance: a hand-edited literal fails here.
	var realms := RealmDefaults.ladder().realms()
	for index in range(realms.size()):
		var seed := MindRealmSeed.for_realm(realms[index].id)
		assert_eq(
			seed.comprehension_required,
			mind_comprehension_generator(index),
			"mind R%d comprehension_required" % (index + 1)
		)


func test_mind_insight_is_half_of_comprehension() -> void:
	# mind.insight_required is exactly 0.5x the gate, and it stays a DERIVATION of it
	# rather than a second hand-typed ladder (BL-0146 carries deleting the field).
	var realms := RealmDefaults.ladder().realms()
	for index in range(realms.size()):
		var seed := MindRealmSeed.for_realm(realms[index].id)
		assert_eq(
			seed.insight_required,
			MindComprehensionScale.insight_floor(realms[index].id),
			"mind R%d insight_required" % (index + 1)
		)


# --- body parity ------------------------------------------------------------


func test_body_work_required_matches_generator() -> void:
	var realms := RealmDefaults.ladder().realms()
	for index in range(realms.size()):
		var seed := BodyRealmSeed.for_realm(realms[index].id)
		assert_almost_eq(
			seed.work_required, body_work_generator(index), "body R%d work_required" % (index + 1)
		)


func test_body_derived_sub_budgets_track_the_authored_budget() -> void:
	# DEF-0130: `work_required`, `acupoint_work` and `meridian_work` are no longer
	# authored lines. `BodyRealmSeed` derives them from `progress_required` and the
	# ladder index, so the seeds lost three duplicate copies of a number they
	# already carried. Nothing was dropped from the contract, but nothing in the
	# `.tres` can be read back to check the arithmetic either, so it is pinned here
	# against the same ladder the seeds are authored from.
	var realms := RealmDefaults.ladder().realms()
	for index in range(realms.size()):
		var seed := BodyRealmSeed.for_realm(realms[index].id)
		assert_almost_eq(
			seed.acupoint_work,
			cut_budget(index, 4 * maxi(1, index)),
			"body R%d acupoint_work" % (index + 1)
		)
		assert_almost_eq(
			seed.meridian_work,
			cut_budget(index, 4 * (index + 1)),
			"body R%d meridian_work" % (index + 1)
		)


func test_body_progress_required_tracks_work_required() -> void:
	# body.progress_required and body.work_required are the same authored budget;
	# the gate is a labour budget, so the two numbers describe one thing.
	var realms := RealmDefaults.ladder().realms()
	for index in range(realms.size()):
		var seed := BodyRealmSeed.for_realm(realms[index].id)
		assert_almost_eq(
			seed.progress_required,
			body_work_generator(index),
			"body R%d progress_required" % (index + 1)
		)


func test_body_insight_required_still_matches_its_own_ladder() -> void:
	# `body.insight_required == mind.comprehension_required == 10 + 6i + 2i^2` was
	# asserted here as a SHARED sequence. It is GONE, on purpose, and the same
	# reasoning DEF-0130 applied to `body.physique_required == qi.comprehension_required`
	# applies here: the equality was a coincidence of authoring that coincided
	# numerically at HEAD, not a balance rule. The two paths ask different questions
	# of the same number — the mind path prices mental study for its entry gate,
	# while the body's `insight_required` is both the body's own entry gate
	# (`body_cultivation/breakthrough_condition.gd:45`) AND a term in its breakthrough
	# CHANCE (`advancement.gd:62`: `0.1 + 0.01 * insight_required`). Re-pinning them
	# equal would mean dragging a second path's gate and its dice onto the mind
	# path's ladder, which is a balance ruling nobody made.
	#
	# What remains is the coverage that was real: the body's own ladder is unchanged,
	# so it is still pinned to its own generator expression. The mind side is now
	# pinned to the ladder in `test_mind_comprehension_required_matches_generator`.
	var realms := RealmDefaults.ladder().realms()
	for index in range(realms.size()):
		var body_seed := BodyRealmSeed.for_realm(realms[index].id)
		var expected := 10.0 + 6.0 * float(index) + 2.0 * float(index) * float(index)
		assert_almost_eq(
			body_seed.insight_required, expected, "body R%d insight_required" % (index + 1)
		)


func test_body_physique_required_matches_generator() -> void:
	# DEF-0130. This used to read `body.physique_required == qi.comprehension_required
	# == 10 + 2 * max(0, i-1)`, and that assertion is DELIBERATELY retired rather
	# than repaired. The two ladders were never one balance rule: qi's
	# `comprehension_required` prices mental study, and the body's floor prices
	# base physique. Pinning them equal was a coincidence of authoring that
	# happened to coincide numerically at HEAD - and it was numerically impossible
	# to keep while the floor did its job. DEF-0104 recorded that the ladder hands
	# out more physique on arrival than the gate asks for on 26 of 30 realms
	# (primordial_origin: 66 asked against 197.20 granted), so the floor had to be
	# re-derived as `free grant + margin`. qi's ladder rises +2 per realm; the
	# body's free grant rises with each realm's `integrity_maximum`. Those two
	# curves cannot be equal at more than a handful of realms, so holding the
	# equality would have re-broken DEF-0104 to keep an accident alive.
	#
	# What replaces it is the invariant the coupling was standing in for: the
	# floor must be a floor the player can actually be under, which means it must
	# sit strictly ABOVE everything the ladder grants on arrival.
	var realms := RealmDefaults.ladder().realms()
	for index in range(realms.size()):
		var seed := BodyRealmSeed.for_realm(realms[index].id)
		assert_almost_eq(
			seed.physique_required,
			body_physique_required_generator(index),
			"body R%d physique_required" % (index + 1)
		)


func test_body_physique_gate_clears_what_the_ladder_grants_for_free() -> void:
	# The gate-soundness half of the assertion above, checked against the seeds
	# rather than the formula, so it cannot be satisfied by a formula and a seed
	# that agree with each other and not with the runtime.
	# `BodyBreakthroughCondition` compares base PHYSIQUE against the floor, and
	# the only base-physique writers are the breakthrough reward and the
	# milestone bonus (`BodyProgress.grant`), so arrival physique is fully
	# determined by the ladder. Mirrors `tools/cultivation/audit.py`.
	var realms := RealmDefaults.ladder().realms()
	var granted := 0.0
	for index in range(realms.size()):
		var seed := BodyRealmSeed.for_realm(realms[index].id)
		assert_eq(
			seed.physique_required > granted,
			true,
			(
				"body R%d physique floor %.2f is above the %.2f granted on arrival"
				% [index + 1, seed.physique_required, granted]
			)
		)
		granted += float(seed.rewards.get("physique", 0.0))
		granted += seed.integrity_maximum * MILESTONE_PHYSIQUE_RATIO


func test_body_quality_ladders_match_generator() -> void:
	# The quality ceiling, the entry gate a fixed headroom below it, and the
	# reservoir target above it. Before the retune the gate WAS the ceiling, which
	# pinned average huyệt quality at the moment of an attempt to a single number
	# and made acupoint quality unable to enter the roll anywhere.
	var realms := RealmDefaults.ladder().realms()
	for index in range(realms.size()):
		var seed := BodyRealmSeed.for_realm(realms[index].id)
		assert_almost_eq(
			seed.quality_target,
			quality_ceiling_generator(index),
			"body R%d quality_target" % (index + 1)
		)
		assert_almost_eq(
			seed.quality_required,
			quality_gate_generator(index),
			"body R%d quality_required" % (index + 1)
		)
		assert_almost_eq(
			seed.integrity_target,
			integrity_target_generator(index),
			"body R%d integrity_target" % (index + 1)
		)


func test_body_chance_band_matches_generator_and_stays_live() -> void:
	# `BodyAdvancement._chance` is `chance_base + quality * 0.5` clamped to
	# `chance_cap`, so a cap that is not strictly above `base + quality*0.5` at the
	# top of the span an actor can hold swallows the huyệt term. DEF-0079 recorded
	# exactly that on five realms. Assert both the recipe and the property.
	var realms := RealmDefaults.ladder().realms()
	for index in range(realms.size()):
		var seed := BodyRealmSeed.for_realm(realms[index].id)
		assert_almost_eq(
			seed.chance_base, chance_base_generator(index), "body R%d chance_base" % (index + 1)
		)
		assert_almost_eq(
			seed.chance_cap, chance_cap_generator(index), "body R%d chance_cap" % (index + 1)
		)
		# The span is the gate up to the previous realm's ceiling, because that is
		# what an actor entering this realm can actually be holding.
		var reach := seed.quality_target
		if index > 0:
			reach = BodyRealmSeed.for_realm(realms[index - 1].id).quality_target
		var worst := minf(seed.chance_base + 0.5 * seed.quality_required, seed.chance_cap)
		var best := minf(seed.chance_base + 0.5 * reach, seed.chance_cap)
		assert_eq(best > worst, true, "body R%d has a live chance band" % (index + 1))


func test_body_first_step_moves_the_labour_budget_by_two() -> void:
	# R1 -> R2 moves the body's labour budget by exactly two labour units. The
	# retune did not touch `BODY_WORK_REQUIRED`, so this is still the same
	# invariant it always was; only the way the budget is published to the seed
	# changed (`work_required` is derived, `progress_required` is the authored
	# line). `progress_required` is asserted here rather than the derived alias
	# so the check reads the authored data.
	var r1 := BodyRealmSeed.for_realm(&"qi_refining")
	var r2 := BodyRealmSeed.for_realm(&"foundation")
	assert_almost_eq(r2.progress_required, r1.progress_required + 2.0, "body R1->R2 step is +2")


# --- Step ratios the technique ladder is sized against ----------------------


func test_qi_progress_step_ratio_floor_is_pinned() -> void:
	# DEF-0083 / ADR 0055: the technique learning-cost ladder is sized so its
	# per-realm step stays at or below the qi's work-budget step. The tightest
	# step on the strictly rising part of the qi ladder is R29 -> R30.
	#
	# The scan starts at R2. R1 -> R2 is deliberately flat (both are 100), so its
	# ratio is 1.0 and it is not a work-budget step - including it would measure
	# an authoring artifact instead of the ladder the technique system is sized
	# against. R2 -> R3 is the 2.0x jump off the flat, which is likewise not the
	# tightest step.
	var realms := RealmDefaults.ladder().realms()
	var worst_ratio := INF
	var worst_label := ""
	for index in range(3, realms.size()):
		var previous := QiRealmSeed.for_realm(realms[index - 1].id).progress_required
		var current := QiRealmSeed.for_realm(realms[index].id).progress_required
		var ratio := current / previous
		if ratio < worst_ratio:
			worst_ratio = ratio
			worst_label = "%s->%s" % [realms[index - 1].id, realms[index].id]
	# The floor is measured at R29 -> R30 (dao_ancestor -> primordial_origin).
	assert_eq(worst_label, "dao_ancestor->primordial_origin", "tightest step is R29->R30")
	assert_almost_eq(
		worst_ratio, QI_R29_R30_STEP, "minimum qi step ratio (%s)" % worst_label, STEP_RATIO_EPSILON
	)
	# ADR 0055's published floor. The shipped value is 1.0357142857142858, so
	# 1.035714 is the 6dp truncation of it and the floor is a "at or above"
	# bound, not an equality: a technique step may be this tight or looser, but
	# never tighter than the qi work budget it is paid out of.
	var at_or_above_floor := worst_ratio >= ADR_0055_QI_STEP_FLOOR
	assert_eq(at_or_above_floor, true, "qi step ratio stays at or above the ADR 0055 floor")


func test_qi_progress_step_ratio_only_ever_tightens() -> void:
	# On a linear 100 * i ladder the per-realm step ratio is (i+1)/i, so it falls
	# monotonically toward the top and its minimum is necessarily the last step.
	# If this ordering inverts, a realm has been re-authored out of order and the
	# ladder is no longer linear, which is what would move the ADR 0055 floor.
	var realms := RealmDefaults.ladder().realms()
	for index in range(4, realms.size()):
		var before_previous := QiRealmSeed.for_realm(realms[index - 2].id).progress_required
		var previous := QiRealmSeed.for_realm(realms[index - 1].id).progress_required
		var current := QiRealmSeed.for_realm(realms[index].id).progress_required
		var previous_ratio := previous / before_previous
		var ratio := current / previous
		var tightens := ratio <= previous_ratio + STEP_RATIO_EPSILON
		assert_eq(tightens, true, "qi step ratio tightens at R%d" % (index + 1))


func test_qi_progress_ladder_is_exactly_linear_above_r2() -> void:
	# Above R2 the ladder is 100 * i with no curve at all. This is the property
	# that makes the 1.035714 step the floor rather than an accident of one realm.
	var realms := RealmDefaults.ladder().realms()
	for index in range(2, realms.size()):
		var seed := QiRealmSeed.for_realm(realms[index].id)
		assert_almost_eq(
			seed.progress_required, 100.0 * float(index), "qi R%d is exactly 100*i" % (index + 1)
		)
